### ISSUE TITLE
The Stolen Letters

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#1002]
When I tried collecting the quest item, A Slashed Bundle of Letters, it disappeared before I could collect it. My loot window did not pop up either.

Quest details:
http://www.wowhead.com/quest=26667/the-stolen-letters

**Comment by AuraChan** [comment]
Disabling auto loot allows you to get the quest item. It seems it was auto loot causing the bug.

**Comment by GeneralCaveman** [comment]
I believe that as well for another quest but wowhead seems to be the problem.

http://www.wowhead.com/object=204462/pile-of-scraps

The server uses drop rates based wowhead and wowhead's method to determine drop rates are broken when it comes to situational drops (quests, profession based drops).

**Comment by HellscreamWoW** [comment]
Indeed. Thanks to Caveman for pointing that out. We have quite a bit of work ahead of us on the loot templates.

**Comment by Guybrush-Hellscream** [comment]
It's working.
