### ISSUE TITLE
[Quest] NPC No Drop this Quest : A Gold Pickup Schedule #1307

### ISSUE THREAD

**Issue by ElBondi34** [HellscreamWoW/Tracker#1010]
The NPC James Clark in Elwyn Forest no drop this quest :  http://www.wowhead.com/item=1307/gold-pickup-schedule
NPC :  http://www.wowhead.com/npc=13159/james-clark

**Comment by Guybrush-Hellscream** [comment]
[Fixed](http://www.hellscream-wow.com/log#2015.14.10.020107)
