### ISSUE TITLE
[Quest] Westfall Stew #26241

### ISSUE THREAD

**Issue by ElBondi34** [HellscreamWoW/Tracker#1017]
THis Quest isn't work because we can't take Okra . Need to check  completely the Quest .
Link : http://www.wowhead.com/quest=26241/westfall-stew

**Comment by ElBondi34** [comment]
and check the loot on NPC .

**Comment by Malae1** [comment]
What is wrong with the loot?

**Comment by Malae1** [comment]
Fixed
