### ISSUE TITLE
[NPC] "Cookie" McWeaksauce

### ISSUE THREAD

**Issue by Althin** [HellscreamWoW/Tracker#1045]
This NPC: http://www.wowhead.com/npc=17246/cookie-mcweaksauce should train us in cooking and be a cooking vendor. But that's options in his dialog frame are not clickable.
Here's cooking that should teach us: http://www.wowhead.com/spell=2550/cooking

**Comment by zwei7** [comment]
In Azuremyst I can't get him to teach me anything. I click and the option is unresponsive.
![wowscrnshot_110215_051802](https://cloud.githubusercontent.com/assets/15259298/10879311/4ab0a850-8121-11e5-8b7a-f19980ac3cee.jpg)
