### ISSUE TITLE
[Quest] Reclaiming the Ruins

### ISSUE THREAD

**Issue by Althin** [HellscreamWoW/Tracker#1046]
In this quest http://www.wowhead.com/quest=9513/reclaiming-the-ruins , wrathscale naga http://www.wowhead.com/npc=17193/wrathscale-naga are isntantly complete after getting quest from quest giver but it's visual bug, when we atttack one of them it's reset.

Another bug with mobs from this quest is lowered drop rate for Rune covered Tablet: http://www.wowhead.com/npc=17193/wrathscale-naga or it's not exist yet. 
It should have:
Wrathscale Myrmidon: http://www.wowhead.com/npc=17194/wrathscale-myrmidon - 6% drop rate.
Wrathscale Naga: http://www.wowhead.com/npc=17193/wrathscale-naga - 5% drop rate.
Wrathscale Siren: http://www.wowhead.com/npc=17195/wrathscale-siren - 4% drop rate. 

:)

**Comment by Guybrush-Hellscream** [comment]
Fixed.
