### ISSUE TITLE
[item] Quest Items for Repeatable Quests

### ISSUE THREAD

**Issue by ticklex** [HellscreamWoW/Tracker#1048]
How it should work: Items needed for  repeatable quests should drop without having the quest-means that items must be in the normal loot and most of them are even tradable.

How it works: Right now NO items for that repeatable quests drop. They can only be looted if player has got a pre-repeatable quest in quest log. But after having completed that items never drop again at the moment.

Seems like that items are marked in database as "only drop for quest" - what is totally wrong! Below a list of non dropping items:

http://www.wowhead.com/item=20404/encrypted-twilight-text
http://www.wowhead.com/item=21383/winterfall-spirit-beads
http://www.wowhead.com/item=25433/obsidian-warbeads
http://www.wowhead.com/item=29209/zaxxis-insignia
http://www.wowhead.com/item=24401/unidentified-plant-parts
http://www.wowhead.com/item=24449/fertile-spores
http://www.wowhead.com/item=24291/bog-lord-tendril
http://www.wowhead.com/item=29425/mark-of-kiljaeden
http://www.wowhead.com/item=30809/mark-of-sargeras
http://www.wowhead.com/item=29740/fel-armament
http://www.wowhead.com/item=29426/firewing-signet
http://www.wowhead.com/item=30810/sunfury-signet
http://www.wowhead.com/item=29739/arcane-tome
http://www.wowhead.com/item=42780/relic-of-ulduar
http://www.wowhead.com/item=35188/nesingwary-lackey-ear
http://www.wowhead.com/item=21229/qiraji-lords-insignia
http://www.wowhead.com/item=21230/ancient-qiraji-artifact

**Comment by ticklex** [comment]
http://www.wowhead.com/item=22642/spinal-dust
http://www.wowhead.com/item=22641/rotting-heart

**Comment by Malae1** [comment]
Fixed in next update
