### ISSUE TITLE
Bloodscalp Trolls double spawns

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1055]
http://www.wowhead.com/npc=701/bloodscalp-mystic
http://www.wowhead.com/npc=595/bloodscalp-hunter

Not just limited to these guys but they seem to double spawn in locations throughout the area.

![wowscrnshot_062015_202835](https://cloud.githubusercontent.com/assets/12555606/8269836/f0535bbe-178a-11e5-9aec-7902459bd293.jpg)

**Comment by GeneralCaveman** [comment]
http://www.wowhead.com/npc=702/bloodscalp-scavenger

The double spawns seem to be happening outside the camp with these guys as well.

**Comment by GeneralCaveman** [comment]
![wowscrnshot_082715_132151](https://cloud.githubusercontent.com/assets/12555606/9527691/91ee77ca-4cbe-11e5-9b46-055818cc1588.jpg)

I think these might be double spawns as well.

**Comment by Malae1** [comment]
Got them.
