### ISSUE TITLE
[Quest][Westfall] Feeding the Hungry and the Hopeless 26271

### ISSUE THREAD

**Issue by ElBondi34** [HellscreamWoW/Tracker#1062]
This quest is not work , the npc no eat the object of quest . 
Link : http://www.wowhead.com/quest=26271/feeding-the-hungry-and-the-hopeless

**Comment by Thefakemccoy** [comment]
Just finished the quest with no problem if some one did it before you they get a feed buff which wont allow you to feed the same ones for like 2 mins

**Comment by GMTyrial** [comment]
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/184
