### ISSUE TITLE
Hunter - Mend Pet/Revive Pet

### ISSUE THREAD

**Issue by Malae1** [HellscreamWoW/Tracker#1078]
As of 6.0.2, Revive Pet and Mend Pet are integrated into one spot on your action bar.

Basically what this means, is that if your pet is alive, the button will show "Mend Pet". But if your pet has died, that same button turns into "Revive Pet". Very useful, especially when you are in a tough battle, when you click the button, if the pet has just died, instead it will revive your pet.

**Comment by Redrian-Hellscream** [comment]
Mend Pet should be integrated in Resurrect Pet, the same spell heals the pet and resurrects it when dead.

**Comment by Malae1** [comment]
To clarify in more detail: 

As of 6.0.2, Revive Pet and Mend Pet are integrated into one spot on your action bar.

Basically what this means, is that if your pet is alive, the button will show "Mend Pet". But if your pet has died, that same button turns into "Revive Pet". Very useful, especially when you are in a tough battle, when you click the button, if the pet has just died, instead it will revive your pet.

**Comment by Malae1** [comment]
Thanks for the info, updated the main topic.

**Comment by Grimoslav** [comment]
Hmmm... I am having an issue then, since my Revive Pet spell doesn't change in to Mend Pet spell...

**Comment by Malae1** [comment]
The reason this is open is because it does not currently work as should. You can make a macro for mend pet however for the time being. /cast mend pet should work.

**Comment by Grimoslav** [comment]
Macro works!!! Thank u a lot.

**Comment by EPS1L0N** [comment]
#2266
