### ISSUE TITLE
[Quest][Loot][Westfall] In Defense of Westfall !

### ISSUE THREAD

**Issue by ElBondi34** [HellscreamWoW/Tracker#1081]
The quest are work but the loot is very very low . I need to kill 20-25 Gnoll to get object of the quest .
Link : http://www.wowhead.com/quest=26286/in-defense-of-westfall
Loot Object : http://www.wowhead.com/item=58111/gnoll-attack-orders

**Comment by Guybrush-Hellscream** [comment]
It's working. #2235
