### ISSUE TITLE
[Quest][Loot][WestFall] Captain Sanders Hidden Treasure #26353

### ISSUE THREAD

**Issue by ElBondi34** [HellscreamWoW/Tracker#1086]
The NPC no loot the item for start the quest . The player need to go on the first spawn on the quest for activate the Quest of Captain Sanders . 
Link : http://www.wowhead.com/quest=26353/captain-sanders-hidden-treasure

**Comment by Guybrush-Hellscream** [comment]
Fixed. :palm_tree:
