### ISSUE TITLE
[Talent][Passive][Rogue] Shadow Focus #108209

### ISSUE THREAD

**Issue by ElBondi34** [HellscreamWoW/Tracker#1088]
This Talent is not bugged but normally it's activated when the rogue are invisible . Currently , the talent are activated when the rogue are not Invisible and invisible , it's so op bug .
Link : http://www.wowhead.com/spell=108209/shadow-focus

**Comment by Cyuty** [comment]
I tested this one and it work's perfect, it needs to be closed.
