### ISSUE TITLE
Night elf starting zone bug

### ISSUE THREAD

**Issue by FlameChampion34** [HellscreamWoW/Tracker#11]
When making a new night elf character, I noticed that in the starting zone of this race, has a bug with the first quest giver (Ilthalaine). The issue is that there are more than one of the same npc, while it should e only one, and also there's another bug, the quests that he gives are all available at once, while only one should be available at level 1, and the quest that is available from this npc is also available from the mobs that are for the quest "The Balance of Nature", which is not normal.
Pics that show the bugs:
http://store.picbg.net/pubpic/06/59/e06d1e13c3040659.jpg

http://store.picbg.net/pubpic/B7/AD/496b15f56823b7ad.jpg

Link from wowhead:

http://www.wowhead.com/npc=2079

**Comment by ArthonTheAvenger** [comment]
I think this issue should be closed as it's already solved.
