### ISSUE TITLE
(QUEST) Into the Dragon's Mouth - Badlands

### ISSUE THREAD

**Issue by Kelpo122** [HellscreamWoW/Tracker#1119]
http://www.wowhead.com/quest=27826/into-the-dragons-mouth

Rhea (http://www.wowhead.com/npc=46654/rhea) is not spawned.

**Comment by Kelpo122** [comment]
She is not spawned to turn in this quest either
http://www.wowhead.com/quest=27764/a-strange-request

**Comment by HellscreamWoW** [comment]
ref #2235
