### ISSUE TITLE
website and client 

### ISSUE THREAD

**Issue by Nienz** [HellscreamWoW/Tracker#1137]
Hey not sure where to post this but here because i cant access ur wep page or login to the server at all, i can explain what happened, i was at silithus yesterday, went to the bugs mobs and one mob insta charmed me 24/7 and after 20min of that i finally killed it, hearthstoned out asap and went underground at sw so i alt f4 it and after that i cant neither login on the site or the game, get constantly battle net error #2. i deleted the entire wow folder, got it reinstalled from BN, did all the things im suppose to do on  that and i cant still do anything, would appreciate for any assistance on this. my char is alliance sham named Kaikai

**Comment by Malae1** [comment]
Have you since then be able to connect to either?

**Comment by Nienz** [comment]
no i havnt been able to either acces the website, get a "site is unavailable" msg on that, and on the client i get bnet error #2, and its only on those two i cant do anything about, u think resetting my modem and router would help? cus that i havnt done yet

**Comment by Nienz** [comment]
well i reseted my modem and router, still same thing for me

**Comment by Nienz** [comment]
so after i reseted, i tried go to ur website, didnt work so i ran a diagnostic on my end to see if theres something wrong but there wasnt any, and it found a problem tho and the msg was "your computer appears to be correctly configured, but the device or resource (hellscream-wow.com) is not responding"

**Comment by Malae1** [comment]
What is your account?

**Comment by Nienz** [comment]
u want the acc name? if so its quezla@live.com

**Comment by Nienz** [comment]
is it possible i got banned? would explain alot, but then again i didnt get a warning from a gm or anything, all i did was tryiing to get away from that mob, and if u wanna know what happened im in the guild "Heroes Gone Wild" and if Yagami or Flare is online they know what happened, still if thats not the prob then im out of ideas, means my dream finding that rare horde aint gonna happen, and i cant do myt duty as an alliance, and no more Dirge discussions on world chat either sigh...damn it

**Comment by Nienz** [comment]
oke just did another thing, used my laptop to get to the site, didnt work, used my phone, and didnt work aswell, used my oooooold damn comp thats been biting the dust for 2 years and no didnt work aswell, so ye, ow and reminds me, my forum name is Trolliewood

**Comment by Malae1** [comment]
Sorry for the long responses. I will check now and update this post.

**Comment by XEQT** [comment]
Do you have an Skype account ?
I would like to talk with you about this because so far you are not banned in any way.
Let me know if you got Skype and a name there.
And let me know what Company that you have for ISP.

**Comment by Nienz** [comment]
Hey, ye i got skype lemme just fire it up and change my pic there so u can find me there

**Comment by XEQT** [comment]
What's your name on Skype ?

**Comment by Nienz** [comment]
allright i fired up skype, name is Magnus Klang, got a japanese dragon as image

**Comment by XEQT** [comment]
It was a ISP problem. It's fixed now.
