### ISSUE TITLE
Panther Double Spawning

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1142]
http://www.wowhead.com/npc=736/panther

An issue was closed here https://github.com/HellscreamWoW/Tracker/issues/911 and the changelog stated that this issue was fixed. The mob is still double spawning. I made a comment on that issue and as an add on to one of my newer reports here https://github.com/HellscreamWoW/Tracker/issues/1054 but the issue has not been reopened.

**Comment by Malae1** [comment]
Will re-look in to this

**Comment by GeneralCaveman** [comment]
They are in front of the troll encampment there.  Nearly every single panther there is double spawning. To verify it, I killed them and watched two of them spawn in the same spot.

Now I checked a couple days ago so a server restart between now and then might have resolved the issue. I can check later on tonight.

**Comment by Malae1** [comment]
Please do, thanks!

**Comment by GeneralCaveman** [comment]
It is much harder to tell with the pathing but here are some.

![wowscrnshot_062015_201126](https://cloud.githubusercontent.com/assets/12555606/8269786/a6f7ec20-1788-11e5-85df-36f91d8bdbb7.jpg)

The coordinates are in the chat.

![wowscrnshot_062015_201059](https://cloud.githubusercontent.com/assets/12555606/8269789/b94b3db4-1788-11e5-8983-f601afb9ae4b.jpg)

After killing a group of two of them, this is where they spawn.

**Comment by GeneralCaveman** [comment]
Yeah pathing makes it pretty hard to spot if two are spawning in the same spot or for another reason. There is a dense bunch of guys here so I have to think there is something here as well.

![wowscrnshot_062015_202338](https://cloud.githubusercontent.com/assets/12555606/8269826/4ae70a4a-178a-11e5-8b59-7b6cc0fdfe4e.jpg)

**Comment by Malae1** [comment]
May be able to shrink these down as it does seem a lot larger than retails spawns.
