### ISSUE TITLE
Skullsplitter Troll Double spawns

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1153]
http://www.wowhead.com/npc=782/skullsplitter-scout
http://www.wowhead.com/npc=670/skullsplitter-witch-doctor
http://www.wowhead.com/npc=784/skullsplitter-beastmaster

![wowscrnshot_062015_211109](https://cloud.githubusercontent.com/assets/12555606/8269950/e0e8159c-1790-11e5-8678-ae6dde972a4b.jpg)

Edit: Some more
http://www.wowhead.com/npc=780/skullsplitter-mystic
http://www.wowhead.com/npc=696/skullsplitter-axe-thrower

![wowscrnshot_062115_011726](https://cloud.githubusercontent.com/assets/12555606/8270579/4b662aae-17b3-11e5-8f83-8083355d61dd.jpg)

**Comment by Malae1** [comment]
I believe this is exactly how it is on retail here.  Not certain, but I seem to recall these areas being much larger density than the outside.

**Comment by GeneralCaveman** [comment]
I think there are a couple similar setups in the area and they have 2-4 less mobs.

I will fly back out, look on the outside and other similar ruins.

**Comment by GeneralCaveman** [comment]
The other ruins in the same camp have 4-5 compared to this one's 8.

I took a better screenshot of the area. You can see a Witch Doctor and a Scout in stacked in one spot to my right and a Witch Doctor and a hunter stacked below me.

![wowscrnshot_062115_011453](https://cloud.githubusercontent.com/assets/12555606/8270574/24fc1bc6-17b3-11e5-93aa-c47f4ac5e1dc.jpg)

**Comment by Malae1** [comment]
This is true, they aren't double spawns, however they are on the same spawn point. If remembering correctly, these mobs rotate their spawns with each other, perhaps why they are spawning on top of one another.

**Comment by GeneralCaveman** [comment]
I have nothing to go on other than experience on the server but I believe that is true. When there is a large aimless group of humanoids/undead in (mainly) Azeroth, their different types tend to share spawns.

Now when you say double spawn, do you mean the same mob spawned twice or two things that are able to spawn at that location has spawned. Because of some creatures sharing spawns like this, I always try to use it in the context of the latter.
