### ISSUE TITLE
(MONK)  [Stance of the Sturdy Ox]

### ISSUE THREAD

**Issue by Awkakelen** [HellscreamWoW/Tracker#1167]
Stance of the Sturdy Ox sometimes quits me from that stance randomly, it happens fg. when I hit a mob with spells, autoattacks or he hits me with his those too. When I reloged, I have had that skill doubled.

**Comment by Gramur** [comment]
I had the same issue.... still have it.
Fixed it in a simple way.

When the stance drop, your spell bar revert to a old one. 
Simply replace all the power with the Sturdy OX from your spell book. 
By filling your off stance spell bar with the Sturdy ox, whenever the stance drop, you'll reactivate it.

Not a real fix, but it help not to get killed!

**Comment by Guybrush-Hellscream** [comment]
same as https://github.com/HellscreamWoW/Tracker/issues/338 and https://github.com/HellscreamWoW/Tracker/issues/525

**Comment by Kyramud** [comment]
i have got the same Problem with the stance of sturdy Ox and also if you use Keg Smash you didnt get any Chi :(

**Comment by SamixAiros** [comment]
Yeah, got the same problem. This so annoying making it a little bit difficult to play :( :-1:

**Comment by Moustachos** [comment]
Fixed on next update.
