### ISSUE TITLE
Shaman important bugs in early leveling.

### ISSUE THREAD

**Issue by anarkigrim** [HellscreamWoW/Tracker#1168]
Lighting shield should last 1 hour, instead it dissapears after 1 hit, this is big problem cuz u have to use shield 10000 times in one fight, and specialy if u are enha.
- Lava lash passive is bugged, it does not spread flame shock on other targets that are near.

**Comment by Malae1** [comment]
Ref #720

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020006.
