### ISSUE TITLE
[Quest] Totem of Tikti

### ISSUE THREAD

**Issue by Althin** [HellscreamWoW/Tracker#1190]
Questgiver: http://www.wowhead.com/npc=17361/totem-of-coo

For this quest we should jump from the cliff through the water but when we jump down there we should get quest buff that looks like golden wings. (I have no link for this skill, sorry but in questgiver link is screenshot with this skill). Now we have no those wings so if we jump down there we can be alive or we die fast. We can't complete this quest because http://www.wowhead.com/npc=17362/totem-of-tikti is missing in marked place.

**Comment by Guybrush-Hellscream** [comment]
Fixed.
