### ISSUE TITLE
quest not working from lvling zone 80-85

### ISSUE THREAD

**Issue by mrsanjose** [HellscreamWoW/Tracker#1191]
hello, hows everybody doing, it seems that the majority of the quest in mount hyjal are bugged, or dont work, it does'nt bother me that much but it is hard to lvl up 80-85.

On the other hand, vashj'ir doesnt work at all wich is a shame because i really love that lvling zone, the quest giver in Stormwind gives you the quest but after you get on the boat and arrive to the zone there no one there to continue the chane quest,

so if you guys can fix that please it would be great, thank you for your time.

**Comment by Malae1** [comment]
Please report individual quests in the future, not knowing which is bugged exactly does not help us much.
