### ISSUE TITLE
Healing for the Wounded wrong quest!!

### ISSUE THREAD

**Issue by FlameChampion34** [HellscreamWoW/Tracker#12]
While playing as a night elf priest I noticed a bug with a quest that is only for priest. The issue is that when reaching level 3 I get shadow word pain spell, but the class quest that I get is not for this spell, the quest that it gives me is called "Healing for the Wounded" and this quest is for older expansion of wow, cuz in this quest it ask me to use my flash heal while I have shadow word pain, now instead of this quest in WOD I should be getting the quest "Learning the Word", cuz this is the correct quest which has as objective to use the shadow word pain that I get at level 3, cuz flash heal in WOD is available at level 7. So you have to replace the quest "Healing for the Wounded" with quest "Learning the Word". :) 

http://www.wowhead.com/quest=26949/learning-the-word

http://wow.gamepedia.com/Quest:Healing_for_the_Wounded

**Comment by Max-Hellscream** [comment]
Fixed.
