### ISSUE TITLE
Bloodstone teleporter doesn't work

### ISSUE THREAD

**Issue by Rexey** [HellscreamWoW/Tracker#1204]
http://www.wowhead.com/object=203180/bloodstone-teleporter
Though it is successfully activated during the quest (http://www.wowhead.com/quest=25684/attune-the-bloodstone), it doesn't work.

**Comment by Lazyg33k** [comment]
![bloodstoneteleport](https://cloud.githubusercontent.com/assets/15207677/10839932/e23d499a-7eaf-11e5-800b-61fa8d82e15b.jpg)
yes its not working still

**Comment by GMTyrial** [comment]
Duplicate. Solution here : https://github.com/HellscreamWoW/Tracker/issues/640

**Comment by zwei7** [comment]
Still not fixed.

**Comment by zwei7** [comment]
Yay it is going to get fixed!

**Comment by habagatamihan** [comment]
It's working
