### ISSUE TITLE
Wanted! Otto and Falconcrest

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1212]
http://www.wowhead.com/npc=2599/otto
http://www.wowhead.com/npc=2597/lord-falconcrest

The head's of these guys should be a 100% drop.

www.wowhead.com/item=4506/stromgarde-badge
http://www.wowhead.com/quest=26079/wanted-otto-and-falconcrest

The quest drops for all mobs in the area are also ridiculously low. This is the wowhead problem discussed on other issues so I do not know the exact drop rates for these. But by all accounts they should be much higher than they are.

**Comment by Guybrush-Hellscream** [comment]
It's working.
