### ISSUE TITLE
NPC Still missing - Master Harris in Darkshire

### ISSUE THREAD

**Issue by Dracoknight256** [HellscreamWoW/Tracker#1229]
The issue written previously by somebody else got closed for some reason even though he's still missing. 
Master Harris in Darkshire on Raven Hill is missing and you can't complete quests that lead to him. Due to the fact that he's one of the main NPC's in Darkshire This makes many quests unfinishable.  Fixing him would fix most of darkshire issues since only two quests there are bugged.

**Comment by omigawail** [comment]
Confirmed, am standing at his exact spawning location. the Duskwood quest chain can't be completed because of this missing npc.

**Comment by HellscreamWoW** [comment]
ref #2235
