### ISSUE TITLE
Tuning the Gnomecoder - Quest item missing

### ISSUE THREAD

**Issue by Dracoknight256** [HellscreamWoW/Tracker#1232]
http://www.wowhead.com/quest=26512/tuning-the-gnomecorder

The Gnomcoder is not given to you by quest NPC so there's no way to complete this quest

**Comment by zwei7** [comment]
At the location where the professor should be casting the gnomecoder spell, but nothing.
![wowscrnshot_103115_022928](https://cloud.githubusercontent.com/assets/15259298/10862249/4e2ee664-7f77-11e5-8ba6-346cddfaf11b.jpg)

**Comment by GMTyrial** [comment]
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/415
