### ISSUE TITLE
Quest,Tirisfal Glade, A Scarlet Letter

### ISSUE THREAD

**Issue by MirrorWraith** [HellscreamWoW/Tracker#1240]
http://www.wowhead.com/quest=24979/a-scarlet-letter
uncompleteable because there's no prisoner, missing NPC 
http://www.wowhead.com/npc=38999/lilian-voss
thanks

**Comment by Guybrush-Hellscream** [comment]
[Fixed.](http://www.hellscream-wow.com/log#2015.21.09.020012)
