### ISSUE TITLE
Auto loot button

### ISSUE THREAD

**Issue by skorge1** [HellscreamWoW/Tracker#1246]
When i try the auto loot thing. it only loots the money and it doesn't loot any other items automatically and you have to click on the items 1 by 1

**Comment by Malae1** [comment]
Are you sure this is turned on in your options?

**Comment by skorge1** [comment]
i do it the manual  shift+ left click

**Comment by Damvs** [comment]
J'ai activé la fouille automatique dans interface, et quand je ramasse un butin ça fait comme dit précédemment cela ramasse l'argent mais pas les butins.

**Comment by Malae1** [comment]
This issue should now be solved on the live realms
