### ISSUE TITLE
Low drop rate on Mirefin Head

### ISSUE THREAD

**Issue by skorge1** [HellscreamWoW/Tracker#1261]
i had to kill 5 murlocs before i could find the first http://www.wowhead.com/item=5847/mirefin-head and i thought that the drop rate for this item was low because when i checked on wowhead it gave percentages and then when i checked on http://eu.battle.net/wow/en/item/5847#tab=dropCreatures the rate of mirefin was high.

**Comment by Guybrush-Hellscream** [comment]
Quest items of [Hungry as an Ogre!](http://www.wowhead.com/quest=27191/hungry-as-an-ogre) in Dustwallow Marsh

**Comment by Guybrush-Hellscream** [comment]
Fixed. :palm_tree:
