### ISSUE TITLE
Shaman Spell bug:Lava Burst

### ISSUE THREAD

**Issue by skorge1** [HellscreamWoW/Tracker#1262]
http://www.wowhead.com/spell=51505/lava-burst does not hit as a critical strike. it also doesn't do the correct damage it is doing lower than it should.

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020005.

**Comment by niveks1** [comment]
Why this issue is closed? If Lava Burst still makes a low damage, when this spell should makes more damage than  the others spells

**Comment by EPS1L0N** [comment]
4957 damage * 200% crit bonus = 9914. it is hitting for 9916. that is why this is closed.
![Lava Burst](http://puu.sh/mK3z6/70925738e8.jpg)

**Comment by niveks1** [comment]
only you have 4957 damage in that spell
![wowscrnshot_012616_090748](https://cloud.githubusercontent.com/assets/16891849/12581459/0976d114-c40d-11e5-9847-28d42709af05.jpg)

**Comment by Tregeta** [comment]
And what happens when you cast it on enemies?

**Comment by niveks1** [comment]
I only say to lava burst should makes 118.976% of spell power because ligthning bolt only has 104% of spell power and it makes a  superior damage than lava burst

**Comment by Tregeta** [comment]
Please show us photos of Lavaburst being cast on a training dummy of the numbers not matching. Tooltips can sometimes provide misinformation on actual damage numbers.

**Comment by niveks1** [comment]
sorry I was wrong, I had miscalculated
