### ISSUE TITLE
Quest bug: Feeding the Hungry and Hopeless

### ISSUE THREAD

**Issue by Roensilver** [HellscreamWoW/Tracker#1266]
the npc no funktion when i use the Quest Item "Westfall Stew"

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/184
https://github.com/HellscreamWoW/Tracker/issues/1062

**Comment by Thefakemccoy** [comment]
Just finished the quest with no problem if some one did it before you they get a feed buff which wont allow you to feed the same ones for like 2 mins
