### ISSUE TITLE
Quest: Fine Linen Goods

### ISSUE THREAD

**Issue by vegax87** [HellscreamWoW/Tracker#1274]
the drop rates of Linen Scrap is very low and I killed almost 30 bandits to drop these pieces

Quest: http://www.wowhead.com/quest=83/fine-linen-goods

Linen Scrap: http://www.wowhead.com/item=1019/linen-scrap

**Comment by Guybrush-Hellscream** [comment]
So far I've killed 7 of them to gather 6 Linen scraps.
