### ISSUE TITLE
Caster Mobs are much stronger than normal

### ISSUE THREAD

**Issue by vegax87** [HellscreamWoW/Tracker#1275]
I leveled up my mage in Elwynn Forest but I was surprised when Kobold Geomancers killed me with 2 fireballs, same thing with Mage Bandits at level 9 spreaded in the Eastern zone of Elwynn Forest (I don't remember their names sorry)

http://www.wowhead.com/npc=476/kobold-geomancer

I tried to use Counterspell but it doesn't work, and Questing becomes more tedius than it should really be.. :(

**Comment by tribaljet** [comment]
The same happens with Kobold Geomancers inside Jasperlode Mine in Elwynn Forest and Riverpaw Mystics in Westfall, with 2-3 spell hits meaning death.
