### ISSUE TITLE
Quest Drop rate: Feast & Famine

### ISSUE THREAD

**Issue by vegax87** [HellscreamWoW/Tracker#1278]
Fresh Dirt droprate is very very low, it should be 100%

Quest: http://www.wowhead.com/quest=26230/feast-or-famine

Fresh Dirt: http://www.wowhead.com/item=57789/fresh-dirt

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/809

**Comment by Guybrush-Hellscream** [comment]
Droprate was 100% for me, 5 out of 5.
