### ISSUE TITLE
Spell Bug: Water Elemental's Waterbolt

### ISSUE THREAD

**Issue by vegax87** [HellscreamWoW/Tracker#1279]
My Water Elemental doesn't make any damage using its spell Waterbolt, it's basically useless

Spell: http://www.wowhead.com/spell=31707/waterbolt

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/595

**Comment by GeneralCaveman** [comment]
• Fixed damage and healing calculations for player spells that utilize Spell Power and/or Attack Power

It seems player spells also includes their pets as this issue seems to be resolved. Waterbolt looks to be doing full damage.
