### ISSUE TITLE
Shaman Spell bug:Lava Surge

### ISSUE THREAD

**Issue by skorge1** [HellscreamWoW/Tracker#1300]
http://www.wowhead.com/spell=77756/lava-surge does not make lava burst proc

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020006.

**Comment by skorge1** [comment]
This is not fixed properly it when it procs the cooldown isn't reset.

**Comment by manic17** [comment]
Same issue as #2345
