### ISSUE TITLE
Quest Cooking : Careful, This Fruit Bites Back

### ISSUE THREAD

**Issue by vation1234** [HellscreamWoW/Tracker#1308]
http://www.wowhead.com/quest=26227/careful-this-fruit-bites-back

can not I took:   http://www.wowhead.com/item=57766/prickly-pear-fruit

**Comment by Dev-iL** [comment]
@Malae1 @Guybrush-Hellscream This report is simply wrong! The quest is working. The OP must've been standing too far from the cactus when looting.
![Proof](http://i.imgur.com/1ZFIjxt.jpg)

**Comment by Guybrush-Hellscream** [comment]
Closed, thank you!
