### ISSUE TITLE
Specializations, Talents and Glyphs glitched

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1309]
On my gnomish monk, it seems like I am unable to select a specialization. Only the first choice is highlighted and when you click learn, nothing comes from it.

![wowscrnshot_071315_062748](https://cloud.githubusercontent.com/assets/12555606/8647714/761d1c9a-2928-11e5-88e6-97f1a03d6526.jpg)

![wowscrnshot_071315_062913](https://cloud.githubusercontent.com/assets/12555606/8647718/7bd7b3d4-2928-11e5-9710-a42ce35358be.jpg)

Also the glyph screen looks like this.

![wowscrnshot_071315_062756](https://cloud.githubusercontent.com/assets/12555606/8647720/83d65068-2928-11e5-8d51-aa15d39ed7af.jpg)

**Comment by Malae1** [comment]
Specializations are fixed now, can you confirm this also fixed anything else?

**Comment by GeneralCaveman** [comment]
I can check once the server is back online.

**Comment by GeneralCaveman** [comment]
It looks to be resolved. All specializations, talents and glyphs have been reset so everything seems good.

You can close this issue, along with this one https://github.com/HellscreamWoW/Tracker/issues/1313 as it is a duplicate.
