### ISSUE TITLE
Shell of Shadra

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1312]
http://www.wowhead.com/item=58779/shell-of-shadra

I believe this thing should have a 100% drop rate.

**Comment by Guybrush-Hellscream** [comment]
Quest : 
(A) http://www.wowhead.com/quest=26530/the-shell-of-shadra
(H) http://www.wowhead.com/quest=26418/the-shell-of-shadra

**Comment by Guybrush-Hellscream** [comment]
Fixed.
