### ISSUE TITLE
Summit of Fate

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1314]
www.wowhead.com/quest=26517/summit-of-fate

You can't seem to loot the idols from the bodies.

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/761 Duplicate of this issue

**Comment by GMTyrial** [comment]
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/762
