### ISSUE TITLE
Umboda's Head

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1315]
http://www.wowhead.com/item=58236/umbodas-head

I believe this item should have a 100% drop rate which is currently doesn't.

**Comment by Guybrush-Hellscream** [comment]
Quest : 
(A) http://www.wowhead.com/quest=26518/heads-up
(H) http://www.wowhead.com/quest=26366/heads-up

**Comment by Guybrush-Hellscream** [comment]
Fixed. #2235
