### ISSUE TITLE
Talent/Glyph Reset Loading Screens.

### ISSUE THREAD

**Issue by Malae1** [HellscreamWoW/Tracker#1321]
The particular issue causes the talents/glyphs that have any sort of cooldown reduction or distance increase for spells to reset upon any sort of loading screen.. It seems to be happening to more than one class, if not all classes.

**Comment by tribaljet** [comment]
Indeed, Unbreakable Spirit (http://www.wowhead.com/spell=114154/unbreakable-spirit) is selected under Talents as learned but isn't effective, something that happened twice so far.
