### ISSUE TITLE
Druid - Spell - Stampeding Roar

### ISSUE THREAD

**Issue by Kwyzard** [HellscreamWoW/Tracker#1339]
http://www.wowhead.com/spell=106898/stampeding-roar
"The Druid roars, increasing the movement speed of all friendly players within 10 yards by 60% for 8 sec and removing all roots and snares on those targets.

Using this ability outside of Bear Form or Cat Form activates Bear Form."

Doesn't break any root/slow 
Doesn't morph in Bear form if no Form activated
Speed is ok though

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020010.
