### ISSUE TITLE
Druid - Spell - Shred

### ISSUE THREAD

**Issue by Kwyzard** [HellscreamWoW/Tracker#1341]
http://www.wowhead.com/spell=5221/shred
"Shred the target, causing 540% Physical damage to the target
Being stealthed increases damage by 20% and doubles critical strike chance. Damage increased by 20% against bleeding targets."

Being stealthed doesn't increase the damage by 20% + doesn't double critical chance
On Bleeding target doesn't increase the damage by 20% 

About the damage i can't actually know, how can we do to compare from official server ? is there an addon or something ?

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020010.
