### ISSUE TITLE
Druid - Spell - Leader of the Pack

### ISSUE THREAD

**Issue by Kwyzard** [HellscreamWoW/Tracker#1342]
http://www.wowhead.com/spell=17007/leader-of-the-pack
"While in Bear Form or Cat Form, increases critical strike chance of all party and raid members within 100 yards by 5%.

Also causes your melee critical strikes to heal you for 3% of your health.  This effect cannot occur more than once every 6 sec."

Heal from critical hit doesn't work

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020010.
