### ISSUE TITLE
Druid - Spell - Swiftmend

### ISSUE THREAD

**Issue by Kwyzard** [HellscreamWoW/Tracker#1345]
http://www.wowhead.com/spell=18562/swiftmend
"Instantly heals a friendly target that has an active Rejuvenation or Regrowth effect for (350% of Spell power)."

This spell consume the Rejuvenation or Regrowth effect and he shouldn't, except with the talent Rampant Growth 
http://www.wowhead.com/spell=155834/rampant-growth

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020010.
