### ISSUE TITLE
Quest: Hero's Call: Westfall

### ISSUE THREAD

**Issue by omigawail** [HellscreamWoW/Tracker#1358]
The quest: http://www.wowhead.com/quest=26378/heros-call-westfall
Objectives:
* Hand-in the quest by talking to Lieutenant Horatio Laine
Issues: The NPC doesn't spawn, making the bread-crumb quest uncompletable.

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/1277
https://github.com/HellscreamWoW/Tracker/issues/1015
https://github.com/HellscreamWoW/Tracker/issues/931
https://github.com/HellscreamWoW/Tracker/issues/482
https://github.com/HellscreamWoW/Tracker/issues/871

**Comment by HellscreamWoW** [comment]
ref #2235
