### ISSUE TITLE
Spells not generating burning ember

### ISSUE THREAD

**Issue by Burag** [HellscreamWoW/Tracker#1363]
I just got lvl 10 and I choose destro as a spec. If I logged in automatically its generating one burning ember but after none of my spell did. Pls fix it as soon as possible.
Thanks for the great work! I found out an other bug with burning ember. I logged in I watied to generate one ember in automatically but unfortunatelly I could spend that one. I can not use my Chaos Bolt.

**Comment by GMTyrial** [comment]
I have personally tested burning embers and chaos bolt, both are working
