### ISSUE TITLE
Fiona

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1380]
http://www.wowhead.com/npc=45417/fiona

This NPC seems to be missing/not phased in. At the very least the left most spawn of hers is not spawned in.

**Comment by Malae1** [comment]
Have you tried turning any quests in to her at her most earliest point upon entering eastern plaguelands?

**Comment by GeneralCaveman** [comment]
Yes, I had 1-2 quests that ended with her. It was how I knew she was not there.

**Comment by Malae1** [comment]
Fixed in next update
