### ISSUE TITLE
Quest Bug:Archmage Evanor

### ISSUE THREAD

**Issue by vation1234** [HellscreamWoW/Tracker#1384]
http://www.wowhead.com/quest=11681/rescuing-evanor

No man has empty
http://www.wowhead.com/npc=25785/archmage-evanor
 
[img]http://i.imgur.com/XCYKGIU.jpg?1[/img]

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/963

**Comment by vation1234** [comment]
okay

**Comment by HellscreamWoW** [comment]
ref #2235
