### ISSUE TITLE
Lieutenant Horatio Laine missing.

### ISSUE THREAD

**Issue by zekara922** [HellscreamWoW/Tracker#1397]
Lieutenant Horatio Laine missing in Westfall.

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/1277
https://github.com/HellscreamWoW/Tracker/issues/1015
https://github.com/HellscreamWoW/Tracker/issues/931
https://github.com/HellscreamWoW/Tracker/issues/482
https://github.com/HellscreamWoW/Tracker/issues/871

**Comment by HellscreamWoW** [comment]
ref #2235
