### ISSUE TITLE
Mage Spell: Arcane Brilliance

### ISSUE THREAD

**Issue by Odysseas68** [HellscreamWoW/Tracker#1398]
Mage buff spell [Arcane Brilliance] http://www.wowhead.com/spell=1459/arcane-brilliance (when you are in no group, only with your pet) buff only the mage. It should buff and the mage pet too at the same time.

**Comment by Vynrae** [comment]
Also does not increase spell power by 10%, but only crit strike chance.

**Comment by Odysseas68** [comment]
After the fix of the spell the buff also buff all npc's and mob's (hostiles and not) in a large area.

**Comment by Odysseas68** [comment]
After i cast [Arcane Brilliance](http://www.wowhead.com/spell=1459/arcane-brilliance) in a major city (e.g. Stormwind) my PvP flag goes on.

**Comment by Odysseas68** [comment]
It is fixed
