### ISSUE TITLE
[QUEST - Arathi Highlands - "Wanted: Marez Cowl"] Missing NPC

### ISSUE THREAD

**Issue by strangefolk1** [HellscreamWoW/Tracker#1400]
Marez Cowl does not spawn in the target location.

**Comment by Lorelai-Hellscream** [comment]
The spawn time might be very long on her, but I completed this quest a few days ago and can confirm that she was there and I killed her for the Horde Quest: Foul Magics (http://wowwiki.wikia.com/Quest:Foul_Magics_(2))
