### ISSUE TITLE
Heirloom Hoarder

### ISSUE THREAD

**Issue by twoinchknife** [HellscreamWoW/Tracker#1406]
The achievement Heirloom Hoarder does not give the chopper mount mount as reward. The reward is based on the faction of the character that achieve the achievement.
http://www.wowhead.com/achievement=9909/heirloom-hoarder<--Achievement
http://www.wowhead.com/item=120968/chauffeured-chopper<--Horde reward
http://www.wowhead.com/item=122703/chauffeured-chopper<-- Alliance reward

**Comment by Malae1** [comment]
Thanks for info, I have confirmed this to be the case.

**Comment by Malae1** [comment]
Fixed in coming update.
