### ISSUE TITLE
Difficulty changing for raids and dungeons

### ISSUE THREAD

**Issue by skorge1** [HellscreamWoW/Tracker#1418]
There are no options to change the difficulty of raids and dungeons which means you can do heroic for dungeons and you can't do heroic and mythic for raids.

**Comment by Malae1** [comment]
There are options to do this, need more information.

**Comment by skorge1** [comment]
For example raids : you can't change difficulty to 10 normal / 10 heroic / 25 normal / 25 heroic.
For example dungeons: you can't change difficulty to heroic.
This is for instance options.
