### ISSUE TITLE
Golden Eagle

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1439]
http://www.wowhead.com/npc=44628/golden-eagle

These guys have the common flying glitch of being on the ground and targetable but attacking gives you a messaging saying it is too far away.

![wowscrnshot_072315_075100](https://cloud.githubusercontent.com/assets/12555606/8849677/97ba883a-310f-11e5-8049-daba9854a94b.jpg)

**Comment by Malae1** [comment]
Fixed in next update
