### ISSUE TITLE
herb Gathering

### ISSUE THREAD

**Issue by vation1234** [HellscreamWoW/Tracker#1448]
http://www.wowhead.com/spell=2366/herb-gathering
SKILL NOT HIGH ENOUGH
Pls fix,     thanks
[img]http://i.imgur.com/a4IGqur.jpg[/img]

**Comment by Malae1** [comment]
You've opened this issue before and it is still active, Do not open multiple issues on the same topic. Use the search feature. Ref #1409, #1330, #930, #469, #442, #292

**Comment by vation1234** [comment]
ok thanks
