### ISSUE TITLE
Paladin : Consecration Ability

### ISSUE THREAD

**Issue by topher8667** [HellscreamWoW/Tracker#1449]
Whenever I kill an enemy with the Consecration ability it does not let me loot that enemy. It acts like when a pet kills an enemy and the player does no damage the enemy becomes unlootable. I tried this on over 20 enemies and none were lootable. but when I didn't use that ability  every one was.

**Comment by topher8667** [comment]
Also found that it does not give me xp or count the kill towards questing. Example if I need to kile 5 enemies and I use Consecration the kills do not count.

**Comment by EPS1L0N** [comment]
ref #2266

**Comment by HellscreamWoW** [comment]
http://hellscream-wow.com/log#2015.1.09.020004
