### ISSUE TITLE
Shaman Spell bug: Healing Tide Totem.

### ISSUE THREAD

**Issue by skorge1** [HellscreamWoW/Tracker#1467]
The issue with http://www.wowhead.com/spell=108280/healing-tide-totem is that it doesn't heal the shaman or the party members.

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020006.

**Comment by Kilrathe** [comment]
I am also having problems with my healing stream totem not healing anyone including my shaman. Can you look into this please?

**Comment by EPS1L0N** [comment]
@Kilrathe this is a report regarding Healing Tide Totem, not Healing Stream Totem. the reports regarding Healing Stream Totem can be found here: #2645, #2377
