### ISSUE TITLE
Druid Spell Issue

### ISSUE THREAD

**Issue by narik89** [HellscreamWoW/Tracker#1490]
Hello,

Druid spell entangle does not go when i attack the creep with any other spell till death. I have seen that the creep is entangled only till i hit with another spell. Could you please let me know if this is a issue or it is like % chance that the entangle is debuffed?

I played feral spec. I just now saw this issue with my character. Is it only with my character or all druids?

IGN: Druider.

Thanks

**Comment by DeathQueen** [comment]
Hello,
Actually the enangle is never removed , with any spell or long rage attack

**Comment by narik89** [comment]
Hello,

I believe that a mob is entangled until we hit or place another spell over it. But now it stay there for ever. I would think it as a issue.

Regards
Druider

**Comment by EPS1L0N** [comment]
ref #2266
