### ISSUE TITLE
Problem with both my primary professions !!

### ISSUE THREAD

**Issue by plainjanex** [HellscreamWoW/Tracker#1491]
#442 
I can't increase my profession skills anymore, my enchanting is on 301 & my tailoring is on 360. The only recipes listed for me to train in are too high level & I noticed that before I reach a certain level in the profession I can see the recipe and then as soon as I reach the level to train in that recipe it disappears from the list. For example with tailoring, when it was before 360 I could see the option to train in bolt of frostweave but as soon as I reached 360 then it disappeared & now I can't do anything to increase my skill, same with enchanting.

![wowscrnshot_072615_170801](https://cloud.githubusercontent.com/assets/13061895/8894508/4225fa06-33b9-11e5-8597-bac8d8ce3753.jpg)
![wowscrnshot_072615_170851](https://cloud.githubusercontent.com/assets/13061895/8894509/44a3f7a6-33b9-11e5-827d-fd28ea415fcc.jpg)

**Comment by plainjanex** [comment]
![wowscrnshot_072615_170801](https://cloud.githubusercontent.com/assets/13061895/8894499/19ee3f08-33b9-11e5-8c62-dde24e5533a0.jpg)
![Uploading WoWScrnShot_072615_170851.jpg…]()

**Comment by Malae1** [comment]
Looking in to this now.

**Comment by plainjanex** [comment]
I'm very sure, the same thing also happened with my flying training as well, someone had to add them for me and now I still can't learn cold weather flying. I deleted my cache and tried relogging so  many times but the options still don't pop up.

**Comment by Malae1** [comment]
Something may be wrong with your character. We can take a look at it when we get some time available.

**Comment by plainjanex** [comment]
Would it be possible for me to ask when that might be ? And thank you.

**Comment by Malae1** [comment]
Since your issue is very isolated from the other profession issues, it may be easier to unlearn and then reteach them to you. This poses a problem, we do not know if anyone else has this happening to them, we would like to be certain that when we fix this it would be for all players and not one at a time. Can't offer an ETA as of now, however, we will get your character data to see if there is anything out of the ordinary.

**Comment by plainjanex** [comment]
I've asked around and no one else that I've asked is having issues with this. This is happening with all my professions and skills that you get from a trainer.

**Comment by Malae1** [comment]
Which professions if it's not the only two above?

**Comment by plainjanex** [comment]
It's my tailoring,enchanting, cooking, first aid & flying that's doing all of this.

**Comment by Malae1** [comment]
Thanks for all the info. We've gathered your data, and we'll take a look at it when we get a few moments to spare.

**Comment by plainjanex** [comment]
Thank you so much, I would love to get back to levelling my professions & learning my flying. Thank you.

**Comment by Malae1** [comment]
We've looked over the data as much as we could but could not find any error on the character itself. We've also checked these trainers and wasn't able to find a bug with them.  If you would be so kind to send me a pm on the forums and we can further look in to this more.

**Comment by Malae1** [comment]
Resolved - The profession purchasing new spells tab needs the "Available" option checked.
