### ISSUE TITLE
Repeatable Quests in Zangarmarsh

### ISSUE THREAD

**Issue by Odysseas68** [HellscreamWoW/Tracker#1492]
NPC: Fahssn (faction: Sporeggar) http://www.wowhead.com/npc=17923/fahssn

Gives some quest's that works ok. After you deliver the quests, he have 2 repeatable quests, with blue"?", that don't work. You need these quests to gain rep (to Neutral) for the faction Sporeggar to continue the quests there. These quests are:

More Spore Sacs http://www.wowhead.com/quest=9742/more-spore-sacs
More Tendrils!    http://www.wowhead.com/quest=9744/more-tendrils

The reason they don't work is that you don't have them in your Quest Log and by resault the quests items wont drop.

**Comment by Tregeta** [comment]
Fixed drop rate in next update
