### ISSUE TITLE
Link to #241, reopen issue plz

### ISSUE THREAD

**Issue by jfdaigle** [HellscreamWoW/Tracker#1497]
Reloque commented on Jun 2

There have been updates since this issue was closed, but Kadrak(8582) is still missing or phased out.

He plays a major part in Ashenvale's Horde quests, here are the quests which you cannot (shouldn't be able to) complete without him:

Independent quest
Mor'shan Defense(13612)

Breadcrumbs
Warchief's Command: Ashenvale!(28493)
To the Mor'shan Rampart(28876)
Mor'shan Caravan Delivery(29111)
To The Ramparts!(28876)

Gorat Questline
Find Gorat!(13618)
Final Report(13619)
To Dinah, at Once!(13620)
Gorat's Vengeance(13621)

Corrupt the Forest Heart Questline
Got Wood?(13628)
Management Material(13640)
Needs a Little Lubrication(13651)
Crisis at Splintertree(13653)
To the Rescue!(13712)
Blood of the Weak(13803)
Pierce Their Heart(13805)

Note that his Splintertree Post counterpart, Kadrak(33837) is also missing or phased out, which disables the following quests:

Corrupt the Forest Heart Questline
To the Rescue!(13712)
Blood of the Weak(13803)
Pierce Their Heart(13805)

Liberate the Blood Elf Diplomat Questline
Mission Improbable(13808)
Making Stumps(13815)

Transition to Zoram Strand quest
Bad News Bear-er(13848)

**Comment by Malae1** [comment]
Having a multitude of issues in a single post leaves it very difficult to close it as we make progress with each quest. We would ask if at all possible you can separate the issues so we can fix them as they become available.
