### ISSUE TITLE
Corin's Crossing double spawns

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1499]
http://www.wowhead.com/npc=8541/hate-shrieker
http://www.wowhead.com/npc=8543/stitched-horror
http://www.wowhead.com/npc=8526/dark-caster

There might be more as it looks like all the seperate mobs in this area share spawn points.

![wowscrnshot_072615_220315](https://cloud.githubusercontent.com/assets/12555606/8897366/2421be36-33e2-11e5-9393-a5cfe4fce30a.jpg)

**Comment by Malae1** [comment]
This is one dangerous area on retail, adjusted it a bit, it feels a little safer, but without demolishing the retail-like feel the only thing left to do is space them out or set as sequence spawning. For now it can be resolved until we properly script the entire zone.
