### ISSUE TITLE
Coyote multiple spawns

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1507]
http://www.wowhead.com/npc=834/coyote

![wowscrnshot_072615_230951](https://cloud.githubusercontent.com/assets/12555606/8897943/6ce1ffc4-33eb-11e5-82d9-5151462b88b5.jpg)

The other side of the field feels a little empty but I don't know if it is intended.

I am not 100% sure on how the field is supposed to be so I could be wrong with the spawns. It is harder to tell with the mobs moving around.

**Comment by Malae1** [comment]
It's pretty close to retail now, may need some additional spawns added to a small portion of it, which can be handled when we script this zone fully.
