### ISSUE TITLE
Lower level mobs

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1542]
http://wow.gamepedia.com/Patch_6.0.2#Stat_squish

When attacking lower level mobs (from previous expansions), the player is supposed to get increased damage to the creatures while taking reduced damage from them.

My level 90 DK got her ass handed to her by 4 mobs in Hellfire Ramparts so I don't think this has been implemented.

**Comment by Malae1** [comment]
Ref #926

**Comment by GeneralCaveman** [comment]
There it is. I couldn't find the issue report on it.
