### ISSUE TITLE
Quest "The Pursuit of Umbranse" quest NPC doesn't spawn

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1561]
The quest NPC Haleh isn't spawned at the required location.

**Comment by Guybrush-Hellscream** [comment]
Confirmed, here is a screenshot : 
![wowscrnshot_090115_123252](https://cloud.githubusercontent.com/assets/13908354/9604253/a98f5358-50b6-11e5-96ca-cabdc2758a30.jpg)

**Comment by Malae1** [comment]
Ref #2235
