### ISSUE TITLE
Quest "A Traitor Among Us" quest item bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1573]
The chest containing the required quest item cannot be selected and used, preventing quest completion.

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/707

Make sure to search if any bug was already reported or not and include a wowhead link whenever possible. It makes it slightly easier for the developers to not sort through duplicates and have information about the quest on hand.

**Comment by Guybrush-Hellscream** [comment]
Definitely working now.
