### ISSUE TITLE
Quest "Report to the Allerian Post" quest NPC spawn bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1585]
http://www.wowhead.com/quest=10444/report-to-the-allerian-post

The quest NPC Jenai Starwhisper isn't spawned at the Allerian Post, along with an additional NPC, breaking both the quest and a quest series.

**Comment by silverjade** [comment]
The NPC's for this location & the quest are now present. This quest can now be completed.

**Comment by Malae1** [comment]
Ref #2235
