### ISSUE TITLE
Quest "Unruly Neighbors" quest NPC spawn bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1586]
http://www.wowhead.com/quest=9998/unruly-neighbors

Quest NPC Theloria Shadecloak isn't spawned at the Allerian Post, preventing quest completion.

**Comment by manic17** [comment]
Confirmed npc still missing as of date of post

**Comment by silverjade** [comment]
The NPC is now present.

**Comment by Malae1** [comment]
Ref #2235
