### ISSUE TITLE
Quest "Grmmurggll Mrllggrl Glrggl!!!" mob spawn bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1595]
http://www.wowhead.com/quest=11563/grmmurggll-mrllggrl-glrggl

The quest mob Glrggl doesn't spawn, preventing quest completion.

**Comment by Guybrush-Hellscream** [comment]
He is spawned ATM.
![wowscrnshot_090715_221919](https://cloud.githubusercontent.com/assets/13908354/9722495/8b57c792-55ae-11e5-87d1-d33fd52391a8.jpg)

**Comment by Dushku** [comment]
This can be removed from the tracker. He was spawned for me also, and I was able to complete the quest. The "issue" is that his spawn location and where the map is highlighted to find him are not in agreement. This is an issue with Blizzard's files. The only aspect of it associated with Hellscream is the more general issue of mobs not patrolling.
