### ISSUE TITLE
Quest "Stunning Defeat at the Ring" quest mob spawn bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1597]
http://www.wowhead.com/quest=11300/stunning-defeat-at-the-ring

Required quest mobs aren't spawning at the arena.

**Comment by Dushku** [comment]
I believe this can be removed from the tracker as it appears to have been fixed. The first mob was already spawned. Killing him spawned the next one and so on. Final mob also dropped the Ancient Cipher object, which was lootable http://www.wowhead.com/item=33545/ancient-cipher and completed the quest.

**Comment by Malae1** [comment]
Ref #2235

**Comment by ATalisan** [comment]
This doesn't seem to be working for me.
