### ISSUE TITLE
Bankers in Silvermoon

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1600]
http://wow.gamepedia.com/Bank_of_Silvermoon

All of the bankers in Silvermoon currently only open up a dialogue box with no option to actually access your bank.

**Comment by Lorelai-Hellscream** [comment]
Specifically, it's in the bank off of the Bazaar.

**Comment by Guybrush-Hellscream** [comment]
Fixed in next update. :palm_tree:
