### ISSUE TITLE
Paladin's Blessing of Kings buff bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1621]
The buff Blessing of Kings cannot be cast on friendly targets outside a group.

EDIT: The buff cannot be cast on lower level players either, even grouped with the paladin.

**Comment by Malae1** [comment]
More specifically this can be cast on any level.

**Comment by tribaljet** [comment]
This remains an issue still.

**Comment by EPS1L0N** [comment]
cause the realm hasn't been updated

**Comment by EPS1L0N** [comment]
#2266
