### ISSUE TITLE
Quest "The Mender's Stead"NPC Spawn bug

### ISSUE THREAD

**Issue by Fenderr** [HellscreamWoW/Tracker#1676]
As the title says there is bug with NPCspawn  http://www.wowhead.com/npc=44454/field-agent-kaartish
There is link of the quest also.
http://www.wowhead.com/quest=26952/the-menders-stead

**Comment by Malae1** [comment]
Can you explain the spawn bug in detail? what is wrong with it? Is it missing? double spawned?

**Comment by Fenderr** [comment]
He is missing Malae

**Comment by HellscreamWoW** [comment]
ref #2235
