### ISSUE TITLE
Paladin Spell - Hand of Protection

### ISSUE THREAD

**Issue by geeorgee** [HellscreamWoW/Tracker#1684]
Hey guys!

Spell Hand of Protection (http://www.wowhead.com/spell=1022/hand-of-protection).It says that i can´t attack or use a physical ability.... But actually i can..

**Comment by Luminescent-Hellscream** [comment]
Issue no longer present ingame 

[Screen with hand of protection up and attempting to use judgement](http://i.imgur.com/HYqfjFF.jpg)
