### ISSUE TITLE
Quest "Sea Legs" NPC spawn bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1694]
http://www.wowhead.com/quest=24432/sea-legs

The quest NPC Erunak Stonespeaker isn't spawned at the required location, preventing questing in the zona due to the lack of underwater breathing and movement speed buffs.

**Comment by Trekex** [comment]
The NPC has now spawned!
But it does not cast the spell on you even if you complete the quest :( So Vashj'Ir is still un-doable

**Comment by Malae1** [comment]
Ref #2235

**Comment by tribaljet** [comment]
Update on the quest: The NPC is indeed now spawned but despite changelog indication of the Sea Legs quest being completable and the respective Sea Legs buff being applied, the quest can be completed but the buff isn't given.

**Comment by Dushku** [comment]
I can confirm that upon completion, NPC goes through animation of applying buff, but buff does not display or appear active. HOWEVER, I've just arrived back in Vash for the purpose of checking out candy buckets. Despite showing no buff, my character does not suffer from breathing and moves in the water at an accelerated speed, moreso while "running" along the ground, just as in retail.
