### ISSUE TITLE
Missing professions/spells

### ISSUE THREAD

**Issue by sablast** [HellscreamWoW/Tracker#1749]
After last big patch 2015.24.07 i lost my Fishing spell, cant train at trainer because say i have it an i need to lvl up to 50 skill, problem is that there is not fishing spell in my spell book and i cant use fishing rod. Also i lost call companion spell so i cant use battle pets. I got some pets but all are locked in Battle Pet tab and cant use any of them.
Fishing on new character  works fine but i need it on my lvl 90 char. can u please fix that and Battle Pet for my character in game name DUDU.
Thanks and sorry for bad english.

**Comment by Malae1** [comment]
The call companion spell you are refering to, can you provide a wowhead link to it? Battle pets are not fully enabled, however, you should be able to summon them.

**Comment by sablast** [comment]
Well call companion is now same as battle pets, sorry for misunderstood (my bad english). Problem is that i don't have spell Battle Pet Training http://www.wowhead.com/spell=119467 and Fishing http://www.wowhead.com/skill=356 in my spell book and i cant learn them again because i learned them before patch.

**Comment by Malae1** [comment]
Thanks for the info, we will see if we can restore these to you the next time you are available.
