### ISSUE TITLE
Death Knight currently known bugs

### ISSUE THREAD

**Issue by avandarkwalker** [HellscreamWoW/Tracker#1753]
I.General DK bugs
1. Death Rune doesn't seems to work at all. It is vital and essential for a DK to have Death Runes, because it would affect alot to our rotations and abilities. 
http://www.wowhead.com/spell=54637/blood-of-the-north 
http://www.wowhead.com/spell=56835/reaping
these seem to be the problem, because they doesn't exist in the spellbook.
2.Plague Leech is alsow a bug talent. It doesn't consume diseases and refresh any runes.http://www.wowhead.com/spell=123693/plague-leech
The proc for Howling Blast is proc by any kind of action or attack made by Frost DK.
3.Starting zone and quests are under heavy bugs, which lead to unable to do starting quests for DKs
4.Runeforging is not working at all http://www.wowhead.com/spell=123693/plague-leech
5.Anti Magic Shell (AMS) http://www.wowhead.com/spell=53766/anti-magic-shell : does not give the full runic power base on the absorbtion but only give 1 runic power.
6.http://www.wowhead.com/spell=119975/conversion Conversion doesn't give heal at all as it's supposed to and after awhile will auto turn off eventhough there are plenty runic power left.
7.http://www.wowhead.com/spell=48743/death-pact Death Pact only give 25% max HP heal and doesn't add the absorbtion.
9.Death and Decay http://www.wowhead.com/spell=43265/death-and-decay doesn't deal any damge at all. The animation works fine.
II.UH bugs
Unholy pet bug.http://www.wowhead.com/spell=79905/raise-dead This spell doesn't summon a ghoul as a pet for UH dk and I guess there's no pet bar for it too.
III.Frost bugs
The proc for Howling Blast is proc by any kind of action or attack made by Frost DK.
Howling Blast www.wowhead.com/spell=49184/howling-blast :does not spread Frost disease to others target except the main target.
IV. Blood bugs
Blood Boil http://www.wowhead.com/spell=50842/blood-boil, doesn't spread diseases between targets that got hit by it.  Also the stack are not consumed after using Death Strike.

**Comment by avandarkwalker** [comment]
One more update about DK bugs :( 
T4 talents doesn't seems to work at all. 3 of them actually. That include 
Blood Tap http://www.wowhead.com/spell=45529/blood-tap
Runic Empowerment http://www.wowhead.com/spell=81229/runic-empowerment
Runic Corruption http://www.wowhead.com/spell=51462/runic-corruption

**Comment by avandarkwalker** [comment]
1 more big bug for Frost DK or not...
http://www.wowhead.com/spell=81333/might-of-the-frozen-wastes MoTFW function normally with 2H but doesn't give the Frost Strike http://www.wowhead.com/spell=49143/frost-strike 100% increase damge like in description
My normal damge base on AP is 529-588 so it will be 558,5 and my Frost Strike's damge is 538. So shouldn't it be higher if u count the 100% from MoTFW in ?? The rest works fine with MoTFW makes you attack with both wps, the only bug i've found is this.

**Comment by avandarkwalker** [comment]
http://www.wowhead.com/spell=119975/conversion Conversion doesn't give heal at all as it's supposed to and after awhile will auto turn off eventhough there are plenty runic power left.
http://www.wowhead.com/spell=48743/death-pact Death Pact only give 25% max HP heal and doesn't add the absorbtion.

**Comment by avandarkwalker** [comment]
Death and Decay http://www.wowhead.com/spell=43265/death-and-decay doesn't deal any damge at all. The animation works fine.

**Comment by Malae1** [comment]
For future reference, having each individual issue allows us to close the issue once that quest has been dealt with. Instead, through this method, this will require us to go in manually removing it from the list you have provided, taking more time. If you are willing, in the future, please separate each issue for us to better handle. Thanks

**Comment by KwitUrBichn** [comment]
I want to thank you for taking the time to go back and making individual issues. Your information is very helpful. Please keep posting!

I have referenced all below and will close this one.

[Death Rune] https://github.com/HellscreamWoW/Tracker/issues/1967
[Plague Leech] https://github.com/HellscreamWoW/Tracker/issues/1953
Starting zone and quests for DKs: http://www.hellscream-wow.com/forum/viewtopic.php?f=27&t=3367&p=20131&hilit=starter+zone+for+DK#p20131
[Runeforging] https://github.com/HellscreamWoW/Tracker/issues/818, https://github.com/HellscreamWoW/Tracker/issues/1955, https://github.com/HellscreamWoW/Tracker/issues/2639
[Anti Magic Shell] https://github.com/HellscreamWoW/Tracker/issues/1956
[Conversion] https://github.com/HellscreamWoW/Tracker/issues/1957
[Death Pact] https://github.com/HellscreamWoW/Tracker/issues/1958
[Death and Decay] https://github.com/HellscreamWoW/Tracker/issues/691, https://github.com/HellscreamWoW/Tracker/issues/1959
[Raise Dead] https://github.com/HellscreamWoW/Tracker/issues/393, https://github.com/HellscreamWoW/Tracker/issues/1960. https://github.com/HellscreamWoW/Tracker/issues/2813
[Howling Blast] https://github.com/HellscreamWoW/Tracker/issues/1287, https://github.com/HellscreamWoW/Tracker/issues/1954
[Blood Boil] https://github.com/HellscreamWoW/Tracker/issues/544, https://github.com/HellscreamWoW/Tracker/issues/1961, https://github.com/HellscreamWoW/Tracker/issues/2795
Tier 4 talents: [Blood Tap], [Runic Empowerment] & [Runic Corruption] https://github.com/HellscreamWoW/Tracker/issues/1962
[Asphyxiate] https://github.com/HellscreamWoW/Tracker/issues/1963
Rune regeneration issue - https://github.com/HellscreamWoW/Tracker/issues/1965
[Anti Magic Shell] https://github.com/HellscreamWoW/Tracker/issues/1956
[Might of the Frozen Wastes] https://github.com/HellscreamWoW/Tracker/issues/1966
