### ISSUE TITLE
Warlock Pets

### ISSUE THREAD

**Issue by Alexhandr** [HellscreamWoW/Tracker#1756]
Warlock Pet (imp) fails to attack or follow any orders.

**Comment by Malae1** [comment]
What level are you?

**Comment by Alexhandr** [comment]
3 


     On Friday, August 7, 2015 4:27 PM, Malae1 <notifications@github.com> wrote:
   

 What level are you?—

**Comment by Malae1** [comment]
Thanks for the info.

**Comment by EPS1L0N** [comment]
ref #2266
