### ISSUE TITLE
Tempered Flywheel/Glassweb Venom drop rate

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1758]
http://www.wowhead.com/item=62805/tempered-flywheel
http://www.wowhead.com/quest=27956/lunks-task

The drop rate for these guys for the above quest seem to be either non existent, not correctly triggered or extremely low.

Edit:
http://www.wowhead.com/item=62809/glassweb-venom
http://www.wowhead.com/quest=27958/a-proper-antivenom

The same seems to go for this venom.

**Comment by Guybrush-Hellscream** [comment]
Fixed :palm_tree: (both of them).
