### ISSUE TITLE
(QUEST) An Introduction Is In Order

### ISSUE THREAD

**Issue by jfdaigle** [HellscreamWoW/Tracker#1764]
NPC (Khan Leh'Prah) you need to talk to is missing.

http://www.wowhead.com/quest=14312/an-introduction-is-in-order#videos

**Comment by HellscreamWoW** [comment]
ref #2235

**Comment by zwei7** [comment]
I don't see this npc.

**Comment by Malae1** [comment]
NPC is phased

**Comment by zwei7** [comment]
Phased, what does that mean? Cloaked?

**Comment by Malae1** [comment]
It means it needs scripted to set it to see properly.

**Comment by Malae1** [comment]
Fixed in update
