### ISSUE TITLE
Buffs not showing up on screen!!

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#177]
Whenever a buff like poison or transformation is casted on you by mob or npc, it doesn't display on the screen its duration, here's me on retail buffed by npc that transformed me into frog :D and then it displayed that buff on the screen showing its duration while its active on my character: http://store.picbg.net/pubpic/BE/1A/d4a43d4cb1a4be1a.jpg

**Comment by EPS1L0N** [comment]
pretty sure its just an interface option
