### ISSUE TITLE
Severed Druid/Rotting Slime Spawn density

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1770]
http://www.wowhead.com/npc=3799/severed-druid
http://www.wowhead.com/npc=3928/rotting-slime

![wowscrnshot_080715_235736](https://cloud.githubusercontent.com/assets/12555606/9148952/16110fcc-3d60-11e5-84b2-84c6334bbb7b.jpg)

I am not sure if there are double spawns but the spawn density of these guys seems too high. I played this on retail not too long ago and it didn't feel this packed.

**Comment by Malae1** [comment]
Area feels a bit safer now. Might add that since it was on retail perhaps there was also someone in that area also doing the quest before you.
