### ISSUE TITLE
Mind Blast orb generation

### ISSUE THREAD

**Issue by pouzivatel123** [HellscreamWoW/Tracker#1783]
Hello,

Mind Blast spell is generating 3 shadow orbs instead of one.

**Comment by EPS1L0N** [comment]
ref #2266

**Comment by rist9** [comment]
Now there is a visual bug that will show me gaining 2 shadow orbs, yet I gain one, but once i reach 3 it shows as if i can do the devouring plague spell, but i actually can't. I guess its something to learn to actually take into account, but still, its annoying.

**Comment by EPS1L0N** [comment]
@rist9 can you confirm this still happens after the fixes done today?

**Comment by Malae1** [comment]
Confirmed still doing it.
