### ISSUE TITLE
[Quest]:Protect The Frontier

### ISSUE THREAD

**Issue by Christatik** [HellscreamWoW/Tracker#1788]
The Prowlers and Bears that you need to kill in order to complete the quest don't add to the counter no matter how many you kill

**Comment by Malae1** [comment]
Could not reproduce. Did you happen to relog during this progress at all?

**Comment by Christatik** [comment]
i don't thnk i did , i'll pick it up again next time i log in and let you
know if it works

2015-08-08 18:05 GMT+03:00 Malae1 <notifications@github.com>:
