### ISSUE TITLE
Quest: Teldrassil: Passing Awareness

### ISSUE THREAD

**Issue by FlameChampion34** [HellscreamWoW/Tracker#18]
When you accept this quest "Teldrassil: Passing Awareness" it doesn't give a buff, it's supposed to give a buff called "Wind's Embrace" which should slow your fall speed for 2 minutes, it makes it a lot easier to jump from that high. :D

Quest Link: 

http://www.wowhead.com/quest=28731

Wind's Embrace link:

http://www.wowhead.com/spell=65453

**Comment by Max-Hellscream** [comment]
Fixed.
