### ISSUE TITLE
Shaman Spell bug: Glyph of Lightning Shield

### ISSUE THREAD

**Issue by skorge1** [HellscreamWoW/Tracker#1800]
The issue with http://www.wowhead.com/spell=101052/glyph-of-lightning-shield is that the effect cannot be triggered because the lightning shield is removed after 1 hit. After you are hit when lightning shield is active you should get a 10% damage reduction but this doesn't happen.

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020006.
