### ISSUE TITLE
Shaman Spell bug: Mastery: Molten Earth

### ISSUE THREAD

**Issue by skorge1** [HellscreamWoW/Tracker#1858]
The issue with http://www.wowhead.com/spell=170374/mastery-molten-earth is that when you do a damaging spell the molten earth spikes do not come out of the ground to attack the target.

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020005.

**Comment by omnira** [comment]
still dont work

**Comment by Malae1** [comment]
Explain how it still does not work?

**Comment by omnira** [comment]
I am 84 and i still dont see any molten earth spikes or dmg from it...
