### ISSUE TITLE
NPC "Elder Anli" spawn bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1880]
http://www.wowhead.com/npc=58564/elder-anli

NPC Elder Anli isn't spawned at the required location, The Arboretum in Jade Forest, preventing turning in multiple quests.

**Comment by KwitUrBichn** [comment]
https://github.com/HellscreamWoW/Tracker/issues/3728

**Comment by Malae1** [comment]
Fixed in next update
