### ISSUE TITLE
Ghostlands Quests: Spinal Dust

### ISSUE THREAD

**Issue by Gantian2** [HellscreamWoW/Tracker#1890]
Mobs do not drop Spinal Dust at all.

**Comment by bennnery** [comment]
Spinal Dust
http://www.wowhead.com/quest=9218/spinal-dust
 quest does work I just completed it.
Need to kill
 Deathcage Sorcerer
Dreadbone Sentinels

I got about 4 really fast then about 6 kills later I got more took less then 10 mins to finish the quest.

**Comment by HellscreamWoW** [comment]
ref #2235
