### ISSUE TITLE
NPC: Stephanos

### ISSUE THREAD

**Issue by FlameChampion34** [HellscreamWoW/Tracker#19]
The issue with this npc is that, he is in the wrong place, his new location is supposed to be inside Exodar. Instead he is on the old location from previous expansion right now.

Screenshot from in-game location for easy find: 

http://store.picbg.net/pubpic/FD/1A/2b1e2d673941fd1a.jpg

Wowhead link, it shows where his new location should be: 

http://www.wowhead.com/npc=17555/stephanos

**Comment by Max-Hellscream** [comment]
Will be fixed in next update.
