### ISSUE TITLE
Problems at the auction house

### ISSUE THREAD

**Issue by mrjhaker400** [HellscreamWoW/Tracker#1918]
There's some bugs in the auction house:
1.research by name don't work(it can make really hard to find an item in particular)
2.Target only the usable items don't work either(really annoying too)
3.It's not a bug but even if i know that the server put items in the auction house by its own because the lack of player, could he put items of level more than 55 because we still need stuff beyond this level.
Hope it will be fixed soon.

**Comment by Malae1** [comment]
Ref #1285
