### ISSUE TITLE
Soloting old instances and killing low level mobs.

### ISSUE THREAD

**Issue by mrjhaker400** [HellscreamWoW/Tracker#1919]
I don't know if its because you haven't released Draenor yet or anything but one principal thing of this expansion isn't here:
Before WOD the numbers(of armor,HP and damages) weren't reduced so the difference between a lvl 60mob and a lvl 90player allowed him to kill him easily and to solo raids and heroic dungeons.
But now this diferrence is far less important so the Blizzard developpers put something that made that we can still solo raids and all...
This thing is that the more level we got compared to our opponent the more damage we dealt him and that worked well because we are able to solo cataclysm raids.
But on this server its not there so we aren't able to solo a burning crusade hero dungeon or even a vanilla raid and this situation became really annoying because once we reached maximum level what are we supposed to do?
Hope it will be fixed soon.

**Comment by Malae1** [comment]
Ref #926, #1542
