### ISSUE TITLE
* Quest - Axis of Awful

### ISSUE THREAD

**Issue by Tyrelas** [HellscreamWoW/Tracker#1938]
Axis of Awful (http://www.wowhead.com/quest=26868/axis-of-awful) - Objective - Loot two item from Canary's Cache obtained via accepting the quest, and use them as mentioned in objective / Issue - When player opens Canary's Cache, it's empty, none of those two items are there.

**Comment by Guybrush-Hellscream** [comment]
same as https://github.com/HellscreamWoW/Tracker/issues/2148
