### ISSUE TITLE
* Quest - Resuplying the Excavation

### ISSUE THREAD

**Issue by Tyrelas** [HellscreamWoW/Tracker#1940]
Resuplying the Excavation (http://www.wowhead.com/quest=273/resupplying-the-excavation) - Objective - Find dwarves carying a vagon, and complete the quest / Issue - When found, no progress will occur, you still can talk to the key NPC, but the "?" is grey.

**Comment by Guybrush-Hellscream** [comment]
Loch Modan - Quest - Resupplying the Excavation
