### ISSUE TITLE
Quest "The Dark Portal" NPC bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1945]
http://www.wowhead.com/quest=34398/the-dark-portal

Talking with Archmage Khadgar near the Dark Portal in phased Blasted Lands does trigger the cutscene and teleport to Draenor but does not complete the quest.

**Comment by Malae1** [comment]
I believe this issue is resolved now, remove the quest, retake it, and speak with Khadgar, once the cutscene is over speak to him on the other side. Relog after such.
