### ISSUE TITLE
Ashes to Ashes [Western Plaguelands]

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#1949]
The mobs you are supposed to kill, Deathguard War-Captain, is missing from Andorhal. 

More info on quest/ spawn points,
http://www.wowhead.com/quest=27199/ashes-to-ashes

**Comment by silverjade** [comment]
http://www.wowhead.com/npc=44449/deathguard-war-captain

**Comment by GMTyrial** [comment]
Duplicate https://github.com/HellscreamWoW/Tracker/issues/1689
