### ISSUE TITLE
Death Knight Pet bug 

### ISSUE THREAD

**Issue by avandarkwalker** [HellscreamWoW/Tracker#1960]
Unholy pet bug.http://www.wowhead.com/spell=79905/raise-dead This spell doesn't summon a ghoul as a pet for UH dk and I guess there's no pet bar for it too.

**Comment by KwitUrBichn** [comment]
https://github.com/HellscreamWoW/Tracker/issues/393
https://github.com/HellscreamWoW/Tracker/issues/2813
