### ISSUE TITLE
Fuselight-by-the-Sea is a ghost town

### ISSUE THREAD

**Issue by silverjade** [HellscreamWoW/Tracker#1979]
There are no NPCs in Fuselight-by-the-Sea, including a link listing the npcs that should be there.

http://wow.gamepedia.com/Fuselight-by-the-Sea

**Comment by Malae1** [comment]
Eddie Flofizzle - http://www.wowhead.com/npc=46650/eddie-flofizzle
Barkeep Dadams - http://www.wowhead.com/npc=49917/barkeep-dadams
Colt Carbine - http://www.wowhead.com/npc=49920/colt-carbine
The Great Pisani - http://www.wowhead.com/npc=49934/the-great-pisani
Buckslappy - http://www.wowhead.com/npc=49918/buckslappy
Loremaster Bret - http://www.wowhead.com/npc=49919/loremaster-bret
Demolition's Analyst I - http://www.wowhead.com/npc=50511/demolitions-analyst-i
Demolition's Analyst II - http://www.wowhead.com/npc=50512/demolitions-analyst-ii
Exploding Sheep - http://www.wowhead.com/npc=50594/exploding-sheep
Zak Callabang - http://www.wowhead.com/npc=49936/zak-callabang
Boss Mack - http://www.wowhead.com/npc=49932/boss-mack
Max Boomson - http://www.wowhead.com/npc=49926/max-boomson
Kramer - http://www.wowhead.com/npc=49921/kramer
Jeigh Southie - http://www.wowhead.com/npc=49944/jeigh-southie
Joe Mag - http://www.wowhead.com/npc=49924/joe-mag
Johnny shinster - http://www.wowhead.com/npc=49925/johnny-shinster
Nik the Mountain - http://www.wowhead.com/npc=49933/nik-the-mountain
Aleesha Killem - http://www.wowhead.com/npc=49937/aleesha-killem
Dr. Wizzle Doomsday - http://www.wowhead.com/npc=49953/dr-wizzle-doomsday
Jafix - http://www.wowhead.com/npc=49912/jafix
Demolition's Tester (This npc is not in WoWhead's DB for some reason) - http://i.imgur.com/Q3lDxK6.png

**Comment by HellscreamWoW** [comment]
ref #2235
