### ISSUE TITLE
Azuremyst isle buggy mobs

### ISSUE THREAD

**Issue by FlameChampion34** [HellscreamWoW/Tracker#20]
In Azuremyst isle while exploring as level 4 night elf, I encountered mobs that cannot be seen, they attack me while walking on the road to Azure Watch from the docks. I encountered mostly Nightstalker mobs, they are like underground I think and made me think they are invisible, maybe there are other mobs in this zone that are underground or maybe they are invisible. 

http://www.wowhead.com/zone=3524/azuremyst-isle

**Comment by Max-Hellscream** [comment]
This was due to a movement bug. It's since been fixed.
