### ISSUE TITLE
Rogue can't enter Stealth 

### ISSUE THREAD

**Issue by Demonstrike95** [HellscreamWoW/Tracker#2005]
My lvl 19 rogue Silentnight is unable to go into stealth for a time now...
I tried my best to solve the problem through relog, unlearning my specialization etc. although nothing helped.
The forum hasn't solutions either for this...

Hope you can fix the problem soon.

**Comment by Malae1** [comment]
Can you please tell us which talent you have currently?

**Comment by Demonstrike95** [comment]
I changed it yesterday from subtlety to combat if that helps.

**Comment by Malae1** [comment]
That is specialization, your first row of talents, which one did you select?

**Comment by Demonstrike95** [comment]
I selected Subterfuge as my first and only talent

**Comment by Demonstrike95** [comment]
Problem solved... just had to reskill
