### ISSUE TITLE
quest items doesnt drop

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#205]
I have a level 16 shadow priest and now  im on redridge mountain and there are some quest that doesnt drop the material of the quest .. like Yowler Must Die! when you kill him the plans doesnt drop..... i dont know if its scripted but none of the quest that requires material drop none of them drop if you kill the mob .. there are many....

**Comment by MythicBird** [comment]
I don't think it's that the quest item doesn't drop, but moreso that the quest item drop rate is insanely low.

**Comment by Guybrush-Hellscream** [comment]
It's working.
