### ISSUE TITLE
Moonkin Mounting

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#2050]
While in Moonkin form I cannot mount. An error pops up saying, 'You are in Shapeshift form'. Even though I am in shapeshift form I should still be able to mount up as a Moonkin.

Here are a few pics to show that Moonkin's should be able to mount up,
http://wow.zamimg.com/uploads/screenshots/resized/167717.jpg
http://wow.zamimg.com/uploads/screenshots/normal/240086.jpg

**Comment by Guybrush-Hellscream** [comment]
That is quite true since Cataclysm according to patch note!
Patch 4.0.6 (8-Feb-2011): Druids in Moonkin Form should now correctly be able to mount.
http://wowwiki.wikia.com/wiki/Moonkin_Form
