### ISSUE TITLE
Craig Nollward [Cooking Trainer]

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#2061]
This NPC's gossips, Train Me and Let me browse your goods, does not work. 

Info on NPC,
http://www.wowhead.com/npc=4894/craig-nollward#teaches-recipe

**Comment by zwei7** [comment]
Picture of NPC not allowing me to do anything.
![wowscrnshot_111415_213537](https://cloud.githubusercontent.com/assets/15259298/11166864/b026f22a-8b17-11e5-812f-fd647c786976.jpg)
