### ISSUE TITLE
Dun Morogh - Quest - Forced to Watch from Afar

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2075]
Title : Forced to Watch from Afar
Link Wowhead : http://www.wowhead.com/quest=313/forced-to-watch-from-afar

Side : Alliance
Start with : Pilot Stonegear or Captain Tharran
End with : Pilot Stonegear or Captain Tharran

Why it doesn't work : PNJ are where they're supposed to be but when you talk to them, it doesn't work. Mountaineer Dunstan is one of the three PNJ and this is what he is saying.

Screenshot IG :
![wowscrnshot_082215_012001](https://cloud.githubusercontent.com/assets/13908354/9421130/33620536-486e-11e5-8982-848f243d9c45.jpg)

Credits : Tyrelas

**Comment by GoshanTN** [comment]
Can confirm that this quest isn't functioning correctly. The usual speech option doesn't appear in the Mountaineers' chat window.

**Comment by zwei7** [comment]
It works for me. Spoke with all of the 3 dwarves and they deployed all these robots. However I am Drenai and I am not in the correct starting position for my questing (Bloodmist Isles). In addition when the robots are deployed they look really buggy. Also those robots, when not deployed, walk into walls and disappear. Then they come out again.
![wowscrnshot_111815_185357](https://cloud.githubusercontent.com/assets/15259298/11258269/bbf4ef24-8e25-11e5-9494-c4172a1663c8.jpg)
