### ISSUE TITLE
Dun Morogh - NPC - Innkeeper Belm

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2097]
Name : Innkeeper Belm
Link Wowhead : http://www.wowhead.com/npc=1247/innkeeper-belm
 
Side : Alliance
Job : Innkeeper

What's wrong with him : You can't bind your hearthstone (Make this inn your home) nor browse his goods (Let me browse your goods) because those buttons don't work.

Screenshot IG : 
![dun morogh - 2](https://cloud.githubusercontent.com/assets/13908354/9423553/b29dec0c-48c8-11e5-85c2-b588679237f1.PNG)
 
Note : He is selling "Rhapsody Malt" which is needed in a quest named "Beer Basted Boar Ribs". This quest is doable even if you can't get it from this Innkeeper but you need to go to Thelsamar, Loch Modan and buy it from Yanni Stoutheart. So if you fix this NPC, you'll make this quest easier for low level players.

Credits : Tyrelas

**Comment by Guybrush-Hellscream** [comment]
Fixed. :palm_tree:

**Comment by zwei7** [comment]
With ganja?
