### ISSUE TITLE
Death Knight [Death Grip] bug

### ISSUE THREAD

**Issue by avandarkwalker** [HellscreamWoW/Tracker#2104]
http://www.wowhead.com/spell=99123/death-grip 
Death Grip can't be dodge or parried but i've seen some mobs dodged and even parried my Death Grip. Also, sometimes the grip doesn't drag the target right at my DK position but hover it in air then suddenly appears right in front of me or just close to that but still out of melee range. Occasionally, the grip doesn't move the target at all but then have cool down on it.

**Comment by Malae1** [comment]
Ref #119

**Comment by KwitUrBichn** [comment]
https://github.com/HellscreamWoW/Tracker/issues/1922
