### ISSUE TITLE
Loch Modan - NPC - Golden Eagle

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2110]
Name : Golden Eagle
Link Wowhead : http://www.wowhead.com/npc=44628/golden-eagle
 
Side : Alliance

What's wrong : Some eagles are fine (those on moutains) but some can't be attacked (those on the ground). They should fly above our head.

Screenshot IG : 
![wowscrnshot_082215_155244](https://cloud.githubusercontent.com/assets/13908354/9425286/855fe2de-490b-11e5-9e2a-776c7cb1b666.jpg)

Note : Same problem with Cackle in Arathi Highlands (https://github.com/HellscreamWoW/Tracker/issues/2135).

**Comment by Malae1** [comment]
Fixed in next update
