### ISSUE TITLE
Wetlands - NPC - Highland Razormaw

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2124]
Name : Highland Razormaw
Link Wowhead : http://www.wowhead.com/npc=41400/highland-razormaw

What's wrong : When you get close to them, they are not attacking unless you attack them first. Moreover, when they are attacking, they are not standing but on their side.

Screenshot IG : 
![wowscrnshot_082315_120408](https://cloud.githubusercontent.com/assets/13908354/9427800/c039cbf2-498f-11e5-8ec9-45d9308aa3c5.jpg)

Note : Strange thing happened when they respawned after i killed them, i couldn't attack them anymore.

**Comment by Malae1** [comment]
Fixed in next update
