### ISSUE TITLE
Wetlands - NPC - Raptors

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2125]
Name : Unknown
Type : Raptors

What's wrong with them : There is a bunch of raptors (two different colors) who cannot be attacked nor targeted and who attacked you if you come close. Moreover, they are not on their feet but attacking on their side. They are close to Whelgar's Retreat (west of this camp). I counted 4 green and 3 purple (7 total). Purple one might be "Mottled Raptor" (http://www.wowhead.com/npc=41343/mottled-raptor).

Screenshot IG : 
![wowscrnshot_082315_125200](https://cloud.githubusercontent.com/assets/13908354/9427945/d234ad84-4996-11e5-93bb-ad608fd4bded.jpg)
![wowscrnshot_082315_125102](https://cloud.githubusercontent.com/assets/13908354/9427946/d3314210-4996-11e5-9691-84b51ed6879f.jpg)

Note : Same bug as https://github.com/HellscreamWoW/Tracker/issues/2131 with another NPC
Note 2 : When you'll correct this bug, you can close https://github.com/HellscreamWoW/Tracker/issues/1450 and https://github.com/HellscreamWoW/Tracker/issues/604

**Comment by Malae1** [comment]
Fixed in next update
