### ISSUE TITLE
Shadowsworn multiple spawns

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#2127]
http://www.wowhead.com/npc=6004/shadowsworn-ritualist
http://www.wowhead.com/npc=6006/shadowsworn-adept
http://www.wowhead.com/npc=6005/shadowsworn-thug

There are a large group of NPCs right inside the cave, nearly impossible to get through.

**Comment by Malae1** [comment]
cleaned up, the rest are meant to be there.
