### ISSUE TITLE
Arathi Highlands - NPC - Cackle

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2135]
Name : Cackle
Link Wowhead : http://www.wowhead.com/npc=50337/cackle
 
Side : Hostile

What's wrong : He is standing in the water without anyone being able to attack him. He should fly above our head.

Screenshot IG : 
![wowscrnshot_082315_182457](https://cloud.githubusercontent.com/assets/13908354/9429700/2c9afbfa-49da-11e5-98f7-adaa0a3b407f.jpg)

Note : Same problem with the Golden Eagles in Loch Modan (https://github.com/HellscreamWoW/Tracker/issues/2110).

**Comment by Malae1** [comment]
Fixed in next update
