### ISSUE TITLE
Inscription

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#2141]
It seems that Inscription is heavily bugged. The only items I create for this skill is ink. I'm not sure if this is happening for everyone else but this started happening to me when my skill hit 249.

**Comment by Malae1** [comment]
I was not able to reproduce this. Have you been learning new glyphs through the research?

**Comment by AuraChan** [comment]
Both from research and through a trainer. None are working except for ink, I can make as much ink as I want with no problems.
