### ISSUE TITLE
The Hinterlands - Quest - In Defense of Quel'Danil

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2168]
Title : In Defense of Quel'Danil
Link Wowhead : http://www.wowhead.com/quest=27625/in-defense-of-queldanil

Side : Alliance
Start with : Anchorite Traska
End with : Anchorite Traska

Why it doesn't work : There is no Deathstalker Invader, thus you cannot kill 16 of them. There should be Deathstalker Invaders attacking bloodelves everywhere but nothing in sight.

Screenshot IG : 
![wowscrnshot_082415_155406](https://cloud.githubusercontent.com/assets/13908354/9446835/1d553998-4a94-11e5-8964-6cfc53e1d4da.jpg)
![wowscrnshot_082415_155432](https://cloud.githubusercontent.com/assets/13908354/9446836/1dda0f7e-4a94-11e5-8e97-0ca1e63e31d0.jpg)

**Comment by GMTyrial** [comment]
Duplicate https://github.com/HellscreamWoW/Tracker/issues/766
