### ISSUE TITLE
Dustwallow Marsh - Quest - Corrosion Prevention

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2211]
Title : Corrosion Prevention
Link Wowhead : http://www.wowhead.com/quest=27347/corrosion-prevention

Side : Alliance
Start with : Moxie Steelgrille
End with : Moxie Steelgrille

Why it doesn't work : When i use quest item (Ooze Buster) on Oozes, nothing happens thus you canno't dissolve them. It's written : you can't do that right now

Screenshot IG :
![wowscrnshot_082615_200225](https://cloud.githubusercontent.com/assets/13908354/9501910/6921da66-4c2e-11e5-94f5-ec1dcf122aa2.jpg)

**Comment by zwei7** [comment]
Had the same problem.

**Comment by K-Reeboo** [comment]
In fact, quest work.

You have to place yourself near one of the sparkling engines and be touched by a sparklling beam. Then use the device on the targeted ooze. After a short time, it will dissolved, updateing the counter.

Here a screenshot :

![wowscrnshot_121915_080733](https://cloud.githubusercontent.com/assets/16204587/11913153/17e537fc-a628-11e5-8bda-4d2022118fe9.jpg)

**Comment by Tregeta** [comment]
This is correct :-)

**Comment by lordsk8** [comment]
Still don't count as a dissolved when you are energized, bugged.

**Comment by TheRealHoboo** [comment]
need to remove this from the quest tracker
