### ISSUE TITLE
Hearthstone sets to Warchief's Lookout in Dustwallow Marsh

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#2284]
http://wowwiki.wikia.com/wiki/Beezil's_Wreck
http://wowwiki.wikia.com/wiki/Warchief's_Lookout

Showing what it was set to beforehand.

![wowscrnshot_083015_200349](https://cloud.githubusercontent.com/assets/12555606/9570221/79c22e26-4f52-11e5-90e9-d5d7c66db969.jpg)

Screen capping the second it changes.

![wowscrnshot_083015_200407](https://cloud.githubusercontent.com/assets/12555606/9570222/7bf01370-4f52-11e5-9374-75df56aaaf79.jpg)

For whatever reason, when moving around in this area, my hearthstone (Gnome Monk in this case) sets to the Goblin 5-10 zone in the Lost Isles.

**Comment by rist9** [comment]
I propose you guys just put portals on the Lost islas as many people seem to get stuck there. Too many people.

**Comment by Malae1** [comment]
It is an option, however, we'd like to find the route cause and eliminate it indefinitely.

**Comment by derety** [comment]
Happened to me
