### ISSUE TITLE
Skinnig Issue after Recent Update

### ISSUE THREAD

**Issue by narik89** [HellscreamWoW/Tracker#2304]
Hi Team,

The skinning is not working now after the recent update. When i try to skin a creature (right click on it) the pointer changes to a hand with glowing as such to select the creature again, but it is not working. Could you please check into this?

I am attaching screenshots with this post. But the mouse pointer is not showing in the shots.
![wowscrnshot_090115_071816](https://cloud.githubusercontent.com/assets/13406028/9594546/b4c03ef0-5079-11e5-875a-c140f0dd8468.jpg)
![wowscrnshot_090115_071820](https://cloud.githubusercontent.com/assets/13406028/9594545/b4bf8f96-5079-11e5-8cd1-33a318d9621a.jpg)

Regards
Druider

**Comment by silverjade** [comment]
I've had this happen to me before the last update with some mobs (especially those where you are there). But it was only with select mobs that it occurred on. Try skinning mobs outside of that area?

**Comment by narik89** [comment]
Hello,

Yes i would agree with you. Only in the place i was i am unable to skin. Sorry for this wrong judgement.

Regards
Druider
