### ISSUE TITLE
Hellfire Peninsula - NPC - Major double spawn

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2319]
Here is a map of every douple spawn i've seen so far.

![hellfire peninsula - 2](https://cloud.githubusercontent.com/assets/13908354/9626101/6316e940-515b-11e5-866f-9904c3320459.png)

NB : The white square is nothing, i tried to erase smth. :-p

**Comment by Malae1** [comment]
Thank you for the full zone through :+1:

**Comment by Guybrush-Hellscream** [comment]
You're welcome, i'll do that for other Outland zones because it appears to be global on this planet!

**Comment by Malae1** [comment]
Should be pretty solid now
