### ISSUE TITLE
Zangarmarsh - NPC - Major double spawn

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2323]
Here's the map!
![zangarmarsh - 2](https://cloud.githubusercontent.com/assets/13908354/9642466/93142bec-51bc-11e5-8ade-ed19f16b96d3.png)
Caption : 
1 - Inside the cave, downstairs near the boss
2 - Coosh'coosh
3 - Mire Hydra and Umbraglow Stinger around the lake (mostly on the east side)
4 - 3 green giants on the same spot
5 - Couple Marshfang Ripper
6 - Nagas
7 - Green giants again, damn them!
8 - Marshlight Bleeder, bloody bugs!
9 - Couple Fen Striker, i'd say too close from each other

**Comment by Malae1** [comment]
Looks pretty good now.
