### ISSUE TITLE
Bled Dry quest issue

### ISSUE THREAD

**Issue by nobnob2015** [HellscreamWoW/Tracker#2325]
Doing the bled dry quest (3rd one in draenor after entering the portal). Game crashed so had to relog. After coming back in none of the quest NPCs are there so can't turn in.

**Comment by Malae1** [comment]
They are at further location down the road.

**Comment by nobnob2015** [comment]
I've tried all the way down to the bridge, down to the 3 orbs and even back up past where the portal used to be, I just got auto-ported back into the place where the yellow question mark is but no one there.

**Comment by nobnob2015** [comment]
In Addition if I abandon the quest, hearth back to stormwind and relog, Archmage Khadgar starts talking as if I was back through the portal, even though I'm in Stormwind and he's not with me.

**Comment by Malae1** [comment]
Khadgar is no longer in Stormwind, so i don't know how you're talking to him there.

**Comment by nobnob2015** [comment]
Yes that is my point. I guess a picture is needed... attaching a screenshot of having logged in in the middle of the elwynn forest.
![quest_bug](https://cloud.githubusercontent.com/assets/14104770/9669014/b29a20fa-527c-11e5-8347-8ea4fbc95714.jpg)

**Comment by nobnob2015** [comment]
Screenshot of the return place with the yellow question mark here on map but room out of phase.

![quest_bug2](https://cloud.githubusercontent.com/assets/14104770/9672048/2fd7222c-528f-11e5-9787-b810de02bb13.jpg)

**Comment by Malae1** [comment]
Proceed down the trail, he is before altar altercation starts.

**Comment by nobnob2015** [comment]
No, if I go towards the altar, it automatically teleports me back to the room where they ran to before. (the one in the image above)

**Comment by Malae1** [comment]
Drop the quest, leave the area, return and then try.

**Comment by nobnob2015** [comment]
It's NOT the arena quest, it's a few quests before that. It's the 2 guys just outside the hut to free prisoners from cages. I have tried dropping the quest and redoing it again but the turn in NPC is never there.

This is a huge problem as I can't do anything else, I can't abandon the whole quest line either, if I try to go anywhere else I just get teleported back to the hut.

**Comment by Malae1** [comment]
Looks like it's working perfectly fine to me.

![Bled Dry](http://i.imgur.com/DkcXlWx.jpg)

**Comment by nobnob2015** [comment]
Still no luck. here is my screenshot .... (there is no one here) 

![stillbugged](https://cloud.githubusercontent.com/assets/14104770/9720756/54eb78fe-5589-11e5-8d90-35123ab5f30a.jpg)

**Comment by Malae1** [comment]
You are somehow phased out of the correct area then. The quest indeed works though. I'll pass this along hoping to correct your phase.

**Comment by HellscreamWoW** [comment]
Just re-log. The correct phase will be set then.

**Comment by nobnob2015** [comment]
I have logged and reclogged and reclogged many times. As you can see I have been stuck on this spot for over a week now so that did not sort anything.

**Comment by Malae1** [comment]
Have you tried relogging after removing the quest and leaving the area? (Back to Stormwind)

**Comment by nobnob2015** [comment]
Yes I have dropped the quest twice now , hearthed back to stormwind, gone all over the place and no luck.

If you look at the screenshots above (in elwynn forest) you can see that he still tries to talk to me even though I'm nowhere in the area.

As this is taking so long and I bought the boost for this guy with points, can you guys just refund those points and I'll delete this guy and start again?

I would REALLY like to carry on playing and it's been over a week of no progression.

**Comment by Malae1** [comment]
What is a convenient time for you? I have attempted to bring you to the correct phase.

**Comment by nobnob2015** [comment]
I'm on around 17:00 - 19:00 GMT time on most days.

**Comment by nobnob2015** [comment]
Also the phase fix didn't work, I've tried logging in and out all over the place with no luck.

**Comment by Malae1** [comment]
We will need to be online at the same time to do a proper phase fix. If at all possible transitioning this to the forum would be great. You can Send me a private message there.

**Comment by nobnob2015** [comment]
Online now ... what's your ingame name ?
