### ISSUE TITLE
Outland Madness - Round 3 - Terrokar Forest

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2326]
Alright man, this round is a tough one. Put your sunglasses on and do your magic! Good luck! :ghost: 
![sunglasses](https://cloud.githubusercontent.com/assets/13908354/9655331/a27139d0-5230-11e5-9006-792c28097d0a.gif)
Here's the map
![terrokar forest - 2](https://cloud.githubusercontent.com/assets/13908354/9655631/d51e88b8-5232-11e5-83fc-b725973d8237.png)

Caption : 

1 - Torgos is not supposed to be spawned unless he is called via the quest
2 - Double spirits everywhere!
3 - Outside and inside the tomb man, they're all around!!!
4 - Bonelashers
5 - Rotten trees
6 - Scorpids
7 - Spiders
8 - Warp Hunters
9 - Ogres
10 - Cabal people

A - Skyguard Scout (they're friendly but that's too many on the same spot)
B - Orcs
C - Wolves
D - Warp Stalker
E - Basilics
F - Teromoth
G - Bird guys
H - Birds reunion in Shattrah
I - Auchenai dudes

**Comment by Malae1** [comment]
Should be all of em, that was definitely a run through!
