### ISSUE TITLE
Bug westfall

### ISSUE THREAD

**Issue by Enisximeni** [HellscreamWoW/Tracker#2327]
![wowscrnshot_090315_143533](https://cloud.githubusercontent.com/assets/14073401/9657395/51298654-5249-11e5-8613-794053e7cc6c.jpg)
 so the bg is i have hero call for westfall i am at the quest giver place i see it on mini map but i dont see NPCS to give quest.first i think they have been killed i am waiting 5 hours nothing no Npc HERE

**Comment by Guybrush-Hellscream** [comment]
#482, #1277, #1358, #1474
check out #2235 for more infos about quest issues

**Comment by HellscreamWoW** [comment]
ref #2235
