### ISSUE TITLE
Druid Spell Rip

### ISSUE THREAD

**Issue by DeathQueen** [HellscreamWoW/Tracker#2328]
it shows and does 0 damage at any combo point level

**Comment by silverjade** [comment]
On my druid Rip does do damage, however the damage is low no matter how many combo points you use. Including a screenshot of the damage that is said to be done by a 4 combo point Rip here: 
![wowscrnshot_090315_151206](https://cloud.githubusercontent.com/assets/13601831/9669716/6e2bb0ec-524e-11e5-92a7-4a7b1549caf6.png)

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020010.
