### ISSUE TITLE
Deviate Cobra being spawned in Venture Co Mine in Mulgore

### ISSUE THREAD

**Issue by silverjade** [HellscreamWoW/Tracker#2330]
Not sure what caused this to start occurring, given it wasn't happening when I ran my druid & mage through this mine earlier this year. But I just took my shaman to the Venture Mine in Mulgore and upon killing the Supervisor for the quest a ?? lvl Deviate Cobra spawned where the Supervisor had previously stood.

Logged onto my priest to kill it, it was gone by the time she got to the mine. I pulled the Supervisor again and the moment the the Supervisor Fizsprocket moves from his usual position, the cobra spawns.

Edit: Here's a screenshot of it I took on my priest

![](http://i.imgur.com/FBmnq46.png)

**Comment by HellscreamWoW** [comment]
Fixed.
