### ISSUE TITLE
[Shaman Spell] Lightning Shield Consumed by Spells

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#2336]
Certain spells I use are consuming Lightning Shield. Spells that keep consuming Lightning Shield are Stormstrike, Lava Lash, Flame Shock, Fire Nova, and Frost Shock. It also seems that after using any of these spells Lightning Shield disappears when I'm hit by mobs.

Info on Stormstrike,
http://www.wowhead.com/spell=17364/stormstrike

Lava Lash,
http://www.wowhead.com/spell=60103/lava-lash

Flame Shock,
http://www.wowhead.com/spell=8050/flame-shock

Fire Nova,
http://www.wowhead.com/spell=1535/fire-nova

Frost Shock,
http://www.wowhead.com/spell=8056/frost-shock

Info on spell being affected Lightning Shield,
http://www.wowhead.com/spell=324/lightning-shield

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020006.
