### ISSUE TITLE
{Talent} {Paladin} Selfless healer

### ISSUE THREAD

**Issue by Luminescent-Hellscream** [HellscreamWoW/Tracker#2344]
Currently with the tallent  [Selfless Healer] you can cast flash of light as many times as you want with out a cast time at 3 stacks for the duration of the buff, this is not how it should be once you have stacks of  Selfless Healer and get off a cast of flash of light the buff should be removed.

I will upload footage later to show that it is indeed bugged on hellscream.
https://www.youtube.com/watch?v=rhwSqWoWkjw
http://www.wowhead.com/spell=85804

**Comment by Moustachos** [comment]
Fixed on next update.

**Comment by Guybrush-Hellscream** [comment]
#2266
