### ISSUE TITLE
Quest: Shimmercap Stew

### ISSUE THREAD

**Issue by evienda** [HellscreamWoW/Tracker#2362]
Can't target the sweetroot to gather it for the quest.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/quest=12483/shimmercap-stew

**Comment by Guybrush-Hellscream** [comment]
This quest is doable, [Sweetroots](http://www.wowhead.com/item=37087/sweetroot) can be taken! You probably targeted the wrong plants!
![wowscrnshot_090515_190146](https://cloud.githubusercontent.com/assets/13908354/9700389/21c24450-5401-11e5-9609-d1e467bdacb6.jpg)

**Comment by Dushku** [comment]
I too was able to complete the quest without issue. It's still listed in the tracker though.

**Comment by Malae1** [comment]
When an issue is closed it is resolved.
