### ISSUE TITLE
Trainers not Responding

### ISSUE THREAD

**Issue by narik89** [HellscreamWoW/Tracker#2369]
Hello,

I see that trainers other than the Hometown do not respond or talk with me. Is it a character issue or it is a bug with the game scripting?

For Eg: Trainers in Shattarah,Dalaran ot any other place other than hometown do not speak to me. I have to either go to Ogrimmar or Thunder Bluff to train each and every time.

Could you please check out on this issue. It would save lot of time and also some frustration.

IGN : Druider

Regards
Druider

**Comment by Malae1** [comment]
Specific NPCs names if you don't mind.

**Comment by silverjade** [comment]
Shattrath City Profession Trainers:
http://wowwiki.wikia.com/wiki/Darmari
http://wowwiki.wikia.com/wiki/Enchantress_Volali
http://wowwiki.wikia.com/wiki/High_Enchanter_Bardolan
http://wowwiki.wikia.com/wiki/Hamanar
http://wowwiki.wikia.com/wiki/Zula_Slagfury
http://wowwiki.wikia.com/wiki/Kylene
http://wowwiki.wikia.com/wiki/Jack_Trapper
http://wowwiki.wikia.com/wiki/Lorokeem
http://wowwiki.wikia.com/wiki/Mildred_Fletcher
http://wowwiki.wikia.com/wiki/Seymour

**Comment by silverjade** [comment]
The Dalaran Trainers: 
http://wowwiki.wikia.com/wiki/Dalaran_NPCs#Magus_Commerce_Exchange 

I noticed that none of them work myself in either Shatt or Dal, most refuse to even open a window, those that do just say "Greetings <name>"

**Comment by Malae1** [comment]
Definitely gossip options then.

**Comment by narik89** [comment]
Hi,

As silverjade mentioned. Its all the trainers. Primary prof, secondary. All trainers in all places other than the starting places of all faction do not talk.

Regards
Druider
