### ISSUE TITLE
Bugged Heirlooms !!!

### ISSUE THREAD

**Issue by vation1234** [HellscreamWoW/Tracker#2374]
So I might be just stupid, but I bought a Ancient Heirloom Armor Casing for coins of ancestry but when I try to use it on my level 100 heirloom it just keeps telling me "That item is not a valid target".
Has anyone successfully used it or having the same issue? I'm very confused right now.
:( :( :( 
[img]http://i.imgur.com/OpUDS6M.jpg[/img]

I'm nervous

**Comment by Guybrush-Hellscream** [comment]
"Only work on heirlooms that scale to level 90."
Are you trying to use it on level 60 heirlooms?

**Comment by HellscreamWoW** [comment]
You first need to upgrade the heirloom to scale to 90, before you can upgrade it to scale to 100.
