### ISSUE TITLE
[Quest] The Bear's Blessing

### ISSUE THREAD

**Issue by Ryunosukeknt** [HellscreamWoW/Tracker#2382]
after getting the bear paw herbs, i need to get some of Fleetfoot's tailfeathers, but.... where fleetfoot is SUPPOSED to spawn at, there is none, quest guide is missing darkshore, ashenvale. and ultimate quest tracker has nothing on it either.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/quest=13544/the-bears-blessing

**Comment by HellscreamWoW** [comment]
ref #2235
