### ISSUE TITLE
Lesser Infernal untargetable

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#2394]
www.wowhead.com/quest=14373/infernal-encroachment
http://www.wowhead.com/npc=35591/lesser-infernal

You are not able to target these creatures and they are able to be aggro'd. Also they seem to be double spawning.

Edit: Ok, I also found a mob called "lesser infernal" that is invisible but is able to be targeted. An example of the double spawns are also available with the creatures (the untargetable ones) around the location in the screenshot.

![wowscrnshot_090715_172232](https://cloud.githubusercontent.com/assets/12555606/9722964/14b17404-5585-11e5-804e-21a997025d59.jpg)

**Comment by Malae1** [comment]
Looks like it's not possible to clear these spawns. Moved to scripting.

**Comment by Malae1** [comment]
Fixed in next update
