### ISSUE TITLE
[Quest] Ferocitas the Dream Eater

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#2397]
The issue is that, there are too many spawned mobs in the quest's area, and the mob "Ferocitas the Dream Eater" for the quest is duplicated twice, also the quest item that you should get from the mob "Ferocitas the Dream Eater" is available to be looted from all of the mobs in the area of the quest, while it should only be available for loot from the mob "Ferocitas the Dream Eater".

Quest link: http://www.wowhead.com/quest=2459/ferocitas-the-dream-eater

Mob "Ferocitas the Dream Eater" link: http://www.wowhead.com/npc=7234/ferocitas-the-dream-eater

**Comment by Malae1** [comment]
Flagging as multiple spawns until cleared area of them, then will revert back to quest only.

**Comment by Guybrush-Hellscream** [comment]
Fixed. :palm_tree:

**Comment by phikaro** [comment]
Yea it's fixed, but now the quest item Tallonkai's Jewel is dropped twice when killing the mob "Ferocitas the Dream Eater", it's dropped as necklace  and as Jewel, while the Jewel  is also found in the necklace.

**Comment by Guybrush-Hellscream** [comment]
Thank you for your input, it'll be fixed in next update. :palm_tree:
