### ISSUE TITLE
Adventure Guide content selection bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#2401]
The Adventure Guide does not allow for choosing the raids tab when Classic, The Burning Crusade or Wrath of the Lich King content is selected.

**Comment by Malae1** [comment]
Not certain on this, but I believe this doesn't even work on retail.

**Comment by Collector-Hellscream** [comment]
I think there's no such thing in WoD. Dungeons & Raids list was added in cataclysm and had just cata dungeons and raids in it. Then in MoP old content DUNGEONS (not raids) were added and ofc mop dungeons and raids. In WoD it was renamed to adventure guide with suggested content.

**Comment by Malae1** [comment]
As collector has mentioned, and I have confirmed this on Retail.
