### ISSUE TITLE
Dyslix Silvergrub[Flight Master]

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#242]
Unable to take flight, no option.

**Comment by Reloque** [comment]
[Dyslix Silvergrub](http://www.wowhead.com/npc=40358)(40358) is the Flight Master for Mudsprocket, Dustwallow Marsh.

The for my Horde character, the flight path reads (with and without the quest "[To The Summit](http://www.wowhead.com/quest=25356)"(25356) in my log):

    Quest - "To The Summit" - Camp Mojache -> Westreach Summit - Begin

It is also unlinked to other nodes.
