### ISSUE TITLE
Warlock bug

### ISSUE THREAD

**Issue by MandrarK** [HellscreamWoW/Tracker#2431]
I can summon my Imp, but there is no action bar, and he doesn't attack with me. Is that bugged or do I need a specific level to control him? Is that normal?
![wowscrnshot_090915_150102](https://cloud.githubusercontent.com/assets/12882321/9770036/1da6dfd8-5704-11e5-9f2b-fd5a65cf85b3.jpg)

**Comment by silverjade** [comment]
You'll need to hit lvl 10 before you get a control bar for the imp. It's a known issue that pets/minions don't attack below 10 at times.

**Comment by MandrarK** [comment]
Thank you so much, silverjade

**Comment by Malae1** [comment]
1-10 you are unable to force it to attack unless you make a macro /petattack.

**Comment by Mushrambo** [comment]
I also found bugs.
1.Immolate doesn't apply a DoT.
2.Chaos Bolt doesn't crit.

**Comment by Physeeeeee** [comment]
Actually i dont have the control pet skill, im hunter lvl 10 that means that i dont have the pet action bar...

**Comment by EPS1L0N** [comment]
ref #2266
