### ISSUE TITLE
[NPC] Admiral Odesyus

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#2440]
This npc does not have quests for my night elf, and I have completed the quest that should unlock the quests for this npc, not sure if it works for draenei, but as night elf he does not have have quests for me, and his quests are not race locked, they are for all alliance races.

http://www.wowhead.com/npc=17240/admiral-odesyus#starts

**Comment by Guybrush-Hellscream** [comment]
You didn't complete the pre-requisite since it's a **draenei only** quests line.
[Pre-requisite](http://www.wowhead.com/quest=9505/the-prophecy-of-velen).
So this is not an issue since Blizzard changed this quests line to be drenei only.

**Comment by phikaro** [comment]
I see, oh well I'll close the ticket then. =)
