### ISSUE TITLE
Permanent debuff with Totem (Dwarf mission)

### ISSUE THREAD

**Issue by Trekex** [HellscreamWoW/Tracker#2499]
Hi I play as a Dwarf Hunter and started today playing. Since i did a quest in Dun Morogh to destroy the totems of the troll, I got a permanent visual debuff that doesn't disappear. i tried to log out and in or close the game, but it's still here. So I kept playing and I did a screenshoot. The debuff as I said is only visual and does nothing, but it's boring to play with it :(
![wowscrnshot_091315_202136](https://cloud.githubusercontent.com/assets/14263412/9838209/b1e824b2-5a57-11e5-8b6a-5221431af049.jpg)

**Comment by silverjade** [comment]
If you die, it will leave. So far this is the only way I know of to get rid of it.

**Comment by Trekex** [comment]
Yes, I died and it disappeared! And so I let my pet die too to make it disappear from him too.
