### ISSUE TITLE
[Quest] Tirisfal Glades - A Scarlet Letter

### ISSUE THREAD

**Issue by hugomarciano** [HellscreamWoW/Tracker#2511]
Quest: A Scarlet Letter
Wowhead: http://www.wowhead.com/quest=24979/a-scarlet-letter

Side: Horde
Start:  A Scarlet Letter
End: Deathguard Simmer

Cause: "Lilian Voss is not stuck in the cage."

**Comment by Guybrush-Hellscream** [comment]
[Fixed.](http://www.hellscream-wow.com/log#2015.21.09.020012)
