### ISSUE TITLE
[NPC] Dun Morogh - Innkeeper Belm <Innkeeper>

### ISSUE THREAD

**Issue by hugomarciano** [HellscreamWoW/Tracker#2515]
NPC: Innkeeper Belm <Innkeeper>
Wowhead: http://www.wowhead.com/npc=1247/innkeeper-belm

Faction: Ironforge

Cause: "The innkeeper doesn't let us make your Inn our home and doesn't sell us your items."

**Comment by Guybrush-Hellscream** [comment]
Fixed. :palm_tree:
