### ISSUE TITLE
[NPC] Pilot Marsha

### ISSUE THREAD

**Issue by silverjade** [HellscreamWoW/Tracker#2517]
![wowscrnshot_091415_130858](https://cloud.githubusercontent.com/assets/13601831/9857721/e66e60f4-5ae1-11e5-972f-6bd342f617e5.jpg)

She's supposed to be a vendor (an Engineering one) but she doesn't give you the option to check her wares or to sell anything to her.

http://www.wowhead.com/npc=18278/pilot-marsha

**Comment by Guybrush-Hellscream** [comment]
Fixed. :palm_tree:
