### ISSUE TITLE
Whelgar's Retreat "Dead" Dinosaurs

### ISSUE THREAD

**Issue by Trekex** [HellscreamWoW/Tracker#2518]
Hi. I was walking along Whelgar's Retreat in Wetlands when something hit me. Then I noticed that were some dead Dinos that are positioned in the camp and near the entrance. They shouldn't move and I can't hit them cause they are not true enemies, but they hit me (and very heavy too). So i had to do an other path and solved, but they are bugged.
![wowscrnshot_091415_221557](https://cloud.githubusercontent.com/assets/14263412/9861270/823ef6e8-5b31-11e5-9103-4fab00b2e38b.jpg)

**Comment by Malae1** [comment]
Fixed in next update
