### ISSUE TITLE
Legacy System

### ISSUE THREAD

**Issue by Nienz** [HellscreamWoW/Tracker#2519]
Was doing Onyxias lair and i couldnt set it on 10man cus it auto set 25man and mobs had 800k+ hp in there so couldnt do much, works nicely on TBC contents tho

**Comment by Malae1** [comment]
This is most likely from WotLK onwards, plan to test shortly. Since TBC did not have a different lockout for 10 and 25 man.

**Comment by Malae1** [comment]
Awaiting a response.

**Comment by Nienz** [comment]
yes im sure, was set properly, atm i have a save so once its reset ill check if it works

**Comment by Nienz** [comment]
oke i checked it properly had to find a 10-25man raid i knew about and that was firelands, and it worked guess im still a nuub on wow on certain stuff, this legacy system is still news for me, sry for taking the time on this matter,so my bad and i apologize, should had checked it properly

**Comment by Malae1** [comment]
Thanks for the follow up.
