### ISSUE TITLE
[Quest][Mulgore] The Restless Earth

### ISSUE THREAD

**Issue by Orothus** [HellscreamWoW/Tracker#2522]
In this quest we must use "Drum of the Soothed Earth" on Earth Spirits. But when i use this quest item on moob nothing happens. Use this spell, drums fly to my target, spin around my target, and nothing.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/quest=14491/the-restless-earth

**Comment by Orothus** [comment]
Zon start, troll side not tauren :)
