### ISSUE TITLE
[Quest] Teldrassil - Ferocitas the Dream Eater

### ISSUE THREAD

**Issue by hugomarciano** [HellscreamWoW/Tracker#2526]
Quest: Ferocitas the Dream Eater
Wowhead: http://www.wowhead.com/quest=2459/ferocitas-the-dream-eater

Side: Alliance
Start: Tallonkai Swiftroot
End: Tallonkai Swiftroot

Cause: "I just found the Tallonkai's Jewel (http://www.wowhead.com/item=8050/tallonkais-jewel) on a  
Gnarlpine Mystic, and not on the Ferocitas the Dream Eater".

**Comment by Guybrush-Hellscream** [comment]
Fixed. :palm_tree:
