### ISSUE TITLE
[Quest] The Zhevra

### ISSUE THREAD

**Issue by Malae1** [HellscreamWoW/Tracker#2531]
[The Zhevra](http://www.wowhead.com/quest=845)

The creatures "[Zhevra Runner](http://www.wowhead.com/npc=3242/zhevra-runner)" are invalid targets and are laying on the ground like they are dead.

![Zhevra](http://i.imgur.com/gZZoorC.png)

**Comment by BraynStorm** [comment]
Duplicate of #1092?
