### ISSUE TITLE
Skills at 0/0

### ISSUE THREAD

**Issue by KhurleeV** [HellscreamWoW/Tracker#2550]
fishing cooking first ait archaeology bug missing. 

my 2 pets is missing.... pet call in but  no out no pets. summons is not working.... PLS HELP ME

![dawdw](https://cloud.githubusercontent.com/assets/14320792/9920041/f17b06e2-5d0b-11e5-8d25-09b763717968.jpg)

HI yesterday help gnomish engineering bug.... can you help me. unlearn try agian learn 300/300 point . only engineering is bug fix it. only engineering is. pls pls pls.. back up professions... pls pls

**Comment by Malae1** [comment]
Did you just recently take gnomish engineering?

**Comment by KhurleeV** [comment]
HI yesterday help gnomish engineering bug.... can you help me. unlearn try agian learn 300/300 point . only engineering is bug fix it. only engineering is. pls pls pls...

**Comment by KhurleeV** [comment]
#2550

**Comment by Malae1** [comment]
Ref #2929 Should be fixed soon/next update.
