### ISSUE TITLE
[Druid] Tiger's Fury can be cast during Berserk

### ISSUE THREAD

**Issue by silverjade** [HellscreamWoW/Tracker#2556]
Tiger's Fury is currently useable while you're under Berserk's affect as a druid. When I was last on retail you can cast TF right before you Berserk but not during Berserk.

http://www.wowhead.com/spell=5217/tigers-fury
http://www.wowhead.com/spell=106952/berserk

**Comment by EPS1L0N** [comment]
[![TF+Berserk Test](http://img.youtube.com/vi/CLL88l-cUNk/0.jpg)](http://www.youtube.com/watch?v=CLL88l-cUNk "TF+Berserk Test")

TF can be cast while berserk is up on retail
