### ISSUE TITLE
[Quests] [Eastern Kingdoms] [Elwynn Forest] The Collector

### ISSUE THREAD

**Issue by hugomarciano** [HellscreamWoW/Tracker#2559]
Quest: The Collector
Wowhead: http://www.wowhead.com/quest=123/the-collector

Side: Alliance
Start:  Gold Pickup Schedule
End: Marshal McCree

Cause: "I killed James Clark twice and he did not drop the item that starts the mission."

**Comment by silverjade** [comment]
I looked up the item that starts this quest. It states it's a guaranteed drop. So, it's a drop rate issue, since some people have said they've gotten this from James Clark. 

http://us.battle.net/wow/en/item/1307

**Comment by Guybrush-Hellscream** [comment]
#2235
