### ISSUE TITLE
[Quests] [Eastern Kingdoms] [Tirisfal Glades] Recruitment

### ISSUE THREAD

**Issue by hugomarciano** [HellscreamWoW/Tracker#2562]
Quest: Recruitment
Wowhead: http://www.wowhead.com/quest=26800/recruitment

Side: Horde
Start: Deathguard Saltain
End: Deathguard Saltain

Cause: "The Deathguard Saltain does not end the quest. Simply not appear question mark on it."

**Comment by Malae1** [comment]
Ref #1924, #284, #4
