### ISSUE TITLE
I'm stuck on a blimp

### ISSUE THREAD

**Issue by Illidanpwner** [HellscreamWoW/Tracker#2572]
Whenever I log on to my char I either, never get passed the loading screen or get disconnected I was flying from Orgrimmar to STV and for some reason I can't get passed so now I'm stuck... :)

**Comment by Malae1** [comment]
Client likely corrupted, please reinstall/repair and follow our How to Connect guide. You can also give me your character and I can teleport you while you do these steps to be in a safe position.

**Comment by Illidanpwner** [comment]
his name is Merick  thanks again

**Comment by Illidanpwner** [comment]
no need I was able to repair and reset it thanks again for information
