### ISSUE TITLE
Pandaria flying skill should require lvl 85 (and not 90)

### ISSUE THREAD

**Issue by Dev-iL** [HellscreamWoW/Tracker#2594]
Link: [Wisdom of the Four Winds](http://www.wowhead.com/spell=115913/wisdom-of-the-four-winds).
This was changed in patch 6.1.0 according to wowhead.

When you try to learn the skill @ [trainer](http://www.wowhead.com/npc=60167/skydancer-shun), even though it says 85 in the tooltip, you can't learn it being lvl 85.

**Comment by llamalama** [comment]
This is how it is supposed to be. If you read the comments on the page, you will see that the only way you're supposed to be able to learn flying there at 85 is if you get an item from the Black Market Auction House.
http://www.wowhead.com/item=110672/grimoire-of-the-four-winds

**Comment by Dev-iL** [comment]
@llamalama Seems like a bug @ blizzard, if the book works from 85 (not that it exists on the server...) there's no reason the trainer shouldn't too. 
Books like this (e.g. [Tome of Cold Weather Flight](http://www.wowhead.com/item=49177/tome-of-cold-weather-flight)) only save you the need to walk to the trainer, otherwise it would be seriously imbalanced.

**Comment by Guybrush-Hellscream** [comment]
This is a retail bug.
If you look at comments (http://www.wowhead.com/spell=115913/wisdom-of-the-four-winds), you'll see that they have this problem on retail too.
> By ssscrudddy (1,235 – 4·9) on 2015/03/29 (Patch 6.1.2)		
Despite this site saying level 85, you need to be level 90. I just made it to Shrine of the 2 Moons as a lvl 86 hunter, but it says I need to be lvl 90.
