### ISSUE TITLE
Legacy buff and damaging finishers

### ISSUE THREAD

**Issue by Aveta** [HellscreamWoW/Tracker#2601]
Damage of finishing moves like Eviscerate, Kidney Shot (when the Internal Bleeding talent is selected) and possibly every other damaging finisher isn't increased at all by legacy buff.

**Comment by Collector-Hellscream** [comment]
I would like to add that there is similar issue with druid's finishers. They are not affected by legacy buff.

**Comment by Malae1** [comment]
Priests damage spells all seem to be affected as well.
