### ISSUE TITLE
Tirisfal Glades - Quest - The Haunted Mills

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2610]
Title : The Haunted Mills
Link Wowhead : http://www.wowhead.com/quest=25030/the-haunted-mills

Side : Horde
Start with : [Dargol's Skull](http://www.wowhead.com/item=3082/dargols-skull)
End with : Coleman Farthing

Trouble : It's a loot issue. You get this quest by looting [Dargol's Skull](http://www.wowhead.com/item=3082/dargols-skull) on [Captain Dargol](http://www.wowhead.com/npc=1658/captain-dargol). Here, the guy is not dropping it, i've tried to kill him 5 times and nothing.

**Comment by Malae1** [comment]
Fixed in next update
