### ISSUE TITLE
death knight [Death Siphon] bug

### ISSUE THREAD

**Issue by avandarkwalker** [HellscreamWoW/Tracker#2613]
Death Siphon http://www.wowhead.com/spell=108196/death-siphon doesn't give any heal at all. 
One more note i think i should mention with you guys, most of the other private servers have the same common bug for siphon which only give heals to the normal damage but not the heals based on crits.
Exp: I hit for 1k it will heal me 4k in return, but when it crits for like 2k it still heals me for only 4k when it shoud have heal me for 8k. That, my dear devs, is what i've been experienced with every single private server out there, up until now, so i hope that you won't fall into their foot steps. Cheers!!

**Comment by Guybrush-Hellscream** [comment]
I'm confused, you're writing that siphon isn't healing but then you're saying that it heals but not on crits. Can you elaborate on that?

**Comment by avandarkwalker** [comment]
Sorry man, I didn't explain it carefully. The bug i want to report is that the Death Siphon in our server doesn't give heal at all and the note is the bug, that is occurring right now on the other servers. They, the other servers's devs, fixed the "doesn't give heal" part but they stubble upon the other bug like i've already explained.

**Comment by Guybrush-Hellscream** [comment]
Oh okay I see! Don't worry we have good devs, they'll get the job done! :D
