### ISSUE TITLE
Elemental Fusion

### ISSUE THREAD

**Issue by Xondas** [HellscreamWoW/Tracker#2622]
http://www.wowhead.com/spell=152257/elemental-fusion

Not working correctly with enhancement shaman spec.
Increases earthquake dmg instead shock damage

**Comment by EPS1L0N** [comment]
damage increase for Frost / Earth Shock works properly. it does not increase the damage of earthquake.
however, charges are supposed to be dropped after casting shock, which does not currently work

**Comment by EPS1L0N** [comment]
Fixed charges not being dropped. the bugs you mentioned i couldn't reproduce.
