### ISSUE TITLE
Guild gold problem

### ISSUE THREAD

**Issue by Heathclifff** [HellscreamWoW/Tracker#2630]
Seems Cash Flow : Each time you loot money from an enemy, an extra 10% money is generated and deposited directly into your guild bank doesnt work can we have that fixed a soon as possible ?

**Comment by Malae1** [comment]
This was removed in Warlords of Draenor to stop abusive Guild Masters from hoarding the gold (most did, sadly).
This is balanced by the fact that you make a killing just questing in WoD.
Additionally, you can still make gold for your guild by doing guild dungeon runs and raids.

**Comment by Heathclifff** [comment]
Didnt know about that. Yeah thats the worst thing for a guild master to do "steal" his own guild-guildies i see why the removed it.
