### ISSUE TITLE
[Quest] Pie for Billy (quest item drop rate)

### ISSUE THREAD

**Issue by silverjade** [HellscreamWoW/Tracker#2632]
http://us.battle.net/wow/en/item/60401#tab=dropCreatures

Currently you have to kill over 20-30 boars in Elywnn to get the 4 items needed for the quest "Pie for Billy" , according to Blizz; the drop rate shouldn't be that low.

http://www.wowhead.com/quest=86/pie-for-billy

**Comment by Ezekiel2244** [comment]
I think you weren't lucky. In Database drop rates are correct.

**Comment by HellscreamWoW** [comment]
ref #2235
