### ISSUE TITLE
Error after using J key to view guild..

### ISSUE THREAD

**Issue by ZoeyRandomZoe** [HellscreamWoW/Tracker#2633]
USed the J key in horde summer area temple in golden lotus got this error..

Error#132 (0x85100084) Fatal exception!   Exception:Access_ Violation  The instruction at  "0x0000000145fdd1b" referenced memory at "0x000000014197b520"

**Comment by Malae1** [comment]
Was not able to reproduce this, please try to repair your client through the battle.net app.

**Comment by ZoeyRandomZoe** [comment]
Okay, thanks..
