### ISSUE TITLE
Warrior-Wild Strike

### ISSUE THREAD

**Issue by Heathclifff** [HellscreamWoW/Tracker#2647]
Wild strike is bugged cause i can use FREE wild strikes for 14 sec instead of 2 charges that its supposed to get from Bloodthirst.

Here is a link to wild strike http://www.wowhead.com/spell=100130/wild-strike

**Comment by Malae1** [comment]
The proc name is [Bloodsurge](http://www.wowhead.com/spell=46916/bloodsurge) and should dissipate after two are consumed.

**Comment by Gozzreal** [comment]
I can't use wild strike when it procs.. It claims I do not have a melee weapon. even though im dual wielding two Tranquillion Flamberges.

**Comment by Heathclifff** [comment]
Use a 1h on ur off hand it should solve that. I dont know much about warriors but i dont think that's the way it should work i mean why fury 2x2h and use one 1h as off hand for that spell might be a bug as well.

**Comment by EPS1L0N** [comment]
#2266
