### ISSUE TITLE
[Flight between Brill and the Bulwark in Tirisfal] Stuck On the giant bat.

### ISSUE THREAD

**Issue by MaelDesaulniers** [HellscreamWoW/Tracker#2657]
My undead priest is stuck ont he giant bat since my first flight between Brill and the Bulwark and I can't do anything at all, no interaction possible. Disconnecting and reconnecting only resumes the flight midway and it ends up the same : stuck.

**Comment by silverjade** [comment]
What is your priest's name?

**Comment by Moustachos** [comment]
Will be fixed by next update :)
