### ISSUE TITLE
Travel Bug

### ISSUE THREAD

**Issue by radovicz** [HellscreamWoW/Tracker#2668]
I am level 14 and i dont know where these travel points came from(Except Durotar)
![wowscrnshot_100115_210605](https://cloud.githubusercontent.com/assets/7345131/10230941/4acec4d4-6880-11e5-9685-5b1dc0e69edf.jpg)

**Comment by HellscreamWoW** [comment]
Greetings radovicz, these travel points are the default points that Horde characters start with on retail. It's normal, and blizzlike, to have these points when starting a new character.
