### ISSUE TITLE
[Zones] [Level: 1 - 20] [Horde] [1 - Eversong Woods] Eversong Woods

### ISSUE THREAD

**Issue by hugomarciano** [HellscreamWoW/Tracker#2677]
Zone: Eversong Woods

Arcane Patroller http://www.wowhead.com/npc=15638/arcane-patroller
Wretched Urchin http://www.wowhead.com/npc=15644/wretched-urchin

Bug: All Arcane Patroller and Wretched Urchin disappeared from Eversong Woods. There was no left, at least not in Ruins of Silvermoon.

**Comment by HellscreamWoW** [comment]
Fixed! Thanks for reporting this.
