### ISSUE TITLE
[NPC] Ahanu (Leather Armor Merchant)

### ISSUE THREAD

**Issue by silverjade** [HellscreamWoW/Tracker#2678]
http://www.wowhead.com/npc=8359/ahanu

This Merchant refuses to talk to people and sell his wares. 
(About the only time he's feeling chatty is if you're a tauren on the low-lvl quest involving him. http://www.wowhead.com/quest=6362/ride-to-thunder-bluff & http://www.wowhead.com/quest=6363/tal-the-wind-rider-master )

![wowscrnshot_100115_234211](https://cloud.githubusercontent.com/assets/13601831/10239668/b5c0b354-6896-11e5-8442-56db663feb1c.jpg)

**Comment by Guybrush-Hellscream** [comment]
Fixed. :palm_tree:
