### ISSUE TITLE
[Quest] The Party Never Ends

### ISSUE THREAD

**Issue by carminejackal** [HellscreamWoW/Tracker#2679]
You can't complete this quest due to 2 items missing from their respective vendors.
Quest: http://www.wowhead.com/quest=9067/the-party-never-ends

Vendors:
http://www.wowhead.com/npc=16444/halis-dawnstrider (Bundle of Fireworks)
http://www.wowhead.com/npc=16443/zalene-firstlight (Springpaw Appetizers) 
http://www.wowhead.com/npc=16442/vinemaster-suntouched (Suntouched Special Reserve)

As you can see below the only vendor that held the quest item needed was Zalene (with the Springpaw Appetizers):
![wowscrnshot_100215_024258](https://cloud.githubusercontent.com/assets/13601831/10241660/69154fbe-68b0-11e5-9fc1-5ff76d9b1180.jpg)
![wowscrnshot_100215_025407](https://cloud.githubusercontent.com/assets/13601831/10241775/6b2b0cfc-68b1-11e5-8c83-937b164543d2.jpg)
![wowscrnshot_100215_025808](https://cloud.githubusercontent.com/assets/13601831/10241777/7394e340-68b1-11e5-8aab-af0acfc9434b.jpg)

**Comment by Malae1** [comment]
Fixed in Next Update
