### ISSUE TITLE
[Item] The Innkeeper's Daughter

### ISSUE THREAD

**Issue by Collector-Hellscream** [HellscreamWoW/Tracker#2698]
Additional hearthstone from dwarven archeology The Innkeeper's Daughter shares cooldown with the basic Hearthstone. It should not.

**Comment by silverjade** [comment]
According to Wowhead this item does share a cooldown with the Hearthstone. http://www.wowhead.com/item=64488/the-innkeepers-daughter

**Comment by Collector-Hellscream** [comment]
My bad. It's useless than...

**Comment by Guybrush-Hellscream** [comment]
I'm closing it.
