### ISSUE TITLE
Trading bugs!!

### ISSUE THREAD

**Issue by FlameChampion34** [HellscreamWoW/Tracker#27]
When trying to sell items that are not for sale, and these items are like quest items and my hearthstone, then these items turn into grey color and cannot be used. Also when trying to buy something and you don't have money, your character never says anything, while he should be saying, "I can't afford that", "It's to expensive" or "Not enough money".

**Comment by Max-Hellscream** [comment]
We'll have to verify whether or not the first part is still bugged, however the vendor errors are full working now.
