### ISSUE TITLE
Hunter - Pet disappears and doesn't attack

### ISSUE THREAD

**Issue by Netherlord** [HellscreamWoW/Tracker#2700]
I've experienced this bug with two characters. The first time I play a hunter after creating it, the pet is with me as usual, but it does not attack the enemies I am fighting with. The pet attacks if I write /petattack, but it won't automatically do it.

When I log a second, third, even fourth time with the hunter, the pet is not there anymore. It doesn't appear in the pet list, the pet bar is not under the character healt bar, and if I try to evoke it with the whistle skill it won't give me the option to select any pet. It simply vanished.

**Comment by Netherlord** [comment]
I've reached level 10 without any pet to test if the mobs I can tame disappear in the same way. Luckily, it seems that the starting pet is the only one that disappear completely.

**Comment by EPS1L0N** [comment]
ref #2266
