### ISSUE TITLE
[NPC] Golnir Bouldertoe <Mining Supplies>

### ISSUE THREAD

**Issue by silverjade** [HellscreamWoW/Tracker#2705]
This vendor refuses to sell his wares. 

http://www.wowhead.com/npc=4256/golnir-bouldertoe
![wowscrnshot_100215_221817](https://cloud.githubusercontent.com/assets/13601831/10261247/68b5d4b8-6954-11e5-9bd2-944bcc328e4d.jpg)

**Comment by Guybrush-Hellscream** [comment]
Fixed. :palm_tree:
