### ISSUE TITLE
Spell-Shaman:Earth Shock is missing!

### ISSUE THREAD

**Issue by MirrorWraith** [HellscreamWoW/Tracker#2710]
well, this useful spell is missing from shaman
http://www.wowhead.com/spell=8042/earth-shock
thanks

**Comment by Guybrush-Hellscream** [comment]
What spec are you in? As of WOD, it's an Elemental spell so if you're Enhancement or Restoration, you won't have it.
Source : [Wowwiki](http://wowwiki.wikia.com/wiki/Earth_Shock)

**Comment by MirrorWraith** [comment]
it should be available at level 6, before picking the spec

**Comment by Malae1** [comment]
As you can see from the photo below this is taken from retail.

[Shaman spells starting](]http://i.imgur.com/iTUyHLm.png)

**Comment by war627** [comment]
earth is removed in wod
