### ISSUE TITLE
[Raid] (My prince) Illidan from Black Temple

### ISSUE THREAD

**Issue by Collector-Hellscream** [HellscreamWoW/Tracker#2712]
That thing where you need to talk with Akama to activate fight with Illidan (my prince) doesn't work. Akama have gossip text and option to go and fight but after clicking on it nothing happens. Also there is a model of Illidan up there but it is not targetable. I think he went to LEGION expansion and left his wax figure.

**Comment by Collector-Hellscream** [comment]
It is working now. I killed my sweet prince already.

**Comment by Malae1** [comment]
Ref #2468
