### ISSUE TITLE
[NPC] Anchorite Fateema <First Aid Trainer>

### ISSUE THREAD

**Issue by silverjade** [HellscreamWoW/Tracker#2719]
She's supposed to teach players First Aid, currently she doesn't.

http://www.wowhead.com/npc=17214/anchorite-fateema
![wowscrnshot_100315_132407](https://cloud.githubusercontent.com/assets/13601831/10264473/2eb34c90-69d2-11e5-874d-2cbcc6657f2f.jpg)

**Comment by Guybrush-Hellscream** [comment]
Fixed in next update. :palm_tree:
