### ISSUE TITLE
Quest Npc Missing: Lieutenant Horatio Laine

### ISSUE THREAD

**Issue by emil494** [HellscreamWoW/Tracker#2722]
Lieutenant Horatio Laine is missing at The Jansen Stead in Westfall
Npc: http://www.wowhead.com/npc=42308/lieutenant-horatio-laine

**Comment by emil494** [comment]
Quest:

**Comment by emil494** [comment]
pls fix it as fast as possible. cant continue without him;)

**Comment by Guybrush-Hellscream** [comment]
I'd advise you to find another zone, Westfall is broken atm. Try Loch Modan. :palm_tree:

**Comment by emil494** [comment]
ok

**Comment by HellscreamWoW** [comment]
ref #2235
