### ISSUE TITLE
Resting Bonus

### ISSUE THREAD

**Issue by emil494** [HellscreamWoW/Tracker#2728]
The Resting Bonus isnt in the game.

**Comment by silverjade** [comment]
What do you mean?  If you mean the exp bonus from being in an inn or city; it is in the game. You can see my shaman has rested bonus in the below screenshot.
![wowscrnshot_100315_235247](https://cloud.githubusercontent.com/assets/13601831/10266464/f963e826-6a29-11e5-9595-5c3885015f8d.jpg)
