### ISSUE TITLE
Quest brief drop by Tainted Arcane Wraith

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#273]
The Monster Tainted Arcane Wraith dont drop the Quest Brief item its a item that starts a new quest in Sunstrider Isle at Falthrien Academy

**Comment by Guybrush-Hellscream** [comment]
This item : http://www.wowhead.com/item=20483/tainted-arcane-sliver

**Comment by Guybrush-Hellscream** [comment]
It's working. #2235
