### ISSUE TITLE
[NPC] Shatterspear Laborer & Overseers

### ISSUE THREAD

**Issue by carminejackal** [HellscreamWoW/Tracker#2732]
http://www.wowhead.com/quest=13504/shatterspear-laborers

You can complete the above quest fine, since you can kill those mobs, but they are lying on the ground in their 'dead' pose. They'll aggro and attack without changing from that pose as well. 
![wowscrnshot_100315_200221](https://cloud.githubusercontent.com/assets/13601831/10265917/b7458be0-6a09-11e5-8b35-4522e4c7b2a9.jpg)
![wowscrnshot_100315_200152](https://cloud.githubusercontent.com/assets/13601831/10265928/f75200a6-6a09-11e5-873f-b5037cd0e34b.jpg)

The overseers have the exact same issue. Also the Overseers are supposed to drop http://www.wowhead.com/item=44979/overseers-orders to start the quest: http://www.wowhead.com/quest=13506/reason-to-worry , I haven't looted the orders no matter how many I've killed.

**Comment by zwei7** [comment]
seconded, it is happening to me as well
