### ISSUE TITLE
NPC: Dannelor <First Aid Trainer>

### ISSUE THREAD

**Issue by silverjade** [HellscreamWoW/Tracker#2736]
He's nowhere to be found where he should be. 

http://www.wowhead.com/npc=4211/dannelor
![wowscrnshot_100315_222234](https://cloud.githubusercontent.com/assets/13601831/10266278/754b7e48-6a1d-11e5-820c-6a508493b1f1.jpg)

**Comment by Malae1** [comment]
Ref #429

**Comment by HellscreamWoW** [comment]
ref #2235
