### ISSUE TITLE
Sort FRAPPE SAUVAGE

### ISSUE THREAD

**Issue by Anaksunamoun** [HellscreamWoW/Tracker#2738]
Le sort Frappe sauvage du guerrier furie ne fonctionne pas, il ne reconnait pas les armes.

En cliquant sur le sort il est écrit un message d'érreur "Equipez vous d'armes"

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=100130/wild-strike

**Comment by EPS1L0N** [comment]
#2266
