### ISSUE TITLE
Raging Blow

### ISSUE THREAD

**Issue by safakakturk01** [HellscreamWoW/Tracker#2747]
Raging Below skill too not working.

**Comment by Malae1** [comment]
Topic title changed, Several reports already on Wild Strike.

Need more details as to why this is not working.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=85288/raging-blow

**Comment by Gozzreal** [comment]
It may again be because of two hander being in the off hand slot. dual wielding one handers seems to get the skills to work.

**Comment by Malae1** [comment]
Ref #2266
