### ISSUE TITLE
Marith Lazuria ID 50482

### ISSUE THREAD

**Issue by petrie1993** [HellscreamWoW/Tracker#2748]
http://www.wowhead.com/npc=50482/marith-lazuria 

Marith Lazuria, Jewel Crafting Supplies in Orgimmar, the item shop does not respond when I click on "I want to browse your goods"

This is Nimes, I don't know how to link my Hellscream account to this site, so I had to create a new profile and my name was already taken.

**Comment by Guybrush-Hellscream** [comment]
You can't link your account, you have to make a new one on Github! :palm_tree:

**Comment by Guybrush-Hellscream** [comment]
Fixed in next update. :palm_tree:
