### ISSUE TITLE
The Party Never Ends (Quest)

### ISSUE THREAD

**Issue by emil494** [HellscreamWoW/Tracker#2757]
Halis Dawnstrider dosnt sell "bundle of firework" when you get the quest "the party never ends".
NPC: http://www.wowhead.com/npc=16444/halis-dawnstrider
Item: http://www.wowhead.com/item=22777/bundle-of-fireworks
Quest: http://www.wowhead.com/quest=9067/the-party-never-ends

**Comment by Malae1** [comment]
Fixed in Next Update
