### ISSUE TITLE
Bug Talent (Warrior)

### ISSUE THREAD

**Issue by zeefire05** [HellscreamWoW/Tracker#2769]
I took [Bladestorm] when I was farming and changed it to [Avatar] before fighting world bosses. 

However, after relog, it is switched back to [Bladestorm] while the skill icon stays at [Avatar]. I have to buy Dust of Disappearance everytime I relog to change the talent back to [Avatar]

**Comment by EPS1L0N** [comment]
couldn't reproduce
#2266
