### ISSUE TITLE
The Party Never Ends (Quest) again....

### ISSUE THREAD

**Issue by emil494** [HellscreamWoW/Tracker#2786]
Vinemaster Suntouched dosnt sell "Suntouched Special Reserve" when you get the quest The Party Never Ends.
Vinemaster Suntouched: http://www.wowhead.com/npc=16442/vinemaster-suntouched
Item: http://www.wowhead.com/item=22775/suntouched-special-reserve
Quest: http://www.wowhead.com/quest=9067/the-party-never-ends

**Comment by Malae1** [comment]
Fixed in Next Update
