### ISSUE TITLE
iron stars buged

### ISSUE THREAD

**Issue by andrija2567** [HellscreamWoW/Tracker#2858]
they are killing me here and i cant fight back.This should be fixed now 
![wowscrnshot_100915_222252](https://cloud.githubusercontent.com/assets/12571057/10404685/89e3cfde-6ed4-11e5-9378-d089fcf38aca.jpg)

**Comment by Guybrush-Hellscream** [comment]
What's written in your combat log?

**Comment by Malae1** [comment]
Fixed in next update
