### ISSUE TITLE
abilities in heroic dungeons

### ISSUE THREAD

**Issue by Collector-Hellscream** [HellscreamWoW/Tracker#2864]
As a feral druid my cat abilities doesn't do any sound effects and my prowl doesn't give me stealth visual in heroic dungeons. They still do what they suppose to do, it's just cosmetic issue.

**Comment by Collector-Hellscream** [comment]
And actually it's not only for my druid spells but also for boss spells or some dungeon mechanics (and heroic raids too). I don't have that issue anywhere outside heroic difficulty.

**Comment by EPS1L0N** [comment]
ref #2266

**Comment by jareck77** [comment]
Time-Lost Proto-Drake continues bugged
http://www.wowhead.com/npc=32491/time-lost-proto-drake
[IMG]http://i62.tinypic.com/2mg6tzs.jpg[/IMG]
<a href="http://es.tinypic.com?ref=2mg6tzs" target="_blank"><img src="http://i62.tinypic.com/2mg6tzs.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

problem: I can target the Dragon but I can't kill it

**Comment by jareck77** [comment]
Area 51 sellers aren't available.

they are in Area 51, but I cant access them neither all those things that they sell
these npcs are bug:
http://www.wowhead.com/npc=58152/tini-smalls
http://www.wowhead.com/npc=54648/leeni-smiley-smalls
http://www.wowhead.com/npc=40209/grex-brainboiler
http://www.wowhead.com/npc=23396/krixel-pinchwhistle
http://es.wowhead.com/npc=54649/gran-zokk-llave-dinamometrica

<a href="http://es.tinypic.com?ref=35jfomv" target="_blank"><img src="http://i62.tinypic.com/35jfomv.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
[IMG]http://i62.tinypic.com/35jfomv.jpg[/IMG]

**Comment by Collector-Hellscream** [comment]
jareck77 I think you are doing something wrong...
