### ISSUE TITLE
[Spell] [Warlock] Rain of Fire

### ISSUE THREAD

**Issue by hendenie** [HellscreamWoW/Tracker#2870]
http://www.wowhead.com/spell=5740/rain-of-fire =rain of fire

Rain of fire does not work.
We can throw the fate, one see the animation, but no damage is emitted.
The fate is one pipe, but it does not channel.

**Comment by GMTyrial** [comment]
I tested this, and it does channel properly

https://github.com/HellscreamWoW/Tracker/issues/2266
