### ISSUE TITLE
Warrior / Last Stand (ability) Bug

### ISSUE THREAD

**Issue by Ripates** [HellscreamWoW/Tracker#2907]
Problem is that it does not increase 30%  , but only 30 hp ... :)

**Comment by Guybrush-Hellscream** [comment]
UH7e627ERf

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=12975/last-stand

**Comment by EPS1L0N** [comment]
lol nice catch

**Comment by EPS1L0N** [comment]
ref #2266

**Comment by Ripates** [comment]
i don't get it ... so you say that this is not bugg ? or what ?
