### ISSUE TITLE
Unattackable Skettis mobs in Terokkar 

### ISSUE THREAD

**Issue by carminejackal** [HellscreamWoW/Tracker#2910]
All of the mobs below will attack a player, but the player can't attack them in return.
http://www.wowhead.com/npc=21649/skettis-windwalker
http://www.wowhead.com/npc=21911/skettis-soulcaller
http://www.wowhead.com/npc=21644/skettis-wing-guard
http://www.wowhead.com/npc=21650/skettis-talonite
Also the last linked mob was playing dead as seen below, yet they still aggro and still attack.
![wowscrnshot_101015_225914](https://cloud.githubusercontent.com/assets/13601831/10414654/8b62ccee-6fa5-11e5-9023-fe661c157fb4.jpg)

**Comment by Malae1** [comment]
Fixed in next update
