### ISSUE TITLE
Invisible Elementals in Netherwing Fields 

### ISSUE THREAD

**Issue by carminejackal** [HellscreamWoW/Tracker#2921]
![wowscrnshot_101115_033748](https://cloud.githubusercontent.com/assets/13601831/10416036/41b71eea-6fca-11e5-889c-3a9430adb93d.jpg)
![wowscrnshot_101115_033816](https://cloud.githubusercontent.com/assets/13601831/10416037/4495fbe0-6fca-11e5-8a2a-a0895c5dce88.jpg)

I was doing the quest involving Engraged Air Spirits and discovered there's a few in the area that seem to be invisible.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/npc=21060/enraged-air-spirit

**Comment by Malae1** [comment]
Fixed in next update

**Comment by Trekex** [comment]
There are still some invisible

**Comment by Tregeta** [comment]
will once again be fixed.
