### ISSUE TITLE
Death Knight Runeblade

### ISSUE THREAD

**Issue by Malae1** [HellscreamWoW/Tracker#2939]
The quest [The Emblazoned Runeblade](http://www.wowhead.com/quest=12619/the-emblazoned-runeblade) is no longer possible to complete. After using the [Battle-worn Sword](http://www.wowhead.com/item=38607/battle-worn-sword) on the runeforge, it does not complete. This is the starter weapon and is detrimental.

**Comment by Moustachos** [comment]
Fixed on next update.
