### ISSUE TITLE
[Quest] Heart of the Watcher

### ISSUE THREAD

**Issue by silverjade** [HellscreamWoW/Tracker#2942]
http://www.wowhead.com/quest=26252/heart-of-the-watcher
http://www.wowhead.com/item=57935/harvest-watcher-heart
http://us.battle.net/wow/en/item/57935

When you kill Harvest Watchers at the Saldean farm, a Harvest Watcher Heart is supposed to drop and give you this quest.  Currently it hasn't dropped at all for me when I've killed them.

**Comment by Guybrush-Hellscream** [comment]
Fixed. :palm_tree:
