### ISSUE TITLE
[item] + [quest] Red Bandana + Evidence Collection

### ISSUE THREAD

**Issue by silverjade** [HellscreamWoW/Tracker#2943]
http://www.wowhead.com/item=58117/red-bandana
http://www.wowhead.com/quest=26296/evidence-collection
http://us.battle.net/wow/en/item/58117

The Red Bandana is supposed to drop upon first killing a Moonbrook Thug. Currently it doesn't. The Bandana starts the quest Evidence Collection which asks you to collect 6 red bandana's.

**Comment by HellscreamWoW** [comment]
ref #2235

**Comment by silverjade** [comment]
Might need to revisit this, I've been killing thugs all over the area and it's yet to drop.

**Comment by Guybrush-Hellscream** [comment]
I fixed the bandana loot in the actual quest, my bad! The item that starts the quest will soon be fixed as well.
