### ISSUE TITLE
[NPC] [Quest] Tarenar Sunstrike

### ISSUE THREAD

**Issue by carminejackal** [HellscreamWoW/Tracker#2953]
http://www.wowhead.com/npc=45429/tarenar-sunstrike
http://www.wowhead.com/quest=27370/tarenar-sunstrike

This npc is currently missing from Death's Step in Eastern Plaguelands. Thus you can't turn this quest in, nor get his follow up quests.

**Comment by Malae1** [comment]
Phased

**Comment by Malae1** [comment]
Fixed in next update
