### ISSUE TITLE
Missing armor vendors in Stormshield (Ashran)

### ISSUE THREAD

**Issue by Odysseas68** [HellscreamWoW/Tracker#2959]
In Stormshield, near the Auction House, there are 6 Arakkoa vendors that sell 630-675 ilvl armor. 3 of them only working and sell back, legs and hands armor.

[Dawn-Seeker Rilak](http://www.wowhead.com/npc=86387/dawn-seeker-rilak) exist but he didn't sell anything (Apexis Helm Trader)
[Dawn-Seeker Kasrek](http://www.wowhead.com/npc=92501/dawn-seeker-kasrek) is missing (Apexis Belt Trader)
[Dawn-Seeker Skelak](http://www.wowhead.com/npc=91321/dawn-seeker-skelak) also missing (Apexis Bracer Trader)

Also i want to notice that in Horde base all 6 vendors exist and working as they should.

**Comment by Malae1** [comment]
Fixed in next update
