### ISSUE TITLE
Guild Bank Tab

### ISSUE THREAD

**Issue by Kilrathe** [HellscreamWoW/Tracker#2960]
When trying to purchase a guild bank tab (first one to be honest) it doesn't work. I have tried on multiple occasions and days and have also tried restarting computer and game. I am the guild leader so that is not the issue and there is more than enough gold in the guild as well. I contacted a GM the day it happened and didn't hear anything back from him in game other than he was looking into it. Can you tell me where we stand on this issue and if it's just my account or others are having the issue as well? Thank you for all your time and efforts and all that you guys do to make this game more enjoyable and great.

**Comment by Guybrush-Hellscream** [comment]
Can you buy it with gold in your bags?

**Comment by Kilrathe** [comment]
I did not know it was with gold in my bags. I thought it was like the original WOW and you had to do it with guild bank money. I will try it later tonight and inform you of the results.

**Comment by Kilrathe** [comment]
It worked. Feel dumb now. Thanks for putting up with me. :)

**Comment by Guybrush-Hellscream** [comment]
Don't worry, glad it worked. :palm_tree:
