### ISSUE TITLE
Quest: Frost Nova in Sunstrider Isle

### ISSUE THREAD

**Issue by loefflefarn93** [HellscreamWoW/Tracker#2982]
Link: http://www.wowhead.com/quest=10068/frost-nova

In the task execution of the spell is not recognized.

**Comment by GMTyrial** [comment]
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/887

**Comment by Pure-Valhalla** [comment]
#4621 - combined all the class specific quests for this area together
