### ISSUE TITLE
Innkeepers

### ISSUE THREAD

**Issue by Diab24** [HellscreamWoW/Tracker#3001]
Hello

All innkeepers in some locations are bugged and cant choose any option, pls fix them as soon as you can.

Regards Diab.

**Comment by silverjade** [comment]
Please list the bugged Innkeepers so they can be fixed. The Dev's need to know names and locations so they can know who/where needs fixed.

**Comment by Guybrush-Hellscream** [comment]
Yes, please specify.

**Comment by Diab24** [comment]
Hello Devs

That would be a lot of work and i will maybe contact you once i lvl-ed up to max and found all bugged innkeepers.

Dear Diab

**Comment by Guybrush-Hellscream** [comment]
Fixed a bunch of those, write a new issue if you find more. :palm_tree:
