### ISSUE TITLE
[Dungeon] Razorfen Downs

### ISSUE THREAD

**Issue by Collector-Hellscream** [HellscreamWoW/Tracker#3009]
#2247
http://www.wowhead.com/zone=722/razorfen-downs

There is already some report for that dungeon however I am not able to enter it because well... there is no portal to enter it. I can just fly through the place where the entrence should be but nothing happens.

**Comment by Collector-Hellscream** [comment]
This issue can be closed. Portal is there where it should be and it is working.

**Comment by Guybrush-Hellscream** [comment]
#2468
