### ISSUE TITLE
Blood Elfs begginer quest bugged 

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#304]
The quest is called Solanian Belongings,and pretty much I have to pick up 3 different items, even though the items are spawned, I am not able to pick it up, I hope this can be fixed.

**Comment by Malae1** [comment]
Dev Note: Gameobject attachment needed http://www.wowhead.com/item=20470/solanians-scrying-orb http://www.wowhead.com/item=20471/scroll-of-scourge-magic http://www.wowhead.com/item=20472/solanians-journal

**Comment by Guybrush-Hellscream** [comment]
It's working. #2235
