### ISSUE TITLE
Who list bug

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#3042]
Issue: I think there is an issue with how many players it says are online, when clicking on refresh button in Who List Pane without having any zone typed for search, cuz it never says more than 50 players online, while I'm sure it's more than 50. I could be wrong though.

**Comment by silverjade** [comment]
That is the cap for the Who pane. It can't show more than 50.

**Comment by phikaro** [comment]
Oh ok, thanks for commenting, I'll close the issue then. =)
