### ISSUE TITLE
[Spell] Shadowmeld

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#3043]
Issue: When using with my night elf his skill "Shadowmeld" he gets PvP flagged, I think that's not normal.

http://www.wowhead.com/spell=58984/shadowmeld

**Comment by EPS1L0N** [comment]
note: only seems to happen in cities

**Comment by EPS1L0N** [comment]
ref #2266

**Comment by phikaro** [comment]
Nope it does not happen only in cities, I just tested it outside city in Elwynn Forest and Teldrsassil, it flagged me in PvP as soon as I use the spell.

**Comment by EPS1L0N** [comment]
woops, the fix for this got misplaced, we'll get it in next update. sorry!
