### ISSUE TITLE
Xmog Issue

### ISSUE THREAD

**Issue by zeefire05** [HellscreamWoW/Tracker#3049]
I just finished xmog some of my gears. When I entered an instance, it reversed back to my old xmog. Happened everytime since yesterday.

**Comment by THEplaguee** [comment]
Have you tried to re-equip your gear?

**Comment by zeefire05** [comment]
Yes.

**Comment by zeefire05** [comment]
Gold is spent but my xmog gears reverts back to previous xmog.
