### ISSUE TITLE
[Chat] Suggestion

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#3058]
Just a suggestion about the chat, how about making the items that you loot let's say you loot the same item many times, but instead of showing the same item one after another in chat, to show them all in one like the Moonpetal Lily, that I have gathered more than ones to show them as Moonpetal Lily x7 like on this screenshot:

http://store.picbg.net/pubpic/93/B4/fff06e13644193b4.jpg

It would save more space in chat window.

**Comment by Malae1** [comment]
I could be mistaken, but this sounds like an area loot feature piece.

**Comment by phikaro** [comment]
Yea something like that, not sure if this can be done on server side though.
