### ISSUE TITLE
[Spell] [Hunter] Revive Pet

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#3063]
Issue: This spell is changed as of 6.0.2, instead it now is called "Mend Pet". Basically what this means, is that if your pet is alive, the button will show "Mend Pet". But if your pet has died, that same button turns into "Revive Pet". Very useful, especially when you are in a tough battle, when you click the button, if the pet has just died, instead it will revive your pet.

Wowhead link: http://www.wowhead.com/spell=136/mend-pet

Wowhead link: http://www.wowhead.com/spell=982/revive-pet#comments

**Comment by Malae1** [comment]
Ref #1078

**Comment by phikaro** [comment]
Ah it has been reported already, I'll close this one then.
