### ISSUE TITLE
Howling Wind

### ISSUE THREAD

**Issue by danirzv** [HellscreamWoW/Tracker#3076]
drop rate of [Howling Wind] from "Dust Howler" is about 0, should be 12% !
http://www.wowhead.com/item=24504/howling-wind
http://www.wowhead.com/npc=17158/dust-howler

**Comment by Guybrush-Hellscream** [comment]
http://eu.battle.net/wow/en/item/24504 should be higher than 12%

**Comment by Guybrush-Hellscream** [comment]
Will be fixed in next update (NB : it should be higher than 12%, Wowhead rates are broken :palm_tree:)
