### ISSUE TITLE
Defensive Stance 

### ISSUE THREAD

**Issue by Adelpho** [HellscreamWoW/Tracker#3094]
While on Defensive Stance http://www.wowhead.com/spell=71 warriors don't generate rage with each melee hit dealt, making it impossible to use.

**Comment by EPS1L0N** [comment]
Defensive stance doesn't generate rage on melee hit. Battle stance does. Defensive stance generates rage every 3 seconds.

**Comment by EPS1L0N** [comment]
ref #2266
