### ISSUE TITLE
Untargetable mobs in Blasted Lands

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#3111]
It seems that these objects are aggroable like a hostile mob (which I don't believe it should) and are untargetable.

![wowscrnshot_102015_144628](https://cloud.githubusercontent.com/assets/12555606/10617608/6954de30-7739-11e5-9613-b18c3aef1f78.jpg)

**Comment by Malae1** [comment]
Fixed in next update
