### ISSUE TITLE
Important quests

### ISSUE THREAD

**Issue by sevike777** [HellscreamWoW/Tracker#3112]
Darkness Falls

The Battle of Thunder Pass

The Battle for Shattrath

And Justice for Thrall

Darkness Falls - http://www.wowhead.com/quest=33837/darkness-falls

The Battle of Thunder Pass - http://www.wowhead.com/quest=34124/the-battle-of-thunder-pass

The Battle for Shattrath - http://www.wowhead.com/quest=34099/the-battle-for-shattrath  AND  http://www.wowhead.com/quest=33731/the-battle-for-shattrath

And Justice for Thrall - http://www.wowhead.com/quest=35171/and-justice-for-thrall  AND  http://www.wowhead.com/quest=35169/and-justice-for-thrall

Please, just make these quests to playable, spawn the npcs and make that we can put up the quests instantly.

**Comment by Guybrush-Hellscream** [comment]
We don't do that, they'll be properly scripted.

**Comment by Guybrush-Hellscream** [comment]
#2608
