### ISSUE TITLE
Ability bugs for warrior Impending victory and a trinket

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#312]
"1.I have been traveling to the cape (by that time i got to lever 30)i chose a spec called Impending victory that replaces victory rush.Impending victory does half of the damage it shuld (the base one is for me 438) it does not heal and it does not reset when i kill a monster that yields exp.
2.The trinket inherited mark of tyranny does not increase my health for 15% it only increases health by 10 (not percent,points)
3.And just remembered this one thunder clap does half of the dmg."

**Comment by EPS1L0N** [comment]
ref #221 #223 #118

**Comment by EPS1L0N** [comment]
#2266
