### ISSUE TITLE
Stealth Glyph Bug

### ISSUE THREAD

**Issue by jenloe** [HellscreamWoW/Tracker#3138]
The rogue glyph of Stealth is suppose to make stealth have a 2 second cooldown it does do this but it very frequently resets to the 6 second cooldown and it requires you go log out and back in to fix it.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=63253/glyph-of-stealth

**Comment by Damvs** [comment]
When entering into an instance (or a teleport).

**Comment by Malae1** [comment]
Ref #1321
