### ISSUE TITLE
Dead NPC (Alanndarian Nightsong)

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3147]
She is a night elf NPC in Darkshore Region, within the Shatterspear War Camp. Lying dead on the ground and speaks to you and even gives you quests.
![wowscrnshot_102315_035021](https://cloud.githubusercontent.com/assets/15259298/10687216/50389f34-7939-11e5-8d0f-bb205cd24ed5.jpg)

**Comment by Guybrush-Hellscream** [comment]
https://www.youtube.com/watch?v=GAIlO1In3UY&feature=youtu.be
