### ISSUE TITLE
Merchant: Gorbold Steelhand 

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3149]
This dwarf merchant won't sell anything despite giving me the option, which I click. He is located in Darkshore within the village of Lor'danel.
![wowscrnshot_102315_043342](https://cloud.githubusercontent.com/assets/15259298/10688060/8d50c9ae-793f-11e5-8a46-c9cb61ee5596.jpg)

**Comment by Guybrush-Hellscream** [comment]
Will be fixed in next update.
