### ISSUE TITLE
Ferocious Bite

### ISSUE THREAD

**Issue by Jianxx24** [HellscreamWoW/Tracker#3167]
So, after 2015.24.10.020200 update, Ferocius Bite became bugged. When enemy's hp reaches 25% or below, Ferocious Bite should refresh the duration of Rip, but it's not refreshing. 

http://www.wowhead.com/spell=22568/ferocious-bite
http://www.wowhead.com/spell=1079/rip

**Comment by EPS1L0N** [comment]
thx for the report

**Comment by EPS1L0N** [comment]
#3209
