### ISSUE TITLE
Cant disenchant Cataclysm items

### ISSUE THREAD

**Issue by Yuu89** [HellscreamWoW/Tracker#3180]
Full inventory of items ( green/blue ) ilvl 289 - 333. If I try to disenchant something i get the error message "Must have a %s equipped".

**Comment by silverjade** [comment]
They have a fix for this coming soon, for now disenchant the item in the first slot of your backpack. It'll work there, you'll just need to move each item to that slot.

**Comment by Yuu89** [comment]
Ok thx.
Found out it works for every slot if i put the items in my bank before disenchanting them.
