### ISSUE TITLE
Cant skill fishing anymore

### ISSUE THREAD

**Issue by Yuu89** [HellscreamWoW/Tracker#3181]
Fishing skill moved up to 300, learned Master Fishing in Dalaran but the skill is stuck at 300/300 and now I cant go any higher.

**Comment by Malae1** [comment]
I may be able to assist with this in game, if you can PM me on the forum @ Malae1 that would be great.

**Comment by Malae1** [comment]
Reference for Developers, the only trainers that will allow fishing to be raised without bugging the fishing are the Faction capitals. Orgimmar and Stormwind for certain.
