### ISSUE TITLE
[Monk] dark kick

### ISSUE THREAD

**Issue by ricardoesl** [HellscreamWoW/Tracker#3182]
http://www.wowhead.com/spell=100784 excessive damage in pvp and pve lot more hits, as happened with Hunter powerful shot

[IMG]http://i61.tinypic.com/ek4k1.jpg[/IMG] I stick 80k damage with dark kick

**Comment by lloydbuckley** [comment]
This has apparently been fixed.  Both Jab and Blackout Kick (the only working DPS spells for the class) now hit for significantly less damage than previously.  Jab hits for 700-800.  Blackout Kick hits for 7000-8000.  Expel Heal, the only working heal, heals for about 12k.
