### ISSUE TITLE
[Rogue]Lockpicking

### ISSUE THREAD

**Issue by Aveta** [HellscreamWoW/Tracker#3185]
http://www.wowhead.com/spell=1804/pick-lock
Apparently with one of the latest patches Lockpicking got broken. Now when trying to open any lockbox red text "Must have a %s equipped" appears and you can't open them.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=1804/pick-lock

**Comment by Aveta** [comment]
Seems like it was fixed with the recent update that also fixed Prospecting etc. : )
