### ISSUE TITLE
[Loot] Buggy rate

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#3187]
Issue: I noticed that when playing at the starting zone of night elf, I get some random higher than normal drops from mobs, for example the grell mobs gave me two items that are not supposed to be dropped by such  mobs, here's a screenshot of the items they dropped:

http://store.picbg.net/pubpic/A3/A5/809191a2b716a3a5.jpg

And I have been looting from other mobs armor for example, which I do not get while playing on retail's starting zone.

http://www.wowhead.com/item=53069/murglesnout

http://www.wowhead.com/item=53068/lavascale-catfish

**Comment by Tregeta** [comment]
fixed in next update
