### ISSUE TITLE
[archaeology] Dig Sites

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#3190]
Issue: The Dig sites for archaeology are always in same place, shouldn't they be changing randomly each week?

**Comment by phikaro** [comment]
Update: I think it works as it should, dig sites change spawn when I have they fully done.

**Comment by Guybrush-Hellscream** [comment]
Alright, i'll close it up. Comment here again in case that changed. :palm_tree:

**Comment by zwei7** [comment]
The dig site in Nazj'vel in Dark Shore had me find an artifact 3 times in the same place consecutively.
