### ISSUE TITLE
Config resets on server restart/crash

### ISSUE THREAD

**Issue by jenloe** [HellscreamWoW/Tracker#3200]
If the server restarts or crashes the custom configuration of peoples ui will go to a default state. I have asked many people about this and they have the same problem. I have provided screen shots of this event.
![wowscrnshot_102515_114817](https://cloud.githubusercontent.com/assets/15249869/10716961/178b5ca0-7b17-11e5-9ad3-d090e93c9857.jpg)
![wowscrnshot_102515_124241](https://cloud.githubusercontent.com/assets/15249869/10716962/19111330-7b17-11e5-8c56-43c2e963ff90.jpg)

**Comment by jenloe** [comment]
The first picture is before the restart the second picture is after the restart.

**Comment by EPS1L0N** [comment]
happens on blizz aswell, you have to log out (to char screen) for interface options to save, people just dont notice it on blizz cause they rarely restart and almost never crash
