### ISSUE TITLE
Grizzly Flank

### ISSUE THREAD

**Issue by danirzv** [HellscreamWoW/Tracker#3216]
drop rate of [Grizzly Flank] from "Grizzly Bear" should be 23%
i killed 20 grizzly bear, droped only 1x[Grizzly Flank]
please fix drop rates!

**Comment by Guybrush-Hellscream** [comment]
It'll be fixed soon.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/quest=12216/take-their-rear

**Comment by Malae1** [comment]
Fixed in Next update
