### ISSUE TITLE
The Deserters (quest) 

### ISSUE THREAD

**Issue by Lazyg33k** [HellscreamWoW/Tracker#3238]
Hi i got this bug i almost kill the mob he surender but after i keep be in combat stance and he not ttelling me anything and now he follow me everywhere look into my print screen !

http://www.wowhead.com/quest=27287/the-deserters

![bug teramore](https://cloud.githubusercontent.com/assets/15207677/10768748/009173ba-7cb9-11e5-88aa-f9d0ee783f65.jpg)

**Comment by zwei7** [comment]
I killed all the mobs around that tower and I don't have anyone telling me anything. Not even a person following me around as mentioned in above comment.

**Comment by GMTyrial** [comment]
Duplicate https://github.com/HellscreamWoW/Tracker/issues/1728
