### ISSUE TITLE
Aroom's Farewell

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3251]
The Wildkin Spirit mobs are not dropping the quest item (Slain Wildkin Feather). I have killed 20-30 of them around the Aroom's cave and nothing. The Wildkin in question in the screenshot below:
![wowscrnshot_102715_201551](https://cloud.githubusercontent.com/assets/15259298/10776430/a8f75c12-7ce7-11e5-973c-f05291cd33dc.jpg)

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/quest=13578/arooms-farewell

**Comment by Malae1** [comment]
The creatures do not drop them, they are gameobjects.

**Comment by zwei7** [comment]
sorry.
