### ISSUE TITLE
Talents after changing area

### ISSUE THREAD

**Issue by Collector-Hellscream** [HellscreamWoW/Tracker#3271]
http://www.wowhead.com/spell=118675/crouching-tiger-hidden-chimaera

Talents that reduse cooldown of some abilities (like hunter talent above) somehow "reset/unlearn" after changing area with loading screen. 
For example having that talent I have 10 sec cooldown on Disengage ability but when I go through portal to Pandaria it goes back to 20 sec and only way to fix it is to relog.

**Comment by Malae1** [comment]
#3375 , #1321
