### ISSUE TITLE
[entropic ooze]

### ISSUE THREAD

**Issue by danirzv** [HellscreamWoW/Tracker#3296]
Drop rate of an item named [Slime Sample] from "Entropic Ooze" is too low.
http://www.wowhead.com/item=37199
http://www.wowhead.com/npc=26366/entropic-ooze

**Comment by Guybrush-Hellscream** [comment]
Alliance: http://www.wowhead.com/quest=12219/the-failed-world-tree
Horde: http://www.wowhead.com/quest=12207/vordrassils-fall

**Comment by Malae1** [comment]
Fixed in next update
