### ISSUE TITLE
Quest: Orendil's Cure

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3304]
This quest is automatically completed as soon as you accept it from the NPC shown below. You are supposed to deliver the quest item to Astranaar.

![wowscrnshot_102915_160648](https://cloud.githubusercontent.com/assets/15259298/10830665/472b3a78-7e57-11e5-88f2-9f2a0cc8c2c0.jpg)

**Comment by Guybrush-Hellscream** [comment]
This is normal since you just have to deliver an item to a guy. Delivering quests are auto-completed.
https://www.youtube.com/watch?v=PJFsnkszYmo&feature=youtu.be

**Comment by zwei7** [comment]
sorry my bad
