### ISSUE TITLE
Quest: Dartol's Rod

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3308]
This quest is automatically complete as soon as you click accept from this NPC.
![wowscrnshot_102915_164115](https://cloud.githubusercontent.com/assets/15259298/10831410/e2bd9e28-7e5b-11e5-9ad5-4380d9c40428.jpg)

**Comment by Guybrush-Hellscream** [comment]
Same as the other one! 
Retail video https://www.youtube.com/watch?v=ElfGIVp0vwE&feature=youtu.be
