### ISSUE TITLE
Quest: Dryad Delivery

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3309]
This quest is automatically completed as soon as you click accept from this NPC.
![wowscrnshot_102915_164341](https://cloud.githubusercontent.com/assets/15259298/10831489/50ad6774-7e5c-11e5-95d9-8fdcf85abe0b.jpg)

**Comment by Guybrush-Hellscream** [comment]
https://www.youtube.com/watch?v=mhBQhTQVOO8&feature=youtu.be
