### ISSUE TITLE
Quest Giver: Vindicator Palanaar

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3314]
In Astranaar Village, this NPC does not have the Giant yellow exclamation mark that indicates she has a quest.
![wowscrnshot_102915_180043](https://cloud.githubusercontent.com/assets/15259298/10833282/1bf7152e-7e67-11e5-9973-708a20209d3a.jpg)

**Comment by Guybrush-Hellscream** [comment]
Quest is level 21, requires level 19 and you're 27. It means that it's probably too low for you to see the exclamation mark. Try to turn on the low level quests (magnifying glass around the minimap).
