### ISSUE TITLE
Quest: A Helping Hand

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3315]
http://www.wowhead.com/quest=26453/a-helping-hand

This quest automatically completes as soon as you click accept.
![wowscrnshot_102915_180340](https://cloud.githubusercontent.com/assets/15259298/10833353/a0e056f6-7e67-11e5-95cf-04fb551b84a9.jpg)

**Comment by Guybrush-Hellscream** [comment]
https://www.youtube.com/watch?v=qreFBOtQLsg&feature=youtu.be same as delivering quests.
