### ISSUE TITLE
Quest: Three Friends of the Forest

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3317]
This quest is automatically completed when you click accept. Work should be required!
![wowscrnshot_102915_184750](https://cloud.githubusercontent.com/assets/15259298/10834250/1c39f234-7e6e-11e5-8321-e1ec6071fd88.jpg)

**Comment by Guybrush-Hellscream** [comment]
https://www.youtube.com/watch?v=65cMVpVNxbw&feature=youtu.be
