### ISSUE TITLE
Quest: Do Yourself a Favor

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3318]
Quest is automatically completed as soon as you click accept.
![wowscrnshot_102915_191751](https://cloud.githubusercontent.com/assets/15259298/10834700/eef9e758-7e71-11e5-9c53-de8c7a891d96.jpg)
![wowscrnshot_102915_191759](https://cloud.githubusercontent.com/assets/15259298/10834699/eef99db6-7e71-11e5-8dca-e2cd1cff12e2.jpg)

**Comment by Guybrush-Hellscream** [comment]
https://www.youtube.com/watch?v=yIuRh_7GBxs&feature=youtu.be
