### ISSUE TITLE
Quest: Bombs Away: Windshear Mine

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3319]
Quest automatically completes when you click accept.
![wowscrnshot_102915_192131](https://cloud.githubusercontent.com/assets/15259298/10834748/71e09392-7e72-11e5-80f3-2c86128fb215.jpg)
![wowscrnshot_102915_192133](https://cloud.githubusercontent.com/assets/15259298/10834763/9bad7fdc-7e72-11e5-9187-5fedb40761ea.jpg)

**Comment by Guybrush-Hellscream** [comment]
https://www.youtube.com/watch?v=lUNhUbBzizA&feature=youtu.be
