### ISSUE TITLE
Quest: Rebels without a Clue

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3320]
Quest automatically completes upon clicking accept.
![wowscrnshot_102915_192750](https://cloud.githubusercontent.com/assets/15259298/10834844/4b252f64-7e73-11e5-97be-36006e7fe168.jpg)
![Uploading WoWScrnShot_102915_192805.jpg…]()

**Comment by Guybrush-Hellscream** [comment]
https://www.youtube.com/watch?v=JGAQCyt6fj8&feature=youtu.be
