### ISSUE TITLE
 [Reunited]

### ISSUE THREAD

**Issue by danirzv** [HellscreamWoW/Tracker#3339]
quest  [Reunited] will not complete when you go on the tour of zul drak.
http://www.wowhead.com/quest=12663/reunited

**Comment by silverjade** [comment]
I did this quest just today. It completed for me.

**Comment by danirzv** [comment]
you sit on a npc, it goes around and give you a tour!
when it finished th quest task did not compeleted :(

**Comment by silverjade** [comment]
Were you in the disguise? I clicked on the npc, asked it to give me a tour and did nothing as it did the tour (remaining in disguise the whole route) and upon return it gave me credit.
