### ISSUE TITLE
Auction house

### ISSUE THREAD

**Issue by RadioActiveSoul** [HellscreamWoW/Tracker#3341]
The auction house is removing more gold for posting auctions then what it says... for example..
Deposit 12 silver to start an auction of an item. And it ends up removing more then those 12 silver. It removes 1 gold and some silver. Something is clearly wrong with the creation of auctions. Scripts? Maybe?

**Comment by Guybrush-Hellscream** [comment]
https://github.com/HellscreamWoW/Tracker/issues/2387 we already know about that, it's 5 times more expansive than the usual deposit.
