### ISSUE TITLE
Wailing Feeds dont give exp. anymore

### ISSUE THREAD

**Issue by StaySmart** [HellscreamWoW/Tracker#3344]
Wailing Feeds in Mount Hyjal are bugged somehow they dont give exp. anymore. Lots of quest in Mount Hyjal are bugged but that was only way to leveling kill those Wailing Feeds and those are bugged now

**Comment by Guybrush-Hellscream** [comment]
According to retail, they shouldn't have given xp in the first place. 
I invite you to follow Silverjade guides : 
Alliance > http://www.hellscream-wow.com/forum/viewtopic.php?f=27&t=1946
Horde > http://www.hellscream-wow.com/forum/viewtopic.php?f=27&t=1782
