### ISSUE TITLE
[Error] Webwinder Path

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#3345]
Issue: While walking around in Webwinder Path (Zone: Stonetalon Mountains), my game crashed, it has happened only once, but I thought to send the error files, might help the server get better.

Error Files: http://www81.zippyshare.com/v/dqZqQFZH/file.html

Link: http://wow.gamepedia.com/Webwinder_Path

**Comment by Guybrush-Hellscream** [comment]
Thanks for the info.
