### ISSUE TITLE
Dwarven Ram seller in Dun Mororgh

### ISSUE THREAD

**Issue by Rames312** [HellscreamWoW/Tracker#3382]
So this guy - Veron Amberstill - is supposed to provide shop with Rams and a quest - Which isnt working too -"Ram one the Lam" - but he only provides the quest and you cant buy mounts.

**Comment by Malae1** [comment]
Just checked and confirmed working:
![Vendor Option](http://i.imgur.com/n36wecL.jpg)
![Vendor Open](http://i.imgur.com/n1dUtiK.jpg)

Best option, clear your cache in your WoW directory.
