### ISSUE TITLE
Quest Bug: Onslaught's End

### ISSUE THREAD

**Issue by Hemsly** [HellscreamWoW/Tracker#3383]
The door to disable the northern fell spire is locked and can't be opened.

**Comment by HellscreamWoW** [comment]
You need to get close to one of the dwarfs standing next to what looks like Dynamite plungers. They will blow up the door and grant you access to spire. Their names are Hansel and Thalen.

**Comment by Hemsly** [comment]
They didn't blow up the first door. I had to open the left manually.
