### ISSUE TITLE
MOB bug: Emerald Spirit 

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3385]
This green owl is buggy. Some will appear look normal like a flying owl with full hand some will appear as a corpse with full hp. Then when you walk up to them and in range to shoot an arrow at them, it says it is too far away, even though you are 10 feet away, pretty sure hunters can shoot 40 feet. This occurs for the buggy corpse owls and the normal flying ones. Clearly in the belowp screenshot I am not out of range, yet it says so
![wowscrnshot_103115_140144](https://cloud.githubusercontent.com/assets/15259298/10865132/094183de-7fd8-11e5-9109-d47b0e588e1b.jpg)
.
Here is a buggy corpse owl with full HP
![wowscrnshot_103115_134146](https://cloud.githubusercontent.com/assets/15259298/10865085/09eef7ea-7fd7-11e5-98f8-64e6272823e7.jpg)

When you attack a corpse owl, from 5 feet away, it comes to life and starts attacking normally. Flying ones will attack as well. Then when you kill any owl, it may die and teleport its corpse 2- 5 meters up in the air making it unlootable.
![wowscrnshot_103115_134133](https://cloud.githubusercontent.com/assets/15259298/10865087/1db07628-7fd7-11e5-8a48-ce02282259ce.jpg)

Then there is one owl inside the pond, you can see its green wings popping out of the water.
![wowscrnshot_103115_134342](https://cloud.githubusercontent.com/assets/15259298/10865099/6100aa88-7fd7-11e5-8f0b-f88969934889.jpg)

**Comment by Malae1** [comment]
Fixed in next update
