### ISSUE TITLE
MOB bug: Kalimdor Eagle

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3389]
When you kill this eagle, it will sometimes die 1-2 meters up in the air instead of falling to the ground. Then it may be still mid air or its corpse will bob up and down in the air. Unlootable if it is up that high

Bobbing up
![wowscrnshot_103115_141750](https://cloud.githubusercontent.com/assets/15259298/10865195/651a7fb0-7fda-11e5-9aac-9243fe4ca9f6.jpg)
Bobbing down
![wowscrnshot_103115_141749](https://cloud.githubusercontent.com/assets/15259298/10865196/6685260c-7fda-11e5-8673-f5b782563741.jpg)

On another note. Here is one inside a tree. Alive.
![wowscrnshot_103115_142635](https://cloud.githubusercontent.com/assets/15259298/10865227/74377286-7fdb-11e5-9236-b323ae73c23f.jpg)

**Comment by Malae1** [comment]
Fixed in next update
