### ISSUE TITLE
MOB bug: Invincible, Untargetable, attacking corpse

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3390]
This Wyvern corpse is attacking me and I can't target it, no matter how many times I click, to kill it.

![wowscrnshot_103115_142425](https://cloud.githubusercontent.com/assets/15259298/10865234/a000ed7a-7fdb-11e5-8e1b-8de1f6370b82.jpg)

**Comment by Malae1** [comment]
Fixed in next update
