### ISSUE TITLE
Monk animations

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#340]
"Hi my monk only have the fist animation, and he uses it no matter of what weapon i am holding.
Jab animation and picture dosen't change if i change weapon it stays on the fist.
* And plz fix the blackout kick it is the main spell for windwalkers and its hard to lvl without it :D. It does only 1-2 dmg some1 reported it earlier."

**Comment by Max-Hellscream** [comment]
The Monk having the fist animation, no matter what weapon you're holding, is working as intend. This is how Monks are on retail. Blackout kick is bugged though, so the issue will remain open.

**Comment by Malae1** [comment]
http://www.hellscream-wow.com/log#2015.6.06.010536
