### ISSUE TITLE
Hunter: Kill shot

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3409]
The kill shot spell has a gian yellow text indicator telling you when you can use it (when enemy has 20% health). However after I kill an enemy, no matter if I use kill shot or not, I go up to loot it. Upon selecting an enemy to loot, the giant kill shot yellow text appears again. It shouldn't.
![wowscrnshot_110115_025858](https://cloud.githubusercontent.com/assets/15259298/10867831/6f6660ae-8045-11e5-8b5f-7b21fa884060.jpg)

**Comment by EPS1L0N** [comment]
it should.
