### ISSUE TITLE
Quest Giver: Elunes Brazier

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3411]
This Object gives quests. I also appear to have a satyr inside of it. Notice the brown legs sticking out.
![wowscrnshot_110115_035612](https://cloud.githubusercontent.com/assets/15259298/10868024/81b9eae2-804e-11e5-8c79-1b7b032f6e0a.jpg)

These are the quests given. Notice the quest "Ten Pounds of Flesh" is written twice. You can actually accept 2 quests that are identical.
![wowscrnshot_110115_035525](https://cloud.githubusercontent.com/assets/15259298/10868030/b4638b92-804e-11e5-8ea7-8abb9b79df00.jpg)

The following is the text of all 4 quests.
![wowscrnshot_110115_035528](https://cloud.githubusercontent.com/assets/15259298/10868053/9978a3c0-804f-11e5-9d69-fe110fd3b374.jpg)
![wowscrnshot_110115_035531](https://cloud.githubusercontent.com/assets/15259298/10868052/99788854-804f-11e5-9493-88579c092fbd.jpg)
![wowscrnshot_110115_035534](https://cloud.githubusercontent.com/assets/15259298/10868054/997bf188-804f-11e5-9410-3bec17eddd0f.jpg)
![wowscrnshot_110115_035539](https://cloud.githubusercontent.com/assets/15259298/10868055/997ec084-804f-11e5-98ea-71ebd9a9b867.jpg)

**Comment by Malae1** [comment]
Wasn't able to see those legs you spoke about, the issue is now resolved.
