### ISSUE TITLE
Quest: Blessings from above

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3421]
Can't collect satyr flesh. They don't drop from the satyrs. http://www.wowhead.com/item=48857/satyr-flesh

![wowscrnshot_110115_135039](https://cloud.githubusercontent.com/assets/15259298/10870727/bbaa5506-809f-11e5-8191-9936ed8ee723.jpg)

**Comment by Malae1** [comment]
Fixed in next update
