### ISSUE TITLE
MOB bug: Untargetable Infernal (Desolace)

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3435]
Can't attack this Lessor Infernal in Desolace. 
![wowscrnshot_110115_173111](https://cloud.githubusercontent.com/assets/15259298/10871782/b6cecfde-80be-11e5-8de3-55dd7f04ce8f.jpg)
Even rarer, some lesser infernals are invisible. I only noticed the invisible ones that my pet was attacking, I could only target it with the tab key and help kill it.

**Comment by Malae1** [comment]
Ref #2394

**Comment by Malae1** [comment]
Fixed in next update
