### ISSUE TITLE
Quest: Urgent delivery

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3452]
I handed it in to the NPC below and didn't get exp, money, or items. I can't hand it in again either. Now all I see is shown in the screenshot below. I can talk to the NPC but I don't see a hand in quest option to remove the hand in indicator "?".
![wowscrnshot_110315_010232](https://cloud.githubusercontent.com/assets/15259298/10902080/d7d4ab6e-81c6-11e5-9119-7360f090b82e.jpg)

**Comment by Nimes-Hellscream** [comment]
http://www.wowhead.com/quest=9671/urgent-delivery

**Comment by Malae1** [comment]
https://www.youtube.com/watch?v=pt2c_IO-dkg&feature=youtu.be Quest does not award xp, items, or money.

**Comment by zwei7** [comment]
Okay no rewards got it. However the screenshot shows what I see after I handed in the quest. Therefore there should be no more yellow  "?" indicator above the NPC.
