### ISSUE TITLE
MOB bug: Tzerak

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3453]
This boss mob spawns twice.  Below are the two looking at each other.
![wowscrnshot_110315_013355](https://cloud.githubusercontent.com/assets/15259298/10902380/082cfb5a-81cb-11e5-91fe-7c9e37646d03.jpg)
![wowscrnshot_110315_013358](https://cloud.githubusercontent.com/assets/15259298/10902381/082e5bd0-81cb-11e5-8b92-de9f5d232e87.jpg)

**Comment by Nimes-Hellscream** [comment]
http://www.wowhead.com/npc=17528/tzerak
