### ISSUE TITLE
Druid spell: Revive

### ISSUE THREAD

**Issue by Djurdjevdan** [HellscreamWoW/Tracker#3454]
It has it's animation and it costs mana, but it simply isn't reviving.

**Comment by EPS1L0N** [comment]
![Revive](http://puu.sh/l7LX5/7d3b578812.jpg)
Couldn't reproduce, do you have any more info on when it happens?

**Comment by Djurdjevdan** [comment]
Hm....well i noticed this last week or 2 in nexus (was lazy in posting it). I was the last survivor and i ahd to rezz 2 teammates near me. I did rebirth and it did well. However i constantly did revive over and over again and never rezzed that target. I'm not sure why, but i doubt someone qould constantly declane rezz. It is probably fixed by the time i posted this issue. If that's the case then this treat is useless.

**Comment by Djurdjevdan** [comment]
Just tested today and revive worked. Sorry for giving you false bugs.
