### ISSUE TITLE
Rogue Talent Bug:Dirty Tricks

### ISSUE THREAD

**Issue by jenloe** [HellscreamWoW/Tracker#3455]
The rogue talent Dirty Tricks is suppose to make gouge and blind cost no energy it does this until you load a new area after that gouge and blind require energy to cast. I will provide examples.
![wowscrnshot_110315_093542](https://cloud.githubusercontent.com/assets/15249869/10912543/9bd5df9a-820f-11e5-8807-efbb42b1c627.jpg)
![wowscrnshot_110315_093546](https://cloud.githubusercontent.com/assets/15249869/10912546/a30848de-820f-11e5-96bd-0003b5582aa6.jpg)

![wowscrnshot_110315_093540](https://cloud.githubusercontent.com/assets/15249869/10912536/9266512e-820f-11e5-87b7-27886f05d732.jpg)

**Comment by Malae1** [comment]
Ref #2266

**Comment by Malae1** [comment]
Ref #2266
