### ISSUE TITLE
[Feralas] [NPC] Kylanna Windwhisper, Xylinnia Starshine, Brannock & Karonas

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#3463]
Issue: The first 3 NPCs are trainers and do not offer their services when talking to them, no dialog window opens, only Xylinnia Starshine has a dialog window, but is empty with a simple text.

http://www.wowhead.com/npc=7948/kylanna-windwhisper  - alc

http://www.wowhead.com/npc=7949/xylinnia-starshine  - ench

http://www.wowhead.com/npc=7946/brannock  -  fishing

**Comment by Nimes-Hellscream** [comment]
Karonas - http://www.wowhead.com/npc=40036/karonas
Kylanna is an alchemy trainer
Xylinna is an enchanting trainer
Brannock is a fishing tranier
