### ISSUE TITLE
[NPC] Sansha MacVince "Riding Trainer"

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#3465]
Issue: When talking to this npc, it does not open any dialog window.

Link: http://www.wowhead.com/npc=53407/sansha-macvince

**Comment by Nimes-Hellscream** [comment]
FYI - I'm on Horde side, but as of right now, it appears that you can only train riding in Orgimmar. So, I am guessing that it would be Stormwind for the Alliance.

**Comment by phikaro** [comment]
Nope, I also have been able to learn riding from my night elf Capital City Darnassus. But in Stormwind does work as well. That is the first riding trainer I come across that does not work.
