### ISSUE TITLE
[NPC] Caz Twosprocket "Engineering Trainer" & Marie Holdston "Blacksmithing Trainer"

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#3467]
Issue: The npc  "Caz Twosprocket" (Engineering Trainer) does not offer training in his dialog window, and "Marie Holdston" (Blacksmithing Trainer) is having wrong interface for training, here's how is here and how it's on retail:

HellscreamWoW:
![wowscrnshot_110515_001403](https://cloud.githubusercontent.com/assets/12748693/10953882/1802d912-8353-11e5-813d-b32d59f3cdc6.jpg)

Retail:

![349238](https://cloud.githubusercontent.com/assets/12748693/10953922/4e169f84-8353-11e5-8f27-49bcdbb68fb5.jpg)

Caz Twosprocket: http://www.wowhead.com/npc=4941/caz-twosprocket

Marie Holdston: http://www.wowhead.com/npc=4888/marie-holdston

**Comment by Malae1** [comment]
You linked two entirely different NPCs.

You have Cullen Hammerbrow in your second photo.

**Comment by phikaro** [comment]
It doesn't matter, the Engineering Trainer profession interface is the same for any npc, that's why I did not show the exact same npc.

**Comment by Malae1** [comment]
It does matter, you opened the issue for this particular NPC but are showing us an entirely different one from retail, especially one from Pandaria where they have specific NEW recipes for fast leveling.

**Comment by phikaro** [comment]
Here it is now from retail vs HellscreamWoW same npcs:
HellscreamWoW:
![1802d912-8353-11e5-813d-b32d59f3cdc6](https://cloud.githubusercontent.com/assets/12748693/11017630/bf19fa6c-85ad-11e5-9408-20de09ce20d7.jpg)

Retail:
![wowscrnshot_110815_000549](https://cloud.githubusercontent.com/assets/12748693/11017633/cfe550ee-85ad-11e5-9674-9549ccb82842.jpg)

**Comment by Malae1** [comment]
Looks exactly the same, aside from the level bar, that is your ui.

**Comment by phikaro** [comment]
Lol yea, I got myself confused from the addon difference, anyway ignore this report then.
