### ISSUE TITLE
this quest it doesn't work 

### ISSUE THREAD

**Issue by jareck77** [HellscreamWoW/Tracker#3485]
Quick Facts
Level: 39
Requires level 36
Loremaster: Dustwallow Marsh
Side: Both
Start: Brogg
End: Brogg
Not sharable
Difficulty: 36  37  42  48
Added in patch 4.0.3

Name of the quest: Challenge to the Black Flight
http://www.wowhead.com/quest=27411/challenge-to-the-black-flight

**Comment by Malae1** [comment]
Not enough information, How does it not? Update your Original.

**Comment by Collector-Hellscream** [comment]
I think that banner is not usable even when you stand near entrence to Onyxia's Lair.
