### ISSUE TITLE
[Quest] Challenge to the Black Flight

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#3495]
http://www.wowhead.com/quest=27411/challenge-to-the-black-flight

When using the quest object Stonemaul Banner, a message "Requires Entrance to Onyxia's Lair" appears, despite the item being used on the designated quest location.

**Comment by Malae1** [comment]
Ref #3485

**Comment by zwei7** [comment]
Same problem.
![wowscrnshot_111515_223028](https://cloud.githubusercontent.com/assets/15259298/11173781/9d6a475a-8be8-11e5-8f74-5576b18bfed6.jpg)

**Comment by GMTyrial** [comment]
Already known https://github.com/HellscreamWoW/Tracker/issues/356
