### ISSUE TITLE
Muckgill's Flipper or Something...

### ISSUE THREAD

**Issue by majinonifox1** [HellscreamWoW/Tracker#3531]
A mob in Hillsbrad Foothills, Muckgill, is supposed to drop an item: Muckgill's Flipper. This allows for the start of a quest: 'Muckgill's Flipper or Something...' Currently, Muckgill does not drop the item. Have killed several times, no drop.
Relevant Quest info: http://www.wowhead.com/quest=28154/muckgills-flipper-or-something

**Comment by Malae1** [comment]
Fixed in next update
