### ISSUE TITLE
Badge of Justice drops

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#3540]
http://www.wowhead.com/npc=16152/attumen-the-huntsman

Now I only tried it with Attumen the Huntsman but I have a feeling it might be a more server wide issue. I had a Badge of Justice drop which is, apparently automatically convert to gold which it didn't in this case.

http://wowwiki.wikia.com/wiki/Badge_of_Justice

**Comment by Aveta** [comment]
It appears to be a thing with Stone Keeper's Shards as well.

**Comment by Tregeta** [comment]
fixed next update

**Comment by GeneralCaveman** [comment]
Will it hit the update after todays because it is not fixed as of right now.

**Comment by Tregeta** [comment]
Yes
