### ISSUE TITLE
[Rogue] Eviscerate

### ISSUE THREAD

**Issue by Aveta** [HellscreamWoW/Tracker#3563]
http://www.wowhead.com/spell=2098/eviscerate
Eviscerate appears to do 10 times the damage it's supposed to deal. No matter if it's legacy content or not.
![wowscrnshot_111315_230145](https://cloud.githubusercontent.com/assets/14302942/11158829/1d8f2e44-8a5b-11e5-8cf0-e321d5112ea2.jpg)
![wowscrnshot_111315_231056](https://cloud.githubusercontent.com/assets/14302942/11159359/0fb24726-8a5f-11e5-8502-c663e5b3284f.jpg)
(my recount was reset, but i mostly wanted to show the particular spikes of dmg and i had a dc between those two)

**Comment by Malae1** [comment]
Did you test this on actual creatures and not the training dummy? The photo above suggest it is only the training dummy.

**Comment by Aveta** [comment]
Yes, I swapped to Combat during farming Firelands and was quite suprised seeing how all spells did between 6-10k, then Eviscerate up to 150k (when critting)
I'll go to Draenor and insert a screenshot there if the behavior of Eviscerate is the same.
My boyfriend also mentioned a rogue dueling with him and hitting him for half his HP (which is bit below 200k), something that makes me suspicious if it wasn't an Eviscerate.

**Comment by Aveta** [comment]
Just as I suspected it would be. At the end tooltip for comparison. It's actually 5 times more than supposed to be, still pretty darn brutal.
![wowscrnshot_111415_121417](https://cloud.githubusercontent.com/assets/14302942/11163329/1ec591c0-8acb-11e5-8589-cd2cc77a60c8.jpg)
![wowscrnshot_111415_121700](https://cloud.githubusercontent.com/assets/14302942/11163326/1ebeb0e4-8acb-11e5-99b9-e1f74fc95e4a.jpg)
![wowscrnshot_111415_121931](https://cloud.githubusercontent.com/assets/14302942/11163331/1ecb4e3a-8acb-11e5-841c-943c5a20e5b4.jpg)
![wowscrnshot_111415_122000](https://cloud.githubusercontent.com/assets/14302942/11163330/1eca5cb4-8acb-11e5-8596-5c8ae025f77e.jpg)
![wowscrnshot_111415_122144](https://cloud.githubusercontent.com/assets/14302942/11163328/1ec0d4c8-8acb-11e5-87e7-c2d53635ea8d.jpg)
![wowscrnshot_111415_122524](https://cloud.githubusercontent.com/assets/14302942/11163327/1ec097ba-8acb-11e5-8013-9cb408eed5ae.jpg)

**Comment by kupidons** [comment]
revealing strikes +35% dmg, bandits guile +50% dmg and from what i played ( i have a rogue ) those big numbers are crits so +200% dmg. well formula is mb wrong, dunno about pvp. but it's funny that when i pve 99 rogue with same lvl mobs i hit them 8k, they hit me 20k :D

**Comment by kupidons** [comment]
pray of weak also can be factor

**Comment by kupidons** [comment]
now in nax :D sinister strike 30k crits, eviscerate 600k crits

**Comment by kupidons** [comment]
http://www.bildites.lv/viewer.php?file=0ruyfjwlzelicclrkajn.jpg
http://www.bildites.lv/viewer.php?file=6icvp249kg3pb3c85i7.jpg
http://www.bildites.lv/viewer.php?file=ubo5w89nb15bswetkqa.jpg
doing naxx raid

**Comment by Aveta** [comment]
My rogue is level 100 with pretty solid gear. Bandit's Guile doesn't work at all. Only modifier would be Revealing Strike.
Since someone already "discovered" it for PVP, it should be fixed asap.

**Comment by EPS1L0N** [comment]
retest this after our next update if you would please

**Comment by Aveta** [comment]
Sure thing.

**Comment by Aveta** [comment]
Bug was fixed in this update.

**Comment by EPS1L0N** [comment]
cheers

**Comment by EPS1L0N** [comment]
#2266
