### ISSUE TITLE
MOB: Desolation Wind Rider

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3568]
I can't attack this MOB even though I am right next to it and it says out of range. Below is my location and the MOB in question. This mob is targetable and just stands there flapping its wings.
![wowscrnshot_111415_043842](https://cloud.githubusercontent.com/assets/15259298/11162959/e6911da6-8a89-11e5-8cbf-86cfda0f3966.jpg)
![wowscrnshot_111415_043848](https://cloud.githubusercontent.com/assets/15259298/11162960/e691a064-8a89-11e5-9289-b39e6e1603fa.jpg)

In another encounter within the Southern Barren, I have been attacked the same type of MOB. It was  in a different location within the zone and it fell from the sky to attack me. I never even aggroed it. Perhaps this MOB is supposed to be in the sky and that would be the reason it says out of range. Yet the game draws this MOB on the ground.

The same mobs in Battlescar also do not aggro you, just flap and stay still. However you can attack them without the out of range bug.
![wowscrnshot_111415_111855](https://cloud.githubusercontent.com/assets/15259298/11164536/b9826850-8ac1-11e5-83ba-fc8b8aa62be0.jpg)

**Comment by KwitUrBichn** [comment]
http://www.wowhead.com/npc=37974/desolation-wind-rider

**Comment by Malae1** [comment]
Fixed in next update
