### ISSUE TITLE
Seal of Command not applying

### ISSUE THREAD

**Issue by Swadian** [HellscreamWoW/Tracker#3594]
Whenever I activate Seal of Command I don't get the buff but the hotbar say's it's active and I can't "De-activate it"
Tested on two different characters.Whenever I activate the seal for the first time it gets bugged again.

**Comment by Malae1** [comment]
What is your current level?

**Comment by Swadian** [comment]
At the moment both char's are deleted.First one I went untill level 5 and the second one I deleted at level 3 after finding out the issue persisted

**Comment by Malae1** [comment]
You are not meant to be able to de-activate it until you get another seal. Further the buff is an invisible aura even on retail now, it's working as intended.
