### ISSUE TITLE
MOB: Gilnean Crow 

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3631]
The neutral crows in Gilneas are standing in mid air. They should be on the ground, not hovering 1 m above it without so much as a wing flap.
![wowscrnshot_111715_001315](https://cloud.githubusercontent.com/assets/15259298/11203265/42046fde-8cc0-11e5-86f3-253a147d019b.jpg)

**Comment by Malae1** [comment]
Fixed in next update
