### ISSUE TITLE
Quest: War on the Woodpaw

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3646]
The quest helper is showing the right blue location of the woodpaw knoll MOB, but if you look at the yellow number "9" on the map it is too far away from the quest location. On the opposite side of the map actually.
http://www.wowhead.com/quest=25426/war-on-the-woodpaw
![wowscrnshot_111715_164547](https://cloud.githubusercontent.com/assets/15259298/11225924/dd281472-8d4a-11e5-9a86-b4ea15f52155.jpg)

**Comment by Malae1** [comment]
Looks like it's working just fine to me..
![Same Quest](http://i.imgur.com/oXNnOTL.jpg)
