### ISSUE TITLE
Warrior passive Riposte

### ISSUE THREAD

**Issue by RealFlex** [HellscreamWoW/Tracker#3648]
Warrior Passive Riposte is not working at all 
http://www.wowhead.com/spell=161798/riposte

(This spell is not found in your Spellbook.
In stead it is a hidden passive found when mousing over 'Critical Strike' under 'Enhancements' of your character screen.)

**Comment by Malae1** [comment]
Fixed in coming update.

**Comment by EPS1L0N** [comment]
#843
