### ISSUE TITLE
Mama Celeste

### ISSUE THREAD

**Issue by samvel2804** [HellscreamWoW/Tracker#3649]
Many times wen i try to interact with this NPC it gives me options that dont do anything. If i try again and again and keep clicking the quest it allows me to continue but it dose not display the end quest "Feast or Famine" text. And the shop option dosent work at all no matter the clicks.
quest : http://www.wowhead.com/quest=26230/feast-or-famine
NPC : http://www.wowhead.com/npc=42497/mama-celeste

**Comment by Malae1** [comment]
fixed in coming update

**Comment by samvel2804** [comment]
awesome
