### ISSUE TITLE
Quest: Pilfered Supplies

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3657]
After completing the quest objectives, you can still continue to open the crates and barrels. You shouldn't be able to.
http://www.wowhead.com/quest=25668/pilfered-supplies
![wowscrnshot_111815_183120](https://cloud.githubusercontent.com/assets/15259298/11258209/55bdfd86-8e25-11e5-9d96-51d9bbe32743.jpg)

**Comment by Malae1** [comment]
Should be fixed next update.
