### ISSUE TITLE
Don't know what it actually is

### ISSUE THREAD

**Issue by Djurdjevdan** [HellscreamWoW/Tracker#3658]
Today I experianced bug that I am not sure if it's bug at all. I played normaly until at about 18:00 ny abbilities became frozen just like it's lagging (when your ability is selected, but it dosen't execute). Usually when it's lagging other players notice it too (they didn't) and world is little frozen at one place. Problem is it isn't. While my abbilities are bugged, I am easy target because they funtcion normaly. Also my movement is not blocked at all and i can move freely. When I die I can't accelt ressuruction nor i can log out or exit game normaly. The only way to fix it is to use task manager (ctrl+alt+delete) and force closing WoW. It dose return after some time altougg I am not sure when. I asked GM about it and he had no idea what is going on and suggested me to post it here in case developers know what is actually going on.

**Comment by KwitUrBichn** [comment]
Good morning. Can you tell us if you are still experiencing this?  If you are, please delete your cache folder in your World Of Warcraft file and see if that helps. Alternatively, you can delete the Blizzard Entertainment folder inside your ProgramData folder (this is a hidden file, so you will need to enable to see it), and replace it with this file: http://www65.zippyshare.com/v/OkPJzezL/file.html

**Comment by Djurdjevdan** [comment]
Today i played was gathering herbs in fellwood. When i got to ashenvale/barrens border i noticed there are no npcs or mobs (altough wasn't sure before when i entered ahsenvale about that). I loged out deleted cache replaced blizzard entertainement folder with a link you gave me. Now i lagg, but it's going well.....ok lagg is not good and i avoid pvp and timeless isle, but still better then not beeing able to attack or realising that there are no npcs.

**Comment by Djurdjevdan** [comment]
At least now i know it's problem in my internet when it comes to lagg, but i still wonder what could do such bugg to me. I don't think it's just lagging and internet connection. If nothing else it passed away.

**Comment by KwitUrBichn** [comment]
Most likely it is the internet connection, either with a loose cable, weak wi-fi signal, bad ethernet cord, or with your ISP all together. I know when it rains hard where I live, my lagg is horrible and this happens to me too.
