### ISSUE TITLE
Quets:The Party Never Ends

### ISSUE THREAD

**Issue by iliarakov** [HellscreamWoW/Tracker#3664]
http://www.wowhead.com/quest=9067/the-party-never-ends
see video https://www.youtube.com/watch?time_continue=54&v=HVJu1jUwsvo
the vendors don't selling  the items  is needing for quets  the npc Hails Dawnstrider don't sell Bundle of fireworks ??

**Comment by KwitUrBichn** [comment]
NPC: http://www.wowhead.com/npc=16442/vinemaster-suntouched
should sell ITEM: http://www.wowhead.com/item=22775/suntouched-special-reserve

NPC: http://www.wowhead.com/npc=16443/zalene-firstlight
should sell ITEM: http://www.wowhead.com/item=22776/springpaw-appetizers

NPC: http://www.wowhead.com/npc=16444/halis-dawnstrider
should sell ITEM: http://www.wowhead.com/item=22777/bundle-of-fireworks

**Comment by carminejackal** [comment]
2679, 2786 , 2757

**Comment by Malae1** [comment]
Fixed in Next update
