### ISSUE TITLE
Feeding the Hungry and the Hopeless

### ISSUE THREAD

**Issue by samvel2804** [HellscreamWoW/Tracker#3665]
Wen summoning a "Westfall Stew" near the homeless nothing happens. Thay dont get fed and it dose not count it to the quest.
quest: http://www.wowhead.com/quest=26271/feeding-the-hungry-and-the-hopeless#screenshots
quest item: http://www.wowhead.com/npc=42617/westfall-stew

**Comment by carminejackal** [comment]
https://github.com/HellscreamWoW/Tracker/issues/1266 https://github.com/HellscreamWoW/Tracker/issues/1424 https://github.com/HellscreamWoW/Tracker/issues/1062

**Comment by Thefakemccoy** [comment]
Just finished the quest with no problem if some one did it before you they get a feed buff which wont allow you to feed the same ones for like 2 mins

**Comment by GMTyrial** [comment]
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/184
