### ISSUE TITLE
MOB: Bloodcursed Voyager

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3678]
This mob is underwater and does not swim up to melee attack you properly. It will sometime walk along the ocean floor and stop under you. Sometimes it will jitter/jump up and down rapidly 2-3 meters while walking towards you.

There are also a low amount of them in the questing area indicated below. I only found 2 in the entire Quest zone as shown below. There should be more. Very inconvenient since the quest needs you to kill 4.
![wowscrnshot_112015_011046](https://cloud.githubusercontent.com/assets/15259298/11293030/ae43cde2-8f23-11e5-9b03-bbb25c87a2b5.jpg)

**Comment by Malae1** [comment]
Fixed in next update
