### ISSUE TITLE
Quest: Pilfered Equipment

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3681]
Been up and down the coastline twice and the equipment quest item is not here.
http://www.wowhead.com/quest=9548/pilfered-equipment
![wowscrnshot_112015_024158](https://cloud.githubusercontent.com/assets/15259298/11294289/4d3e2490-8f30-11e5-8c7c-378fa3678dad.jpg)

**Comment by carminejackal** [comment]
The equipment is there, it is just found in the other direction currently. 
As seen below: 
![](http://i.imgur.com/RmTPrnz.jpg)

**Comment by zwei7** [comment]
so to formally fix
1. update the quest helper blue zone to a new location on the mini map or,
2. move the quest items into the current blue zone

**Comment by Malae1** [comment]
Naturally there may be more than one single spawn of this on retail, for now this is fine. If it becomes a big problem later we can come back to it.
