### ISSUE TITLE
Talent [suceur d'âme]

### ISSUE THREAD

**Issue by filoufrip** [HellscreamWoW/Tracker#3683]
Talent non fonctionnel ainsi que le sort [conflagration] qui ralentit la cible sans être affecter par [immolation]

**Comment by GMTyrial** [comment]
Translation
Title : Talent [soul sucking]
Body : Broken talent and fate [conflagration] that slows the target without being affect by [immolation]

Possible duplicate : https://github.com/HellscreamWoW/Tracker/issues/1369
