### ISSUE TITLE
esviscerate damage bug

### ISSUE THREAD

**Issue by ricardoesl** [HellscreamWoW/Tracker#3697]
http://www.wowhead.com/spell=2098 
http://es.tinypic.com/m/j6r8no/2
http://es.tinypic.com/m/j6r8s0/2
Level 99 rogue hits me over the 100k damage, my priest level 100

**Comment by Collector-Hellscream** [comment]
#3563

**Comment by Hangun** [comment]
I think we should close this too. Eviscerate had fixed in newest update

**Comment by Malae1** [comment]
Fixed #2266
