### ISSUE TITLE
Kaw the Mammoth Destroyer

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#370]
"I tried mounting a Wooly Mammoth Bull to Kill Kaw the Mammoth Destroyer and the server crashed.

http://www.wowhead.com/quest=11879/kaw-the-mammoth-destroyer
http://www.wowhead.com/npc=25743/wooly-mammoth-bull
"

**Comment by EPS1L0N** [comment]
Should be fixed
