### ISSUE TITLE
Order of the Cloud Serpent

### ISSUE THREAD

**Issue by Beponator** [HellscreamWoW/Tracker#3728]
Couple of quest are doable but it can't be completed because of missing NPC 
http://www.wowhead.com/npc=58564/elder-anli, i think it's her,my quest mark shows me into that gazeebo but noone is there.

**Comment by KwitUrBichn** [comment]
https://github.com/HellscreamWoW/Tracker/issues/1880

**Comment by Malae1** [comment]
Fixed in next update
