### ISSUE TITLE
[Quest] [Chillwind Camp] Uther's blessing

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#373]
"https://www.youtube.com/watch?v=dgzM4vRPHuo

The inscriptional tablet is missing as long with the priest"

**Comment by Kelpo122** [comment]
Should add a tag for the missing npc

**Comment by GMTyrial** [comment]
I can confirm this quest works

**Comment by GMTyrial** [comment]
#2235
