### ISSUE TITLE
Quest: The Perenolde Tiara

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3734]
The mob (Grelborg the Miser) responsible for dropping the tiara quest item (tiara) isn't there.

Quest
http://www.wowhead.com/quest=543/the-perenolde-tiara
Mob
http://www.wowhead.com/npc=2417/grelborg-the-miser

![wowscrnshot_112615_221627](https://cloud.githubusercontent.com/assets/15259298/11433472/afd67728-948b-11e5-99dc-6bdb565df132.jpg)

**Comment by carminejackal** [comment]
I'll check this again, but last time I did this quest, I was able to complete it. The spawn was just in the wrong location. I'll update with where he is when I locate him again.
