### ISSUE TITLE
Gilnéas - Quête de départ Worgen - "Quelque chose ne vas pas"

### ISSUE THREAD

**Issue by AlphaDraconis** [HellscreamWoW/Tracker#3737]
Absence du PNJ Prince Liam donc impossible de valider la quête.

Cette quête débloque normalement les autres quêtes de la zone. Comme elle est beuguée, les joueurs sont obligés de prendre le portail pour Hurlevent pour monter leur personnage de niveau.

**Comment by Malae1** [comment]
This is very known as we have not scripted the worgen start area, hence the portals.
