### ISSUE TITLE
SORTS - Chevalier de la mort [Rafale hurlante]

### ISSUE THREAD

**Issue by AlphaDraconis** [HellscreamWoW/Tracker#3756]
"Rafale hurlante" spécialisation givre, la fièvre de givre ne se propage pas !

**Comment by KwitUrBichn** [comment]
English translation: 
SPELLS - Death Knight [Howling Blast]

"Howling Blast" Frost specialization, frost fever does not spread!

**Comment by KwitUrBichn** [comment]
https://github.com/HellscreamWoW/Tracker/issues/1954
