### ISSUE TITLE
Broken NPC

### ISSUE THREAD

**Issue by radovicz** [HellscreamWoW/Tracker#3758]
Ornag the Weapon Merchant in Mor`Shan Ramparts is broken!

**Comment by Malae1** [comment]
Please provide us more information as to why this NPC is broken.

**Comment by radovicz** [comment]
I mean it says weapon merchant and the cursor changes when you hover over the npc but she actually is just not giving me a option to buy weapons,repair armor...

**Comment by Malae1** [comment]
Fixed in next update
