### ISSUE TITLE
MOB: Saltspray Gull

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3761]
In thousand needles, this gull has the wrong height coordinates. It should be up in the air. Not underwater flapping it's wings.
![wowscrnshot_112915_121224](https://cloud.githubusercontent.com/assets/15259298/11458983/31f140b6-969a-11e5-85ec-c349ee864771.jpg)

In Tanaris, found this sea gull too low on the ground. floating and not moving, just flapping.
![wowscrnshot_113015_023318](https://cloud.githubusercontent.com/assets/15259298/11465884/ecd8bbc8-970a-11e5-9196-eb3027054be7.jpg)

**Comment by Malae1** [comment]
Fixed in next update
