### ISSUE TITLE
MOB: Silithid Wasps

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3762]
In Thousand Needles this mob has the wrong height coordinates. It should be fying up in the air. When you get close to one it drops out really fast out of the air to the water's surface and is targetable. However it does not aggro. Once you kill it, the corps is bobbing up and down in mid-air.
![wowscrnshot_112915_150309](https://cloud.githubusercontent.com/assets/15259298/11459697/9791f978-96aa-11e5-9129-d59c1ea1b96d.jpg)

When I'm underwater it drops out of the sky and though you can select it, the "out of range" warning appears since the game thinks it's height coordinate is still in the sky, yet the game displays the flyig bug as underwater. It is animated as flying underwater since it is flapping the wings.
![wowscrnshot_112915_145500](https://cloud.githubusercontent.com/assets/15259298/11459708/ea7a5504-96aa-11e5-99e5-50f01ebeadfb.jpg)

**Comment by Malae1** [comment]
Fixed in next update
