### ISSUE TITLE
Bonechewer Devastator double spawns

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#3769]
http://www.wowhead.com/npc=16772/bonechewer-devastator

![wowscrnshot_112915_183431](https://cloud.githubusercontent.com/assets/12555606/11460990/db70997a-96c7-11e5-8a56-3748ec99b687.jpg)

Some of the mobs seem to have a habit of spawning in the ground

**Comment by Malae1** [comment]
fixed.
