### ISSUE TITLE
Item: Captain's Key

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3778]
This quest item drops without a limitation. You also can't carry more than one. I also am not on the quest for it. I don't know the quest it is for either.
![wowscrnshot_113015_025022](https://cloud.githubusercontent.com/assets/15259298/11466507/5374328c-970f-11e5-8570-501d3912f45a.jpg)

**Comment by Tregeta** [comment]
There is no quest, it is meant to open a lock box. Drop rate adjusted in next update, it is common to not be able to loot uniques.
