### ISSUE TITLE
Ruins of The Scarlet Enclave : Missing NPCs

### ISSUE THREAD

**Issue by GMTyrial** [HellscreamWoW/Tracker#3782]
There aren't any NPCs in the entire Ruins of The Scarlet Enclave area, or Deaths Breach. 

I was told by a DK about the issue, and was also told that they were here for awhile. I'm guessing the first part was an instance of it, and the global one is missing them?

The surrounding area and The Ebon Hold have NPCs

**Comment by carminejackal** [comment]
I don't believe there are supposed to be NPCs in the "Ruins of the Scarlet Enclave" , the only time the area has NPCs as far as I recall is during the DK starter instance. The open world version of Deaths Breach is also supposed to be similarly empty, only populated during the DK starter. 

"Upon finishing the Final Quests and leaving the instanced Scarlet Enclave, one will find that like Havenshire and New Avalon, Death's Breach has been abandoned. The Tents remain, the Lich King's platform does not however. Transport to and from Acherus has been removed in favor of the Death Knight's Death Gate. This also keeps others out of Acherus through normal means. Death Knights can also use the flight path to get into the Ebon Hold, should they not want to use or cannot use Death Gate." 

As seen in the links, there are no NPCs in the area.
http://wowwiki.wikia.com/wiki/Ruins_of_the_Scarlet_Enclave  http://wowwiki.wikia.com/wiki/Death's_Breach
