### ISSUE TITLE
NPC: Carmen Ibanozzle

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3789]
Innkeeper NPC presents 2 options that don't work when you click them. Can't make it your home and can't shop.
![wowscrnshot_113015_152051](https://cloud.githubusercontent.com/assets/15259298/11483404/2abf06ca-9776-11e5-8c69-07f1f5d1b997.jpg)

**Comment by Malae1** [comment]
Fixed in next update

**Comment by K-Reeboo** [comment]
As of today, if fixed previously, not working again. Both gossip options not working.
