### ISSUE TITLE
NPC: Grimwing <Flight Master>

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3806]
He is not there.
http://www.wowhead.com/npc=29480/grimwing

![wowscrnshot_120215_142044](https://cloud.githubusercontent.com/assets/15259298/11541501/911f05ec-9900-11e5-9513-bce6fff5774d.jpg)
This is my location on the map.
![wowscrnshot_120215_142536](https://cloud.githubusercontent.com/assets/15259298/11541502/925acb4e-9900-11e5-92ce-8b20459a7e9b.jpg)
Notice there is another golden flightmaster icon north of where i am? I can't reach it. Maybe it is grimwing's flight location labeled in the wrong location on the map.

**Comment by carminejackal** [comment]
The golden flight master you're seeing is above you in Ebon Hold. He is there, he's just not accessible to anyone except DK's and possibly people who can fly up to Ebon Hold. Though I've never tested the latter.

**Comment by zwei7** [comment]
Oh ok dk access okay. There is also no flightmaster icon where I am standing. The Grimwing flightmaster. I moved my position silver arrow icon. No Grimwing flightmaster. In fact the whole camp is empty, no NPCs to populate it.
![wowscrnshot_120215_193225](https://cloud.githubusercontent.com/assets/15259298/11548580/e6d24316-992b-11e5-8870-cafa633bf79b.jpg)

**Comment by carminejackal** [comment]
It's supposed to be empty actually. The only time it's populated is during the DK starter instance.

**Comment by zwei7** [comment]
So i guess grimwing is never supposed to exist there then unless you are a death night?

**Comment by carminejackal** [comment]
Grimwing in Ebon Hold, which is in the sky. You can only get to Ebon Hold if you are a Death Knight or if you can actually fly (lvl 60+).  He's only in the non-starter Ebon Hold.
