### ISSUE TITLE
Items: "Libram of Focus" + "Libram of Rapidity"

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3821]
These two books drop from MOBs in Dire Maul, but they are associated to outdated quests that have been removed from them since cataclysm.
http://www.wowhead.com/item=18333/libram-of-focus#comments

In addition they drop without considering you own one or not. You can only have one of each book. So when I let I get messages saying I already have that.
![wowscrnshot_120315_141221](https://cloud.githubusercontent.com/assets/15259298/11572011/26d05ae2-99cd-11e5-9b74-32a931ced5b2.jpg)
![wowscrnshot_120315_141416](https://cloud.githubusercontent.com/assets/15259298/11572013/26e13538-99cd-11e5-9274-1394ccfc6dd9.jpg)
![wowscrnshot_120315_141425](https://cloud.githubusercontent.com/assets/15259298/11572012/26d0edae-99cd-11e5-9a4f-cca16a6e718e.jpg)

**Comment by Tregeta** [comment]
These items are still meant to drop, it is also normal to see uniques drop and not be able to pick them up if you already have one.
