### ISSUE TITLE
Garrison zone change loading issue

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#3831]
When entering or leaving the garrison, a loading screen can appear without a loading progress bar and the screen flickering.

EDIT: This situation happens when exiting the garrison through the northwest exit, hasn't happened on the southeastern exit when tested.

**Comment by HellscreamWoW** [comment]
This issue caught us by surprise. Everything was working great on Windows, however once we started the core on Linux, this issue presented itself. We're working on fix. Thank you for your report, and for your patience during this time.

**Comment by tribaljet** [comment]
Certainly, I imagined that such an extensive update could have unexpected issues.

Also, the southeastern exit also causes the loading issue.

**Comment by HellscreamWoW** [comment]
Yes, we have confirmed that it happens in the southeastern exit. It is just much less likely to occur there. Same applies for Horde. For the most part they can enter / exit freely, but do occasionally suffer from this issue. We have several leads that we're exploring.

**Comment by HellscreamWoW** [comment]
Fixed
