### ISSUE TITLE
Holy Shock (Holy Paladin)

### ISSUE THREAD

**Issue by Oloorin** [HellscreamWoW/Tracker#3834]
This ability doesnt work at, not dealing damages nor healing anything, just wasting your gold (for respec) and time. 

Would be cool if it could be fixed quickly :)

**Comment by Malae1** [comment]
https://github.com/HellscreamWoW/Tracker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+holy+shock

**Comment by KHAR05** [comment]
paladin spell HOLY SHOCK is not working properly, it is casting but dont heal or damage the target and do nothing.. please help fix it. thanks.
