### ISSUE TITLE
Markmanship (Arcane Shot Missing)

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#384]
"I got lvl 10, got my specialization (Marksman) and my Arcane Shot jut dissapear and was replace by Steady Shot.

Im sure that wasnt suppose to happend. Vital skill for a Hunter "

**Comment by omigawail** [comment]
Requesting lock. Quoted from Arcane shot's Wowwiki page:
"Patch changes:
Patch 6.0.2 (14-October-2014): Arcane Shot is no longer available to Marksmanship Hunters."
