### ISSUE TITLE
NPC: Donna Berrymore <Innkeeper>

### ISSUE THREAD

**Issue by zwei7** [HellscreamWoW/Tracker#3845]
This npc presents duplicate options to buy/sell when you speak to her.
http://www.wowhead.com/npc=44334/donna-berrymore
![wowscrnshot_120615_231222](https://cloud.githubusercontent.com/assets/15259298/11618904/fae8e396-9c6e-11e5-9f88-974e7eabf7fc.jpg)

**Comment by Malae1** [comment]
Fixed in next update
