### ISSUE TITLE
Call Pet

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#385]
Last time i log out i have a starter pet for a troll hunter, i tamed another one and everything was just fine. Next time a log in i had no pet at all. Tried to revive him and nothing happend. I tamed a new one, relog and same thing... No pet

**Comment by Malae1** [comment]
http://www.hellscream-wow.com/log#2015.6.06.010536 & http://www.hellscream-wow.com/log#2015.12.06.010543
