### ISSUE TITLE
For The Horde! Pre-Garrison Quest.

### ISSUE THREAD

**Issue by purgatorypro** [HellscreamWoW/Tracker#3862]
Seems there is a bug on my Druid.  I had "For The Horde!" garrison quest before the garrison release however after placing the banner Thrall doesn't show the question mark to turn the quest in.  I've abandoned it and redone it a few times.  You can pick up the quest from Thrall, just can never turn it in after completing.

**Comment by Aveta** [comment]
You have to turn it in to Gazlowe who's supposed to appear. If you did quests before garrisons were scripted, you currently need to ask a GM to reset the questline for you.
