### ISSUE TITLE
[Quest] Tuning the Gnomecorder

### ISSUE THREAD

**Issue by sultanelu** [HellscreamWoW/Tracker#3923]
I got the gnomecorder from the murloc place, turned in the quest, and took the next quest : http://www.wowhead.com/quest=26512/tuning-the-gnomecorder . I went to the graveyard, and cannot do nothing, i cannot use anything but i assume i am in the right place :) made a screen also 
http://postimg.org/image/n6ja3cu6h/

**Comment by Malae1** [comment]
Duplicate #415
