### ISSUE TITLE
Garrison Missions duration increased

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#3932]
It seems that across all of my characters, every single Garrison Mission is taking 10 minutes longer then they should.

![wowscrnshot_121115_215305](https://cloud.githubusercontent.com/assets/12555606/11759781/9fdae4cc-a051-11e5-98c5-d1794cea3b39.jpg)

![wowscrnshot_121115_215308](https://cloud.githubusercontent.com/assets/12555606/11759782/a2bcea1e-a051-11e5-934c-9a863ab69fdd.jpg)

![wowscrnshot_121115_215314](https://cloud.githubusercontent.com/assets/12555606/11759783/a44585b2-a051-11e5-9d1b-ca56dfda668e.jpg)

**Comment by GeneralCaveman** [comment]
This issue seems to be resolved as of right now.

**Comment by Malae1** [comment]
If this changes, please let us know, closing for now.
