### ISSUE TITLE
The escape

### ISSUE THREAD

**Issue by deathbane1911** [HellscreamWoW/Tracker#3935]
http://www.wowhead.com/quest=863/the-escape this quest is unfinishable because http://www.wowhead.com/npc=3442/sputtervalve you cannot talk to this NPC, and he has other quests as well http://www.wowhead.com/quest=29086/competition-schmompetition http://www.wowhead.com/quest=14006/read-the-manual http://www.wowhead.com/quest=29021/samophlange http://www.wowhead.com/quest=14003/samophlange-repair http://www.wowhead.com/quest=29094/the-short-way-home which are unavailable

**Comment by Tregeta** [comment]
npc was fixed a few updates ago.
