### ISSUE TITLE
[Druid] Primal Fury

### ISSUE THREAD

**Issue by Collector-Hellscream** [HellscreamWoW/Tracker#3938]
http://www.wowhead.com/spell=16961/primal-fury

It seems like feral druids are generating 2 combo points all the time and not only from critical strikes with combo generator abilities.

**Comment by kitvoid** [comment]
I'd like to add that Bears always get the +8 rage too, even from normal attacks, not just critical strikes.

**Comment by EPS1L0N** [comment]
#2266
