### ISSUE TITLE
Healing Touch for Feral (at least)

### ISSUE THREAD

**Issue by Collector-Hellscream** [HellscreamWoW/Tracker#3939]
http://www.wowhead.com/spell=5185/healing-touch
http://www.wowhead.com/spell=69369/predatory-swiftness

Using instant Healing Touch (with Predatory Swiftness proc) generates 1 combo point. It shouldn't.

**Comment by Collector-Hellscream** [comment]
Umm... It's fixed since 2015.24.12.030602 update :P

**Comment by Tregeta** [comment]
Ref #2266
