### ISSUE TITLE
Patchwerk double spawn

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#3989]
http://www.wowhead.com/npc=16028/patchwerk

While running the 10 man version of Naxx, I seemed to have run into two Patchwerks that spawn one on top of the other.

**Comment by Tregeta** [comment]
There is only one in the 10 man version.

**Comment by GeneralCaveman** [comment]
I noticed the issue was fixed when I went through Naxx yesterday. Should have updated here.
