### ISSUE TITLE
missing pvp gear

### ISSUE THREAD

**Issue by Collector-Hellscream** [HellscreamWoW/Tracker#3994]
There's some missing gear from Ashran PvP vendors. At least for leather agility users.

![wowscrnshot_121515_184556](https://cloud.githubusercontent.com/assets/14946340/11818749/5f09e28c-a35c-11e5-8d34-6cbadb93a7fd.jpg)
![wowscrnshot_121515_184600](https://cloud.githubusercontent.com/assets/14946340/11818756/6548456c-a35c-11e5-8633-0b35848857ef.jpg)
![wowscrnshot_121515_184607](https://cloud.githubusercontent.com/assets/14946340/11818758/6b5bf6a6-a35c-11e5-8b75-a6fd93890c26.jpg)

Here are all 3 pages of gear for feral druids from honor vendor. There are no shoulders, chests etc. No gear with set bonuses. 
Conquest vendor have only versatility off set. Also no gear with set bonuses.

**Comment by Tregeta** [comment]
Fixed in update
