### ISSUE TITLE
[Spell] [Shaman] Chain Heal

### ISSUE THREAD

**Issue by Nienz** [HellscreamWoW/Tracker#4002]
i tested chain heal and its bugged, i get healed for 20k or so my target 25k and the ones in between 10million, thats way to OP

**Comment by EPS1L0N** [comment]
couldnt reproduce, http://puu.sh/lX3qi/00b5fba52f.jpg
do you have any other information on how to reproduce it?

**Comment by Nienz** [comment]
no i dont what cause it, it can be racial (draenei) talents or glyphs anyway i took a sc http://imgur.com/QOZXow0

**Comment by Nienz** [comment]
hmm i read on the mastery might not be what i thought it would, didnt knew it was changed on wod, but ill check again to be 100% sure

**Comment by Nienz** [comment]
oke tested it on a lvl 100 and this is the result [img]http://i.imgur.com/jOsPgUO.jpg[/img]

**Comment by EPS1L0N** [comment]
fixed, #2266

**Comment by EPS1L0N** [comment]
It's caused by High Tide. I went ahead and fixed the entire spell. I also noticed Earth Shield was giving way too much of a benefit, fixed that aswell. sorry it took so long, some stuff came up and i had to put this on hold for a couple days. thx for the report ^^
