### ISSUE TITLE
orb of translocation

### ISSUE THREAD

**Issue by johnluke93** [HellscreamWoW/Tracker#4003]
the orb of translocation at Falcon Watch in Outland, Hellsfire Peninsula. dose not work...sorry i forgot that end part LOL

**Comment by Malae1** [comment]
What about it?

**Comment by Luminescent-Hellscream** [comment]
You need to provide details about the bug not providing details to the devs so they know what is broken will just result in this issue being closed please edit your post and provide details on what exactly is not working with as much info as you can.

**Comment by Tregeta** [comment]
With no response in 3 days, this issue will be closed due to lack of details.
