### ISSUE TITLE
recieving donation items

### ISSUE THREAD

**Issue by gargil** [HellscreamWoW/Tracker#4005]
A couple days ago i bought 2 items in the browser but so far i hadnt recieved anything i just want to know how much more ill it last for me to recieve my items?

Polished Legplates of Valor
Worn Stoneskin Gargoyle Cape

![ff](https://cloud.githubusercontent.com/assets/16325795/11850114/08c8f2c4-a3f1-11e5-9069-d692e1b851ee.png)

**Comment by Malae1** [comment]
Items are sent directly to your character's heirloom page, you just need to relog.
