### ISSUE TITLE
Quest:Tree's Company

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#401]
In Draenai zone Azuremyst isle, there is questline from captain  Odesyus. You have to hide as a tree where cut scene will start. The problem is the cut scene dosen't start. I tried many times and it simply dosen't start. There is NPC in a distance (goblin Geezle), but it dosen't move. It looks like whole scenario is placed, but frozen. It's probably problem with triggers.

**Comment by EPS1L0N** [comment]
ref #380
