### ISSUE TITLE
players 'out of range'

### ISSUE THREAD

**Issue by Collector-Hellscream** [HellscreamWoW/Tracker#4012]
I'm not sure if this is a bug or my latency (around 130 ms) but I saw same problem on "another place" and it was fixed there. It's not as serious here like it was there but still, in PvP combat it matters.

So, if I'm somehow slowed or my target have movement speed increased (or both) I'm not able to attack him even tho I'm right behind him or if running right at him. There's error massege 'out of range' while clearly target/player is right at my druid's face.

Of course it's not noticable when target is stunned, have same speed or if you're ranged class. And for some reason (abilities with movement speed increase?) it affects the most priests, death knignts (or at least I noticed that only on them) and players that are mounted.

**Comment by kupidons** [comment]
well it's funny, as rogue i have smth similar, trying to catch sb moving. and also when u sap moving target, they just seems to keep moving. dunno about is it visual or real bug

**Comment by Collector-Hellscream** [comment]
Dunno what happened in last update but my ms is now at 50-52. Will check if that fixes the issue as soon as possible.

**Comment by EPS1L0N** [comment]
happens on blizz aswell, incredibly annoying.

**Comment by EPS1L0N** [comment]
seems there's a movement bug happening when a players speed changes, which causes the receiving client to delay their movement for some reason.

**Comment by EPS1L0N** [comment]
Speed changes, teleporting, and knockbacks would cause movement to get out of sync between client & server.
still though, keep my wall of text in mind ;)

**Comment by HellscreamWoW** [comment]
Should be noted, this was closed because it was fixed. It will be applied to our live realms next update.

**Comment by Collector-Hellscream** [comment]
Thank you :)
