### ISSUE TITLE
Quest:I shot magic into the Darkness

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#403]
The quest says you should go to Warp postion where you will descover Sin Gate and you should kill 5 Void Anomalys there. Those Void walkers are so closle to each other that it's sometimes impossible to pull just 1. However that's not the main problem. The problem is that even tough I discovered War postion, it still says that I must descover that quest (in short objective dosen't complete itself). Killing Void walkers is nightmare, since sometimes quest restarts itself when I "enter" that building so I have to kill 5 new Void walkers

**Comment by HellscreamWoW** [comment]
Active with real poster. Closing old issue.
