### ISSUE TITLE
[Buffs] Well fed Stacking

### ISSUE THREAD

**Issue by Luminescent-Hellscream** [HellscreamWoW/Tracker#4033]
currently you can stack the well fed but this should not happen when eating another food that gives well fed it should replace the well fed buff active on you 
 
[YT video](https://www.youtube.com/watch?v=EALJZvsANHc)

**Comment by Tregeta** [comment]
http://www.wowhead.com/item=81401/yak-cheese-curds
http://www.wowhead.com/item=81406/roasted-barley-tea
http://www.wowhead.com/item=81409/tangy-yogurt
http://www.wowhead.com/item=81411/peach-pie
http://www.wowhead.com/item=81403/dried-peaches
http://www.wowhead.com/item=81414/pearl-milk-tea
http://www.wowhead.com/item=81404/dried-needle-mushrooms
http://www.wowhead.com/item=81412/blanched-needle-mushrooms
http://www.wowhead.com/item=81405/boiled-silkworm-pupa
http://www.wowhead.com/item=81413/skewered-peanut-chicken


Assumption it may be more than just these linked.

http://www.wowhead.com/item=81405/boiled-silkworm-pupa#shared-cooldown

**Comment by Luminescent-Hellscream** [comment]
Seems to be all foods that give the well fed buff stack

**Comment by Tregeta** [comment]
These are the ones that were reported privately a little bit ago that were being tracked on the player. Added the shared cooldown since it also relates to all food buffs.

**Comment by Tregeta** [comment]
fixed
