### ISSUE TITLE
[NPC] Gordok Warlock

### ISSUE THREAD

**Issue by Luminescent-Hellscream** [HellscreamWoW/Tracker#4034]
Currently the npc's [Gordok Warlock](http://www.wowhead.com/npc=11448/gordok-warlock) can not be attacked in the instance of Dire Maul

[Screenshot](http://i.imgur.com/uhuLyhv.jpg)

**Comment by Tregeta** [comment]
Ref https://github.com/HellscreamWoW/Tracker/issues/3751
