### ISSUE TITLE
[NPC] Gordok Reaver

### ISSUE THREAD

**Issue by Luminescent-Hellscream** [HellscreamWoW/Tracker#4035]
Currently the Npc [Gordok Reaver](http://www.wowhead.com/npc=11450/gordok-reaver) can not be attacked in the instance Dire Maul

[Screenshot](http://i.imgur.com/wlUOFDN.jpg)

**Comment by Tregeta** [comment]
Ref https://github.com/HellscreamWoW/Tracker/issues/3751
