### ISSUE TITLE
[NPC] Gordok Captain 11445

### ISSUE THREAD

**Issue by Luminescent-Hellscream** [HellscreamWoW/Tracker#4036]
currently the npc [Gordok Captain](http://www.wowhead.com/npc=11445/gordok-captain) can not be attacked in Dire Maul

[Screenshot](http://i.imgur.com/U6Qie68.jpg)

**Comment by Tregeta** [comment]
Ref https://github.com/HellscreamWoW/Tracker/issues/3751
