### ISSUE TITLE
[NPC] Asuur

### ISSUE THREAD

**Issue by Luminescent-Hellscream** [HellscreamWoW/Tracker#4040]
the npc [Asuur](http://www.wowhead.com/npc=20616/asuur) after right clicking him has no pop up for the good he sells at all.

**Comment by Tregeta** [comment]
Seems like it works for me, try clearing cache. I did notice that it is lacking most all class set data, that will be rectified soon.

**Comment by Tregeta** [comment]
fixed in next update

**Comment by Luminescent-Hellscream** [comment]
Thanks for the update I did try to clear cache also and got the same results no gossip at all. Any idea when the next update will be.

**Comment by Tregeta** [comment]
All seem to check out on my end, can you provide me with your faction standing?
