### ISSUE TITLE
Paladin's Holy Shield talent bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#4044]
After the last update the Paladin's Holy Shield talent stopped working altogether, causing no damage at all, as well as having lowered block chance by 5%.

**Comment by EPS1L0N** [comment]
holy shield has no impact on block chance.

**Comment by tribaljet** [comment]
That doesn't explain why the block chance got lowered by 5%, and Holy Shield should proc on both physical and magic attacks.

**Comment by EPS1L0N** [comment]
No, holy shield should not proc from physical (melee) attacks, I assure you. We tested this spell on blizzards realms and researched it well before fixing it.

**Comment by EPS1L0N** [comment]
We will retest this later today on blizzards realms though, just to be absolutely sure

**Comment by tribaljet** [comment]
Reason I say this is because block chance isn't limited to just spells and proccing damage reflection.

Also, any idea why I have dropped from 44 to 39% since the last update with zero changes to my character's build?

**Comment by EPS1L0N** [comment]
Haven't the foggiest as to why your block chance was lowered by 5%. the only change to paladins was holy shield, and it couldn't possibly have been the cause. A glyph maybe? We did some changes to glyph mechanics recently though I don't know if they are live yet

**Comment by tribaljet** [comment]
Hmm. Currently active glyphs (that have been active for many months without having been replaced) only change skill range, damage and damage reduction, none affecting stats that would directly impact block chance. Also, if I understood correctly, glyph mechanics changes would only be directly related to current talents set, right?

**Comment by tribaljet** [comment]
Ok, I'd like to add that the block chance issue was an oversight of mine due to having been running stat comparison yesterday between buffs.

My question only remains regarding damage reflection proccing through physical damage alongside magical damage.

**Comment by Luminescent-Hellscream** [comment]
https://drive.google.com/file/d/0Bx0fRBSYFJkGRTc5MWlBUGdLUkU/view?usp=docslist_api

Take a look at that screen grab nothing has changed and it does state normal damage will cause it to deal damage

**Comment by tribaljet** [comment]
I have seen that earlier as well, and going by that, physical damage received should proc Holy Shield, not just magical damage, yet physical damage is not proccing it right now.

**Comment by EPS1L0N** [comment]
Indeed, all attacks / spells which can be blocked should trigger Holy Shield's damage effect.
I also noticed that spells which increase block amount pct weren't working, so i fixed that aswell. ([Improved Block](http://www.wowhead.com/spell=157488/improved-block) draenor perk)
