### ISSUE TITLE
[Felwood] Innkeeper : Wylaria and Tennycaugh

### ISSUE THREAD

**Issue by Nemrods** [HellscreamWoW/Tracker#4048]
These innkeepers don't propose to set there inn as the Hearthstone.
But they have twice the proposition to browse goods.

Therefore it's impossible to set an inn in Felwood for the Horde.

More info : 
http://www.wowhead.com/npc=48215/innkeeper-wylaria
http://www.wowhead.com/npc=48599/innkeeper-teenycaugh

**Comment by Tregeta** [comment]
fixed in next update
