### ISSUE TITLE
[Felwood] [Quest] Feathers for Nafien

### ISSUE THREAD

**Issue by K-Reeboo** [HellscreamWoW/Tracker#4053]
I interact with Nafien as if I had that quest in my tasks.
Though I was never proposed to start this quest by NPC.

See my quest log and NPC gossip window on screenshots.

It is a problem since this quest must be done first, which then enables the dailies to grow Timbermaw Hold reputation. And feathers is very quick way once 'Revered'
Starting the quest should trigger the drop of the 'Headdress Feathers' on mobs.
After completion, Feathers should drop normally to complete the dailies.
And as of today, killing required mobs does not drop the item.

![wowscrnshot_122515_112405](https://cloud.githubusercontent.com/assets/16204587/12003754/244bd4d4-aafa-11e5-89f8-078672c7fede.jpg)
![wowscrnshot_122515_112421](https://cloud.githubusercontent.com/assets/16204587/12003755/2ab06376-aafa-11e5-948d-1ddd4ddbdc29.jpg)

**Comment by Tregeta** [comment]
fixed in next update
