### ISSUE TITLE
Warrior Talent - Sudden Death

### ISSUE THREAD

**Issue by niksunstz1** [HellscreamWoW/Tracker#4058]
The Sudden death talent always Procs it says that it should proc 2.5 times in 1 minute but it always procs and people are spamming Execute Execute nonstop this one should be fixed for sure because warriors will use only 1 magic ...

**Comment by kupidons** [comment]
they can't if they don't have rage :D

**Comment by Tregeta** [comment]
Ref https://github.com/HellscreamWoW/Tracker/issues/1742
