### ISSUE TITLE
[Buffs] +5% Strength, Agility, and Intellect

### ISSUE THREAD

**Issue by Luminescent-Hellscream** [HellscreamWoW/Tracker#4069]
[Blessing of Kings](http://www.wowhead.com/spell=20217/blessing-of-kings) and [Mark of the Wild](http://www.wowhead.com/spell=1126) Are currently stacking together when they should not 

Effect: +5% Strength, Agility, and Intellect
Brought by: Any  Druid ( Mark of the Wild), any  Monk ( Legacy of the Emperor), and any  Paladin ( Blessing of Kings) 

Any of these buffs should not stack with one another have not tested is Monk one is stacking as was not able to find a monk at time of posting this to test it.

Complete list of buffs that are the same : 

Druid:
[Mark of the Wild](http://www.wowhead.com/spell=1126)

Monk:
[Legacy of the Emperor](http://www.wowhead.com/spell=115921)
[Legacy of the White Tiger](http://www.wowhead.com/spell=116781)

Paladin:
[Blessing of Kings](http://www.wowhead.com/spell=20217/blessing-of-kings)

Hunter:
[Lone Wolf: Power of the Primates](http://www.wowhead.com/spell=160206)

Pets: 

Dog
[Bark of the Wild](http://www.wowhead.com/spell=159988/bark-of-the-wild)
Gorilla
[Blessing of Kongs](http://www.wowhead.com/spell=160017)
Shale Spider
[Embrace of the Shale Spider](http://www.wowhead.com/spell=90363)
Worm
[Strength of the Earth](http://www.wowhead.com/spell=160077)

In-game screenshots

[No buff's](http://i.imgur.com/HrqFIIy.jpg)
[Buffed with Mark of the Wild](http://i.imgur.com/O8YBZKb.jpg)
[Buffed with Mark and Kings](http://i.imgur.com/g7Yo5sR.jpg)
[Buffed with Mark, Kings and Legacy of the white tiger](http://i.imgur.com/nqkAjdx.jpg)

**Comment by Tregeta** [comment]
Fixed next update.

**Comment by Luminescent-Hellscream** [comment]
Awesome work as usual guys keep it up.
