### ISSUE TITLE
[Buffs] Blessing of Kings / Might

### ISSUE THREAD

**Issue by Luminescent-Hellscream** [HellscreamWoW/Tracker#4070]
[Blessing of Kings](http://www.wowhead.com/spell=20217/blessing-of-kings) and [Blessing of Might](http://www.wowhead.com/spell=19740) Can both be cast by the same paladin.

How it should work: You should only be able to have one blessing acctive per paladin in the group so 1 paladin = kings or might but the same paladin can not cast both on the party if he or she is the only paladin.

[Screen of Kings being cast by myself](http://i.imgur.com/quzVpT9.jpg)
[Might being cast by meself while my own kings buff is active](http://i.imgur.com/8D5NIN5.jpg)

**Comment by Tregeta** [comment]
Fixed next update.
