### ISSUE TITLE
Miniature Camel Figurine is unlootable

### ISSUE THREAD

**Issue by Tankamin** [HellscreamWoW/Tracker#4095]
Hello, I found the Miniature Camel Figurine in Uldum but i was unable to loot it.

**Comment by Luminescent-Hellscream** [comment]
[Miniature Camel Figurine](http://www.wowhead.com/npc=50410/)

**Comment by Tregeta** [comment]
Ref #1677

**Comment by Tankamin** [comment]
Hello, how can i become a scripter/contributer? We have access to retail WoD and being in IT, I'm familiar with sniffers, etc.  Or let us know how we can help. 

Thanks.
