### ISSUE TITLE
Commander Kolurg missing

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#4103]
http://www.wowhead.com/npc=26798/commander-kolurg

This NPC appears to be missing in the normal mode of The Nexus. He does appear in heroic mode however.

http://www.wowhead.com/zone=4265/the-nexus

**Comment by Tregeta** [comment]
He's heroic mode only.
![Proof](http://i.imgur.com/MudIk37.jpg)
