### ISSUE TITLE
Unholy DK/Raise Dead spell isn't working correctly

### ISSUE THREAD

**Issue by Krizar73** [HellscreamWoW/Tracker#4106]
As from the title, Raise Dead as Unholy Death Knight only summons a "Guardian" Ghoul [Risen Ally is it's actual name] so it only lasts 1 minute and has no spellbar. Plus, the spell's CD is supposed to be 1 minute but it's actual CD when it gets used is 2 minutes. 
![wowscrnshot_010216_192535](https://cloud.githubusercontent.com/assets/16519263/12075951/f8fc8ae8-b194-11e5-9e83-d91098c9ce49.jpg)
As you can see from the screenshot, the Ghoul is a "Guardian" and the CD is broken.

**Comment by Tregeta** [comment]
Ref #393, please include the updated information within that post.
