### ISSUE TITLE
Paladin - seal of command

### ISSUE THREAD

**Issue by Skauroki** [HellscreamWoW/Tracker#4126]
Hello , button for seal of command after activating it is stuck , it has picture that it's activated but it isn't and clicking the button doesn't do anything. after dying , respawning , loggining out exiting game - when game loads its always stuck at activated but in reality it isn't.

**Comment by Warjakh** [comment]
I see your paladin is only level 17. You are not meant to be able to de-activate it until you get another seal. The buff is an invisible aura even on retail now, it's working as intended. You should get your next seal when you reach level 22. 

![](http://i.imgur.com/zSbDOK1.png)
