### ISSUE TITLE
Quest Ever So Lonely

### ISSUE THREAD

**Issue by lordsk8** [HellscreamWoW/Tracker#4129]
Hello guys, I'm new on the server, and found a buged quest.

http://www.wowhead.com/quest=24974/ever-so-lonely

Name: Ever So Lonely
Start: Sedrick Calston
Location: Eastern Kingdoms > Tirisfal Glades > Calston Estate

Bug: The Murlock don't follow you after tamed.

Any help?

Thx.

**Comment by Warjakh** [comment]
Ref# 3523
