### ISSUE TITLE
Warrior Protection Bladed Armor

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#432]
I notice one thing after I choice Warrior Protection. Instead to get Bladed Armor which give 100% Attack Power of your Bonus Armor somehow I get Execute which is only to get from Fury.

**Comment by ticklex** [comment]
Bladed Armor is a spell for ALL tanking classes-not only for warrior!
http://www.wowhead.com/spell=161608/bladed-armor

**Comment by EPS1L0N** [comment]
not a bug

**Comment by EPS1L0N** [comment]
ref #2266
