### ISSUE TITLE
Uhhh professions?

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#442]
Been waiting months for this now... come on.

**Comment by Reloque** [comment]
Shouldn't this be a label, instead? [Type-Profession]

**Comment by Malae1** [comment]
Inscription - Unable to Mill Herbs at a Cataclysm level.
Enchanting - creating Scrolls of X enchant sometimes creates a large amount of them.

**Comment by ticklex** [comment]
Mists of Pandaria items cant be disenchanted!
