### ISSUE TITLE
Chi's drunk

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#483]
"I'm getting a strange bug. Sometimes when I relog I appear to have 11 chi's and after I get level they dissapear (good) 

But sometimes when I jab some mob it gives me 3 chi and when I use a spell that  takes 1 chi fro me it takes 2 or 3 and if this happends in PvP it will be really annoying. Please fix the chi's "

**Comment by HellscreamWoW** [comment]
#2266 Fixed a long time ago.
