### ISSUE TITLE
James Clark should drop a Gold Schedule

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#502]
"James Clark [13159] in Eastvale Logging Camp, Elwynn Forest should have a high chance [~79%] to drop the Gold Pickup Schedule [1307].

See http://www.wowhead.com/item=1307/gold-pickup-schedule#dropped-by"

**Comment by HellscreamWoW** [comment]
ref #502

**Comment by HellscreamWoW** [comment]
http://www.hellscream-wow.com/log#2015.14.06.010545
