### ISSUE TITLE
vote service

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#510]
"hello my name is Sytarra  and im selling vote at xtremetop100
and any web site rank
we already can solve any captcha
we can make your server number one at your game Categorie
and u can have test for free to see our service speed

if u like to buy votes u can contact me at skype or send me message to my email

my email is: sytarra@gmail.com
skype: sawa_lv2

"

**Comment by EPS1L0N** [comment]
lol
