### ISSUE TITLE
[Quest] Proving Pit

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#513]
"http://www.wowhead.com/quest=24642/proving-pit

Can't complete quest beacause when i come to NPC i should talk to (http://www.wowhead.com/npc=39062) there's missing option to say him something.. so Naga won't come out of cage."

**Comment by GMTyrial** [comment]
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/981
