### ISSUE TITLE
[brewmaster] Blackout Kick

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#523]
"http://www.wowhead.com/spell=100784/blackout-kick
""dealing [6.4 * ((1.0 * (1 + $versadmg)) * (0.857143 * (Mainhand Min DPS + 1 * (Offhand Min DPS /2)) + Attack power / 3.5 - 1))] to [6.4 * ((1.0 * (1 + $versadmg)) * (0.857143 * (Mainhand Max DPS + 1 * (Offhand Max DPS /2)) + Attack power / 3.5 + 1))] Physical damage""
But deals 1 dmg & 2 crit dmg"

**Comment by EPS1L0N** [comment]
ref #165
