### ISSUE TITLE
[brewmaster] stance of sturdy ox

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#525]
"http://www.wowhead.com/spell=115069/stance-of-the-sturdy-ox
how it should work: Increases armor by 75%, increases Stamina by 25%, reduces magic damage taken by 15% and While in this stance, you will Stagger damage taken.
http://www.wowhead.com/spell=124255/stagger
You shrug off physical attacks, causing 70% of the damage to happen instantly and the remaining 30% to be divided over 10 sec. Stagger must be shown as a buff! 

what happens: stance acts like a priest's shield. Dmg is simply absorbed. If the dmg=absorb then the stance simply cancels. So you have to re-activate the stance and absorb again."

**Comment by Guybrush-Hellscream** [comment]
same as https://github.com/HellscreamWoW/Tracker/issues/338 and https://github.com/HellscreamWoW/Tracker/issues/1167

**Comment by Moustachos** [comment]
Fixed on next update.
