### ISSUE TITLE
[brewmaster] Elusive Brew

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#528]
"http://www.wowhead.com/spell=115308/elusive-brew
how it should work:
Passive: Your autoattack critical strikes grant up to 3 stacks of Elusive Brew, which can stack up to 15 times.
Use: Consumes all stacks of Elusive Brew to increase your chance to dodge melee and ranged attacks by 45% for 1 sec per stack.

what happens: Doesnt build up any stacks and so cant never be used!"

**Comment by Guybrush-Hellscream** [comment]
Sometimes i get some stacks but it's kinda rare and i don't know in what circumstances!

**Comment by HellscreamWoW** [comment]
This was fixed a while ago:
http://hellscream-wow.com/log#2015.6.06.010536
