### ISSUE TITLE
Tabard Vendor Stormwind 

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#539]
NPC is missing, cannot purchase Guild Tabard

**Comment by Reloque** [comment]
The NPC is [Rebecca Laughlin](http://www.wowhead.com/npc=5193), found in The Trade District, Stormwind. I don't remember whether Rebecca actually has a functioning gossip, though (I have come across tabard vendors who don't).
[Lisa Steelbrow](http://www.wowhead.com/npc=5049) in The Commons, Ironforge is functioning.
