### ISSUE TITLE
[ITEM] [MAILBOX] [HEIRLOOM-TAB]

### ISSUE THREAD

**Issue by Rozark** [HellscreamWoW/Tracker#554]
heirlooms (or maybe items in general) are not sent back after 30 days if they were not taken out of mailbox by the recipient (pre-heirloom-tab incident), so they seem to be lost that way. they should appear in the heirloom tab. (maybe you could link the purchase history of your coin-/voteshop to the heirloom-tab)

**Comment by Reloque** [comment]
The heirloom problem could be prevented with [this suggestion](http://www.hellscream-wow.com/forum/viewtopic.php?f=25&t=1058). That still wouldn't necessarily fix this problem, though.

**Comment by Max-Hellscream** [comment]
Linking the purchase history to the heirloom tab is not a bad idea actually.
