### ISSUE TITLE
First Mate Fitzsimmons is missing

### ISSUE THREAD

**Issue by Reloque** [HellscreamWoW/Tracker#565]
[First Mate Fitzsimmons](http://www.wowhead.com/npc=1239)(1239), a questgiver in Menethil Harbor, Wetlands, is missing or phased out. He should be sitting on the sandbags next to the mailbox in front of Deepwater Tavern. He starts [The Third Fleet](http://www.wowhead.com/quest=25815)(25815) and [Cursed to Roam](http://www.wowhead.com/quest=25816)(25816), and ends The Third Fleet. These quests are the first two in a chain of five, not to mention it is normally required to get [Swiftgear Station](http://www.wowhead.com/quest=26980)(26980), the quest which sends you out of Menethil Harbor.

As of right now, [Swiftgear Station is offered anyways](https://github.com/HellscreamWoW/Tracker/issues/552), so players can currently advance to the rest of Wetlands without these quests; however, they miss out on the entire chain.

**Comment by Max-Hellscream** [comment]
Fixed in next update.
