### ISSUE TITLE
Lockpicking

### ISSUE THREAD

**Issue by Reloque** [HellscreamWoW/Tracker#572]
Something is wrong with lockpicking. My lv.51 rogue cannot lockpick([Pick Lock](http://www.wowhead.com/spell=1804)(1804)) a [Sturdy Junkbox](http://www.wowhead.com/item=16884)(16884). The skill level for a Sturdy Junkbox is 175, and a rogue's lockpicking skill *should be* (Level * 5), as advertised in the tooltip for the ability.
51*5=255
255 > 175
I should be able to pick a Sturdy Junkbox at level 51.

Note that Lockpicking is no longer a profession and does not require practice, rather the "skill" is always your level * 5. It's just an ability now.

**Comment by Max-Hellscream** [comment]
Ah yes, this issue. I was able to fix it on 5.x. I'll need to do a little research first to see if anything changed in WoD. Thanks for the report.

**Comment by EPS1L0N** [comment]
ref #442
