### ISSUE TITLE
fredgling brave

### ISSUE THREAD

**Issue by andrija2567** [HellscreamWoW/Tracker#577]
in red cloud mesa taurens that shoot with their guns are attacking the bristlebacks invaders with their spears and since the hostiles cant be killed by  taurens they just hitting them without any affect and not shooting their guns that takes from the atmosphere of the zone

**Comment by Max-Hellscream** [comment]
This is a bug which was introduced with a last minute addition to the update. This addition is also causing the server crashes. We're working on getting that fixed.
