### ISSUE TITLE
 Guild Master NPC in IronForge/Tabard Crest Issues

### ISSUE THREAD

**Issue by DelphineGnome** [HellscreamWoW/Tracker#581]
Having a problem with creating/changing guild crest for my guild. I created a crest originally, the NPC took money but gave me a completely crest to what i had chosen for our guild tabards.

Tried to change it a number of times, he either changes it to a random design or doesnt do anything at all but still takes the 10g each time. 

Kindly address when possible.

Thanks

**Comment by Reloque** [comment]
#505

**Comment by EPS1L0N** [comment]
duplicate of #505
