### ISSUE TITLE
[QUEST] The truth of the Grave

### ISSUE THREAD

**Issue by ENTiTY01** [HellscreamWoW/Tracker#584]
i can't talk to the npc

**Comment by andrija2567** [comment]
you cant just post like this you need to say what npc, where is the npc is he part of the quest,is he a vendor not just cant talk

**Comment by d34d4nh3r0** [comment]
Can't Use Mirror Item on Voss NPC
https://github.com/HellscreamWoW/Tracker/issues/286

**Comment by Guybrush-Hellscream** [comment]
[Fixed.](http://www.hellscream-wow.com/log#2015.21.09.020012)
