### ISSUE TITLE
(Quest) Tree's Company...

### ISSUE THREAD

**Issue by Aedomus** [HellscreamWoW/Tracker#593]
Objective; Admiral Odesyus at Odesyus' Landing on Azuremyst Isle wants you to observe the meeting that is to take place between Geezle and the traitor.

Issue; Tree Disguise Kit works...but when used the meeting never takes place between Geezle and the traitor.

http://www.wowhead.com/quest=9531/trees-company

**Comment by EPS1L0N** [comment]
ref #380
