### ISSUE TITLE
Loch Buzzard

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#597]
http://www.wowhead.com/npc=44184/loch-buzzard

Sometimes after killing a Loch Buzzard, they have a tendency to constantly rubber band up and down. For the ones that glitch, you have to get really close to them to get "in range" for spells (standing next to them to be able to cast a frostbolt).

![wowscrnshot_052415_163711](https://cloud.githubusercontent.com/assets/12555606/7789550/5d66dbd0-0233-11e5-860b-4763dc88101c.jpg)

![wowscrnshot_052415_164719](https://cloud.githubusercontent.com/assets/12555606/7789576/93e1f8ec-0234-11e5-9d86-ddcc963eccb1.jpg)

**Comment by Max-Hellscream** [comment]
Should be fixed now, let me know if you run across it again.

**Comment by GeneralCaveman** [comment]
Like right now or next update?

**Comment by Max-Hellscream** [comment]
Not all issues require a server restart :)  This issue should be fixed now.

**Comment by GeneralCaveman** [comment]
Yep, you got em fixed.
