### ISSUE TITLE
(Duplicate NPC) The Kurken is Lurkin

### ISSUE THREAD

**Issue by Aedomus** [HellscreamWoW/Tracker#598]
Issue; There are 2 of http://www.wowhead.com/npc=17443/kurz-the-revelator

**Comment by Max-Hellscream** [comment]
Are you sure the duplicate NPC is Kurz the Revelator? There is only one of this NPC in the database. The others are Stillpine Defenders which have the same appearance as Kurz The Revelator.

**Comment by Aedomus** [comment]
Let me double check to make sure...

**Comment by Max-Hellscream** [comment]
Fixed. Thanks for the report.
