### ISSUE TITLE
(Quest) Mac'Aree Mushroom Menagerie

### ISSUE THREAD

**Issue by Aedomus** [HellscreamWoW/Tracker#605]
Objective; Jessera of Mac'Aree at Blood Watch wants 1 Aquatic Stinkhorn, 1 Blood Mushroom, 1 Ruinous Polyspore, and 1 Fel Cone Fungus.

Issue; None of the plants are loot-able.

http://www.wowhead.com/quest=9648/macaree-mushroom-menagerie

**Comment by Guybrush-Hellscream** [comment]
It's working. #2235
