### ISSUE TITLE
(QUEST) Sunken treasure - Arathi Highlands

### ISSUE THREAD

**Issue by Kelpo122** [HellscreamWoW/Tracker#608]
Quest: http://www.wowhead.com/quest=26051/sunken-treasure
Objective: Recover 10x Elven Gems http://www.wowhead.com/item=4492/elven-gem from http://www.wowhead.com/object=2712/calcified-elven-gem

Isue: There is only one Calcified Elven Gem in the whole bay

**Comment by Malae1** [comment]
Confirmed, adding more spawns.
