### ISSUE TITLE
Beast mastery pet talents.

### ISSUE THREAD

**Issue by Aversong** [HellscreamWoW/Tracker#613]
You can't learn pet's talents. It shows you to learn them, but whenever you click learn, it doesn't do nothing, nothing happends.

![wowscrnshot_052515_132702](https://cloud.githubusercontent.com/assets/12594712/7795867/cc706cea-02e1-11e5-9a56-1f9374149480.jpg)

**Comment by DrEhsan** [comment]
http://hellscream-wow.com/log#2015.6.06.010536
