### ISSUE TITLE
Item Quest Drop Rate

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#646]
It seems that collection quest items are not dropping correctly off of mobs. It's almost as if the quest items also have a x1 drop rate when questing. For example, collection quests like Kobold Candles, Gold Dust Exchange, and Goldtooth all take an unnecessary amount of time to complete because their quest items do not drop after killing the mobs. It takes multiple tries to get the quest items when it should not, these items should drop from these mobs after you kill them.  There is a topic on the forums I will link that also discuss the issue but it seems worsen when players are in a party.
http://www.hellscream-wow.com/forum/viewtopic.php?f=28&t=1056&p=6469&hilit=quest+drops#p6469

**Comment by Guybrush-Hellscream** [comment]
Fixed for "Kobold Candles", "Gold Dust Exchange" and "Goldtooth". Make a new issue if you have other quests. :palm_tree:
