### ISSUE TITLE
Lost in the Floods

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#650]
Cannot use quest item Thonk's Spyglass. Whenever I try to use it at Razor Hill Watch Tower error text pops up saying that I must be at Razor Hill Watch Tower when I already am.
Quest:
http://www.wowhead.com/quest=25187/lost-in-the-floods

**Comment by AuraChan** [comment]
Close this issue it has already been reported. I forgot to search to see if someone else had reported this quest.

**Comment by Max-Hellscream** [comment]
ref #589
