### ISSUE TITLE
The Kodo's Return

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#660]
Player cannot complete this quest since NPC Kranal Fiss is missing. The kodo is supposed to follow the player back the the farm.

Quest Details:
http://www.wowhead.com/quest=13971/the-kodos-return
NPC Details:
http://www.wowhead.com/npc=5907/kranal-fiss#comments

**Comment by Max-Hellscream** [comment]
Fixed in coming update.
