### ISSUE TITLE
Tainted Screecher

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#680]
http://www.wowhead.com/npc=42338/tainted-screecher

The aggro of Tainted Screechers seem to vary. All of them are targetable however

-most do not respond to attack (it does no damage either) or entering their aggro range
-some you have to enter their hitbox to aggro them
-some work as intended or perhaps have a smaller aggro radius than it should.

**Comment by Max-Hellscream** [comment]
Fixed.
