### ISSUE TITLE
Light's Hope Chapel flight path

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#684]
When flying from Ebon Hold in the Eastern Plaguelands, the flight prematurely stopped at Light's Hope Chapel. When I landed, I am unable to interact with the flight master there.

**Comment by Reloque** [comment]
Other flight masters in the region are also unresponsive, according to #253

**Comment by tribaljet** [comment]
It seems the other flight masters are working now, but Khaelyn Steelwing isn't yet.
