### ISSUE TITLE
The Twilight Lexicon

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#687]
http://www.wowhead.com/quest=8279/the-twilight-lexicon

This can be deleted if untrue but I have a feeling the chapters are supposed to have a 100% drop rate when the quest is active. Wowhead's rates are sometimes skewed as it doesn't always take into account if the person submitting the data is on the quest or not.

http://db.vanillagaming.org/?quest=8279

**Comment by Max-Hellscream** [comment]
They don't have a 100% drop rate:
http://www.wowhead.com/item=20394/twilight-lexicon-chapter-1#dropped-by
http://www.wowhead.com/item=20395/twilight-lexicon-chapter-2#dropped-by
http://www.wowhead.com/item=20396/twilight-lexicon-chapter-3#dropped-by

**Comment by GeneralCaveman** [comment]
I know the wowhead stats but those stats at times combine the drop rates of both people with the quest and without the quest. So people with the quest get 100% drop rate and those without get 0% and wowhead mixes those numbers together.

Ok, I looked into it more and it seems the official WoW game guide suggests that these drops should be 100% for those on the quest.

http://us.battle.net/wow/en/item/20394
http://us.battle.net/wow/en/item/20395
http://us.battle.net/wow/en/item/20396

**Comment by GeneralCaveman** [comment]
If you have the in-game retail statistics then that's that but if you are basing this decision based on wowhead then I have to ask you to reconsider.

**Comment by Max-Hellscream** [comment]
Thank you for the link to the official guide. The entirety of our loot templates are solely based on information gathered from Wowhead. We expect flaws in the data and hope to correct them as we come across them.

**Comment by GeneralCaveman** [comment]
The main problem with the official guide is the lack of specific numbers outside of "guaranteed" or 100% drops.

I do have a question related to this, is there a method/resource to determine the actual drop rate of something? Because I know a lot... nearly all private servers get their data from wowhead and problems like this occurs

http://www.wowhead.com/item=34114/schematic-field-repair-bot-110g#comments

Because wowhead combines the drop rate for engineers, non-engeineers (who it doesnt drop for) and the drop rates from before this item was even added to the game, the number is drastically lower than it should be for engineers (itshould be around 10-20 percent). The problem is that wowhead doesn't sort these drops rates and I cannot find the exact drop rate for this item for engineers.

**Comment by Max-Hellscream** [comment]
There is no method to determine the actual drop rate of something, unfortunately. This is information stored server-side on retail, and the best approximation we have is the cumulative data of wowhead sniffs. We'll have to manually correct inconsistencies.
