### ISSUE TITLE
Helboar, the Other White Meat

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#703]
http://www.wowhead.com/quest=9361/helboar-the-other-white-meat#comments
http://www.wowhead.com/item=23270/tainted-helboar-meat

It seems that Deranged Helboar don't drop the Tainted Helboar Meat needed for the quest 'Helboar, the Other White Meat'.

**Comment by Guybrush-Hellscream** [comment]
Fixed. :palm_tree:
