### ISSUE TITLE
An Ambitious Plan

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#705]
http://www.wowhead.com/quest=9383/an-ambitious-plan

When using the Sanctified Crystal on a Uncontrolled Voidwalker, nothing happens (error: You can do that yet).

**Comment by K-Reeboo** [comment]
As of today (1/1/2016), this quest is working.

You have to trigger the Sanctified Crystal only when Uncontrolled Voidwalker has 10%-15% life left.
A 'red floating crystal' will appear in front of you. Activate it and quest is updated.
