### ISSUE TITLE
Shaman Lightning Shield

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#720]
If you cast Lightning Shield and are then attacked by a mob, the buff disappears. The buff is supposed to stay and be stackable. Here is more info on the skill directly from WowHead:

 Lightning Shield can be considered as the new resources for Elemental  Shaman, one can have 7 charge max, but as the original charge will never be consumed, so it actually means on can have 6 surplus  Lightning Shield charge max.
it generate by (spell triggered by Mastery: Elemental Overload function same):
Lightning Bolt (has a 60% chance to generate 1  Lightning Shield charge ((Spell #88764) ( Item - Shaman T14 Elemental 4P Bonus double this effect)))
Chain Lightning (each jumps has a 60% chance to generate 1  Lightning Shield charge; Lava Beam (switch by Elemental  Shaman turn into Fire ascendant) function same ((Spell #88764) ( Item - Shaman T14 Elemental 4P Bonus double this effect)))
 Improved Lightning Shield
and when  Shaman have surplus  Lightning Shield charge, this spell can be cast to consume all surplus  Lightning Shield charge:
Earth Shock (deal additional damage of all consumed surplus  Lightning Shield charge ( Fulmination); debuff target with Weakened Blows)

Spell Details:
http://www.wowhead.com/spell=324/lightning-shield

**Comment by Althin** [comment]
Still didn't work as retail. Please repair it fast.
