### ISSUE TITLE
High Road Scout

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#724]
There are only 3 High Road Scouts in the quest area with one of them under the map (it is aggro-able, somewhere around location 35.3,14.6). 

Mob Details:
http://www.wowhead.com/quest=24504/clear-the-high-road

**Comment by Reloque** [comment]
According to [this video](https://www.youtube.com/watch?v=WcDR-R1n9e4), there should be... 4?

**Comment by Max-Hellscream** [comment]
Fixed in coming update.
