### ISSUE TITLE
Random critters are attacking me

### ISSUE THREAD

**Issue by ENTiTY01** [HellscreamWoW/Tracker#731]
When i go do a quest in Northern Barrens i noticed that was attacked my random critters like rabbits etc. The problem is that they attack so fast they won't let me click on the item i need to gather or something else. Its not a big problem but it is annoying, and i can't click on them.

Here's a screenshot: http://postimg.org/image/oivpa2vov/

**Comment by Max-Hellscream** [comment]
*Chuckle* Hellscream's rabbits unite!
