### ISSUE TITLE
Princess Drops

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#748]
http://www.wowhead.com/npc=330/princess#drops
us.battle.net/wow/en/search?f=wowitem&page=4&q=collar

According to the the official WoW game guide, Princess should be dropping the collar every time but it currently isn't.

**Comment by Max-Hellscream** [comment]
Thanks for this.

**Comment by HellscreamWoW** [comment]
http://www.hellscream-wow.com/log#2015.14.06.010545
