### ISSUE TITLE
Honor's Stand Officer

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#754]
Horde players cannot attack Honor's Stand Officer but the npc can attack player. This NPC is also needed for the quest Put the Fear in Them.

NPC Details:
http://www.wowhead.com/npc=37216/honors-stand-officer

**Comment by Max-Hellscream** [comment]
ref #752

**Comment by AuraChan** [comment]
This report is different from my other report. This one is for the NPC Honor Officer while the one you ref. is for Honor Guards.
