### ISSUE TITLE
NPC-quest

### ISSUE THREAD

**Issue by Agrail** [HellscreamWoW/Tracker#768]
NPC Vindicator Aldar gives two same quests. Quest name is Inoculation.

**Comment by Guybrush-Hellscream** [comment]
Looking at wowhead, one is from 3.3.0 and the other from 6.0.2, not sure if they're supposed to be two of them though.
http://www.wowhead.com/quest=37444/inoculation

**Comment by Guybrush-Hellscream** [comment]
Fixed.
