### ISSUE TITLE
NPC Thyssiana

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#789]
This NPC attacks Horde players when it should not.

NPC Details:
http://www.wowhead.com/npc=40345/thyssiana

**Comment by Kelpo122** [comment]
But that link there says that she reacts hostile agaisnt horde...

**Comment by AuraChan** [comment]
She isn't supposed to react to horde players next to her even if she is alliance. When I get on my laptop I'll try to post a video on her. But when you get near her she goes after you and she ain't supposed to do that.
