### ISSUE TITLE
Obsidian Warbeads

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#793]
http://www.wowhead.com/item=25433/obsidian-warbeads

It looks like these Warbeads currently drop from the Warmaul ogres they are supposed to.

**Comment by GeneralCaveman** [comment]
http://www.wowhead.com/quest=10476/fierce-enemies

It seems like they only drop when this quest is active. I believe they are supposed to drop all of the time.

**Comment by Malae1** [comment]
Fixed in next update.
