### ISSUE TITLE
[Quest: Unruley Neighbors]

### ISSUE THREAD

**Issue by MythicBird** [HellscreamWoW/Tracker#799]
The quest is completable until you need to turn it in.
Theloria Shadecloak at Allerian Post is not present, so you cannot turn it in.

EDIT: NPC Info; http://www.wowhead.com/npc=18565/theloria-shadecloak

**Comment by silverjade** [comment]
The NPC is now present. This quest can now be completed.

**Comment by Malae1** [comment]
Ref #2235
