### ISSUE TITLE
Feast or Famine

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#809]
http://www.wowhead.com/quest=26230/feast-or-famine

Way more often than not, when picking up the fresh dirt, the loot window immediately closes and you receive nothing.

**Comment by GeneralCaveman** [comment]
This might be a problem with autoloot being on.

**Comment by Max-Hellscream** [comment]
It may be another drop chance issue, and the window closing immediately because auto-loot is on.

**Comment by GeneralCaveman** [comment]
Oh wow, you are right. I didn't realize that wowhead gave it a 1/4 chance of dropping.

**Comment by Guybrush-Hellscream** [comment]
Droprate is "Guaranteed" on retail and it was 100% on Hellscream, so all good.
