### ISSUE TITLE
Dawning Wood Catacombs invisible creature

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#811]
http://wowwiki.wikia.com/Dawning_Woods_Catacombs
http://www.wowhead.com/quest=26753/the-halls-of-the-dead

In the Dawning Wood Catacombs, I got attack by some creature/creatures I couldn't see and hit for pretty damn hard.

After looking it up, there are some ghouls and elites that are supposed to be there but I can't see them. So I presume those are what is killing me.

**Comment by silverjade** [comment]
I can confirm, the first room you enter from the back entrance (tunnel) with the dirt floor & silent shade mobs has something unseen in it that can detect you even in prowl. It seemed confined to that room though as when I left it (at very low health) it didn't follow me out beyond it.

**Comment by silverjade** [comment]
The invisible mobs in question are apparently called Buried Corpses. You can't see them or target them. AOE has no affect on them either. They're invincible. They continue attacking until you die or flee the room, and once you're half way into either of the adjoining rooms, they'll finally leave you alone.

**Comment by Malae1** [comment]
Fixed in next update
