### ISSUE TITLE
(QUEST) Those That Couldn't let Go - Western Plaguelands

### ISSUE THREAD

**Issue by Kelpo122** [HellscreamWoW/Tracker#816]
http://www.wowhead.com/quest=27168/those-that-couldnt-let-go

Using the Holy Thurible (http://www.wowhead.com/item=60861/holy-thurible) on Withdrawn Souls (http://www.wowhead.com/npc=45166/withdrawn-soul) does not give credit, the target npcs do not react in any way.

**Comment by GMTyrial** [comment]
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/2022
