### ISSUE TITLE
Runeforging

### ISSUE THREAD

**Issue by THEplaguee** [HellscreamWoW/Tracker#818]
As a DK, when you try to runeforge your weapon in Ebon Hand, even if you stand beside runeforge, you are still unable to runeforge...it says "Requieres Runeforge"

**Comment by Reloque** [comment]
Hmm. I *was* able to do this on my Death Knight in the Heart of Archerus, Plaguelands: The Scarlet Enclave. This problem may be exclusive to the Archerus on the Eastern Kingdoms map and just be a missing object rather than a problem with the spell.

**Comment by Max-Hellscream** [comment]
Type-Spell is just a note for the developers. The issue here is a missing object which appears only serverside. We're not able to capture these objects in sniffs. Since we recently respawned the world using fresh sniffs, many of these objects were lost.

**Comment by EPS1L0N** [comment]
ref #2266
