### ISSUE TITLE
Into the Draenethyst Mine

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#829]
http://www.wowhead.com/quest=10510/into-the-draenethyst-mine
http://www.wowhead.com/item=30315/draenethyst-mine-crystal

You are currently unable to obtain these crystals from the crystal formations lining the cave.

**Comment by Reloque** [comment]
As a workaround, Wowhead says the crystals drop from [Bloodmaul Drudger](http://www.wowhead.com/npc=21238)s.

**Comment by GeneralCaveman** [comment]
Yes, they have a pretty low chance of dropping (according to wowhead) so I am just grinding them out for now.

**Comment by Reloque** [comment]
The game object is [Draenethyst Mine Crystal](http://www.wowhead.com/object=184689)(184689).

**Comment by Trekex** [comment]
I could collect the crystals from the crystals formations as it should be. You can close this post :D

**Comment by Guybrush-Hellscream** [comment]
Confirmed.
