### ISSUE TITLE
[class] warrior - Shield Slam

### ISSUE THREAD

**Issue by ticklex** [HellscreamWoW/Tracker#846]
How it should work: Slam the target with your shield, causing [(Attack power * 0.366 * 1 * 1 * (1 + $versadmg))] damage and generating 20 Rage. 
How it works: Does 1 dmg (2 critical).
http://www.wowhead.com/spell=23922/shield-slam

**Comment by Reloque** [comment]
#444

**Comment by Max-Hellscream** [comment]
Thanks Reloque
