### ISSUE TITLE
Bronk limited supply

### ISSUE THREAD

**Issue by Reloque** [HellscreamWoW/Tracker#849]
Alchemy Supplies vendor [Bronk](http://www.wowhead.com/npc=8158)(8158) in Camp Mojache, Feralas sells unlimited amounts of multiple items which should be in limited supply.

[Recipe: Ghost Dye](http://www.wowhead.com/item=9302)(9302) should have a stock of one.
[Superior Healing Potion](http://www.wowhead.com/item=3928)(3928) should have a stock of two.
[Greater Mana Potion](http://www.wowhead.com/item=6149)(6149) should have a stock of two.
[Recipe: Nature Protection Potion](http://www.wowhead.com/item=6057)(6057) should have a stock of one.

**Comment by Max-Hellscream** [comment]
Thank you for this level of detail.
