### ISSUE TITLE
[class] warrior - Deep Wounds

### ISSUE THREAD

**Issue by ticklex** [HellscreamWoW/Tracker#850]
How it should work: 
Your Mortal Strike, Bloodthirst, Devastate, and Thunder Clap cause the target to bleed for (420% of Attack power) Physical damage over 15 sec.
How it works: Bloodthirst and Devastate dont cause a bleeding.
http://www.wowhead.com/spell=115767/deep-wounds

**Comment by EPS1L0N** [comment]
Bloodthirst isn't supposed to apply deep wounds (tooltip is wrong), however devastate is.

**Comment by EPS1L0N** [comment]
#2266
