### ISSUE TITLE
[class] warrior - Wild Strike

### ISSUE THREAD

**Issue by ticklex** [HellscreamWoW/Tracker#854]
How it should work: A quick strike with your off-hand weapon that deals 375% Physical damage and reduces the effectiveness of healing on the target for 10 sec.  Bloodthirst has a 20% chance of granting 2 charges of Wild Strike that cost no Rage.
How it works: Doesnt neither do damage nor it shows any animation. Completely without any function.
http://www.wowhead.com/spell=100130/wild-strike

**Comment by Kelpo122** [comment]
I have to add here that this problems seems to only be on Dual 2-handed weapons Fury Warriors, I'm Dual 1-handed and can use this spell w/o problems

**Comment by Vodkanator** [comment]
you can spell Wild Strike as fury with 1 2h and 1 1h weapon though

**Comment by Kelpo122** [comment]
yes, that that kills the purpose of fury warriors, you waste the 2 1h or 2 2h bonus

**Comment by Gingerspice** [comment]
Just thought I'd voice that I just hit level 18 and came across this as well. 

Haha and its quite funny because I have been eagerly awaiting hitting 18 so that I could get it

**Comment by EPS1L0N** [comment]
#2266
