### ISSUE TITLE
Whelps of the Wyrmcult

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#864]
http://www.wowhead.com/quest=10747/whelps-of-the-wyrmcult

You can use the net on the whelps and the net attaches to them but you don't get credit for capturing them.

**Comment by Guybrush-Hellscream** [comment]
it worked for me!

**Comment by Dushku** [comment]
It worked for me also. Even if I was already in combat with the targeted Blackwhelp.

**Comment by Guybrush-Hellscream** [comment]
Oops, thanks that's edited!
