### ISSUE TITLE
Westfall Missing Npcs

### ISSUE THREAD

**Issue by AuraChan** [HellscreamWoW/Tracker#871]
There are a few npcs missing near Jansen Stead. Some were supposed to be solved according to the Changelog on the site but are still missing. These npcs are:
Lieutenant Horatio Laine (reported but closed #297)
Stormwind Investigator
Farmer Furlbrow (reported but closed #270)
Verna Furlbrow
Old Blanchy

http://www.wowhead.com/npc=42308/lieutenant-horatio-laine#starts
http://www.wowhead.com/npc=42309/stormwind-investigator#ends
http://www.wowhead.com/npc=237/farmer-furlbrow#comments
http://www.wowhead.com/npc=238/verna-furlbrow
I can't find a proper link to give for poor Old Blanchy so if you have a helpful link please leave it here.

**Comment by GeneralCaveman** [comment]
www.wowhead.com/npc=582/old-blanchy

I think the problem you made have had was that you didn't click "Westfall" after "This NPC can be found".

**Comment by Reloque** [comment]
Last time I was in Sentinel Hill I saw the Stormwind Investigator, and could turn in my quest to him. This is a workaround, however, and does not entirely solve the problem.

**Comment by AuraChan** [comment]
Oh woops lol Thank you for linking, really appreciate it! On another note, there is another missing NPC.

Two-Shoed Lou
http://www.wowhead.com/npc=42405/two-shoed-lou

**Comment by Max-Hellscream** [comment]
The NPCs which were spoken of in the changelog are present. They have an aura applied to them which makes them invisible to you. The quest progression of the zone will need to be scritped before you can see the npcs for each given phase of the quest.

**Comment by HellscreamWoW** [comment]
ref #2235
