### ISSUE TITLE
Captured Northwatch Scout is not captured in the cage

### ISSUE THREAD

**Issue by MirrorWraith** [HellscreamWoW/Tracker#877]
http://www.wowhead.com/npc=39215/captured-northwatch-scout

He should be located and LOCKED in the cage, in this server, they were located in the cage but they could walk over the cage

thanks

**Comment by MirrorWraith** [comment]
That's in The Den, Valley of Trials, Orc starting zone

**Comment by Max-Hellscream** [comment]
Oops. We may have given them random movement.
