### ISSUE TITLE
 Mistweaver Monks not regening mana

### ISSUE THREAD

**Issue by Narteisok** [HellscreamWoW/Tracker#884]
i just reached level 10 and my mist weaver monk got mana added as a thing, but she won't regen. Even if i drink water or other mana Regen items

**Comment by Narteisok** [comment]
Also, surging mist doesn't actually heal... at all.

**Comment by Max-Hellscream** [comment]
Monks are a work in progress. Today's release was an initial release, much more is planned for this class in the coming updates.
