### ISSUE TITLE
Bids are deleted after server restart

### ISSUE THREAD

**Issue by Reloque** [HellscreamWoW/Tracker#889]
This one would be huge if people used the Auction House. I had a chance to test it out during the last three back-to-back server restarts (hopefully it wasn't me crashing it!).

**Comment by Reloque** [comment]
related or same as #211

**Comment by CursedCat** [comment]
Posting items as well ...

**Comment by GeneralCaveman** [comment]
I know it was stated on the forums but this problem has returned.
