### ISSUE TITLE
(QUEST) Perfectly Pure - The Cape of Stranglethorn

### ISSUE THREAD

**Issue by Kelpo122** [HellscreamWoW/Tracker#890]
http://www.wowhead.com/quest=26817/perfectly-pure

When you click on The Holy Spring (http://www.wowhead.com/object=759/the-holy-spring) you do not get Pure Water (http://www.wowhead.com/item=60386/pure-water) everytime, had to wait for 3 respawns to get it.
WoWHead says the drop chance is 65% but you dont get any other of the drops the Spring can give, you only get an empty loot window that instantly closes.

**Comment by Guybrush-Hellscream** [comment]
it should have 100% drop rate.
