### ISSUE TITLE
The Hunt is On

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#940]
www.wowhead.com/quest=11794/the-hunt-is-on

After discovering these guys, they are supposed to speak a line of dialogue or two before turning hostile but currently do not.

**Comment by Dushku** [comment]
Might this have been resolved? They spoke lines and turned hostile. Quest appears to function Blizz-like.

**Comment by Guybrush-Hellscream** [comment]
Oh yes, thank you for pointing that up. I managed to do this quest while go. Definitely working atm.

**Comment by Guybrush-Hellscream** [comment]
#2235
