### ISSUE TITLE
Kvaldir Raider double/out lot of spawns

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#945]
http://www.wowhead.com/npc=25760/kvaldir-raider

These guys seem to be currently double/triple spawning.

Edit: Well it seems to be worse than a double spawn, there are mobs of these guys all over the place.

![wowscrnshot_060715_213545](https://cloud.githubusercontent.com/assets/12555606/8027063/3817d516-0d5d-11e5-8755-28e86fa2b11a.jpg)

**Comment by HellscreamWoW** [comment]
Best place to farm Frostweave until it's fixed :)

**Comment by GeneralCaveman** [comment]
Well once Death Knight gets it's rune system/Death and Decay/Blood Boil/DoTs fixed, I will be all over it like a fat kid on candy.

**Comment by GeneralCaveman** [comment]
![wowscrnshot_072915_233941](https://cloud.githubusercontent.com/assets/12555606/8975342/1dedcc74-364b-11e5-8e25-628c1619de56.jpg)
