### ISSUE TITLE
Energy Regen issue

### ISSUE THREAD

**Issue by crohde7707** [HellscreamWoW/Tracker#970]
Introduced in Wrath, the regen of energy (rogues, cat form druids, etc) went from a chunk-like regen style to a consistent regen style. Currently, the energy regen is behaving pre-wrath

From the patch logs (http://wow.gamepedia.com/Patch_3.0.2):
WotLK Patch 3.0.2 (2008-10-14): Energy no longer uses the "tick" system and instead regenerates in real time. Regeneration went from 20 energy per tick to 1 energy per decisecond.

**Comment by Malae1** [comment]
Have been unable to reproduce.

**Comment by crohde7707** [comment]
sorry about that! turned out to be a config problem with the UI addon that im working with, for some reason its set to the old ways by default, which is really strange to me...

**Comment by Rushor** [comment]
must be fixed in : 
if (m_regenTimerCount >= 2000)
        SetPower(power, curValue);
    else
        UpdateUInt32Value(UNIT_FIELD_POWER1 + power, curValue);
