### ISSUE TITLE
Quest bug: Never Trust a Big Barb and a Smile 

### ISSUE THREAD

**Issue by jindo1** [HellscreamWoW/Tracker#982]
I am unable to complete http://www.wowhead.com/quest=25165/never-trust-a-big-barb-and-a-smile because http://www.wowhead.com/npc=3125/clattering-scorpid do not cast http://www.wowhead.com/spell=73672/envenom , which means you cannot use the totem to counter the ability thus meaning you can't complete it.

**Comment by HellscreamWoW** [comment]
ref #932
