### ISSUE TITLE
Quest bug; "Wanted: Knucklerot and Luzran " in Ghostlands

### ISSUE THREAD

**Issue by generalu19** [HellscreamWoW/Tracker#983]
Luzran or Knucklerot heads do not appear in loot screen. Did the quest twice once i looted luzran head and second time only knucklerot`s head. i think its random only 1 head appears in loot screen from the 2 above. its still a bug i think ! did knucklerot again after 5 min and gave me the head. but it should of give me his head from the first try, not to farm him for the head!

**Comment by AndreasGr94** [comment]
mate this quest works fine i have done it with 2 characters

**Comment by generalu19** [comment]
all im saying is the head either from luzran or knucklerot doesent drop for me the first time(as they should i thnink). had to abandon quest, to do it second time, and in this 2`nd try, killed knucklerot 2 times for his head(when it must of dropped the first time). - this is my experience.

**Comment by Guybrush-Hellscream** [comment]
Fixed.
