### ISSUE TITLE
Druid - Cat's damage

### ISSUE THREAD

**Issue by MirrorWraith** [HellscreamWoW/Tracker#992]
idk either the cat's ability damage output or the ability's tooltip is true, like shred skill in tooltip it said 2,333 damage, but in reality, it's 18 damage, and so did ferocious bite
thanks

**Comment by generalu19** [comment]
i want to add that ferocius bite does not scale with combo points it always does the same damage no matter how many combo points i have.( for example im lvl 17 and it does constantly 135 dmg). 
tooltip says 1 point - 30 dmg ; 2 points - 60 dmg ; 3 points 89 dmg; 4 -119 and 5 - 149.

**Comment by HellscreamWoW** [comment]
#2266 Fixed. Will be included in update 020010.
