### ISSUE TITLE
Subterfuge

### ISSUE THREAD

**Issue by xickoh** [HellscreamWoW/Tracker#996]
When I learnt the talent Subterfuge I couldn't go Stealth anymore. On the top, the buff still appeared, but mobs could see me, and I couldn't use any stealth abilities. For that reason, I had to reset my talents, which costed 1 gold (somewhat significant for a lvl 15 rogue, I lost 80% my earnings).

This is an annoying bug, not only for the gold I spent, but also a relevant talent that can't be used.

**Comment by Mortatus** [comment]
como puedo resolverlo sin gastar oro?

**Comment by GMTyrial** [comment]
Possible solution here : https://github.com/HellscreamWoW/Tracker/issues/2005
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/2661
